### PR TITLE
PSP Vita

### PR DESCRIPTION
**Pull request by AJenbo**
For keeping track of the PSP Vita port by https://twitter.com/gokuhss (@gokuhs)
The diff is currently pretty big as some files were reformatted and vscode config added to the repo.
Another major challenge will probably be merging the code now that DevilutionX has gotten controller support, but doing this should get the Vita port to a state where we can start evaluating how to go about merging the changes.

### CODE REVIEW

**Comment by gokuhs** [comment]
Hi! 
@AJenbo Thanks for your interest! I am still working on it.

I have tried that none of my changes affect the rest of the versions, in fact if the compilation for PSVita is deactivated, the code compiles correctly.

I feel quite noob in all this, so far I had not worked with GitHub before, so if you advise me another work methodology I will be delighted :)

In theory, as I have stated, it should be "easy" to make devilutionX work with a Gamepad. I'm waiting to see how  @glebm advances, because for now my version has some bugs.

On the other hand, the multiplater game will be difficult to port it, the Vita SDK is missing many libraries so it would have to be rewritten a lot, so for the moment I discard it

**Comment by AJenbo** [comment]
Yes game pad support has been a goal for some time as it would make ports like yours more feasible. @glebm and I worked on it and it was merged yesterday.

Using vcode is fine, but you should att it's workspace to your global ignore so that it isn't accidentally added to projects you work on. 
For avoiding line formatting changes you can either selectively commit things or disable autoformating in your editor.

**Comment by AJenbo** [comment]
As you can see at the bottom of this page your code unfortunately breaks other platforms.

Most of the content from the vita folder should be moved to the Package folder. 

It looks like the changes to the game folder is largely related to the old game controller code, so once you merge with current master things should start looking a lot better.

**Comment by rsn8887** [comment]
Just in case it helps: Vita SDL library supports gamecontrollers just like Switch, so SDL game controller code from Switch should work 1:1 on Vita, I think. Touch should also work exactly the same way, because SDL supports touch on Vita just like on Switch.

**Comment by rsn8887** [comment]
Danzeff is not needed, see here how to do Vita StartTextInput using the vita on-screen keyboard provided by the Vita operating system:
https://github.com/rsn8887/julius/blob/0e104719b47efa76201ae963aec6537d145dc066/src/platform/vita/vita_input.c#L309

And this code is needed:
https://github.com/rsn8887/julius/blob/master/src/platform/vita/vita_keyboard.c

**Comment by AJenbo** [comment]
Both the controller code and touch are now part of the master branch, and the controller code in the master branch works with SDL1 also.

**Comment by rsn8887** [comment]
I don't think SDL1 even has touch support? And controller button mapping is kind of just some random assignment, so has to be re-mapped using custom code for Vita. SDL2 game controller is much nicer, because the button mappings are standardized for all platforms.

**Comment by gokuhs** [comment]
@rsn8887 yes i know SDL2 is better like SDL1 but in PSVita the performace is very very poor like SDL1. You can test It if you wish.

Edit CMakeLists.txt and set USE_SDL1 to off (line 36). May os my fault but I can't get more of 8 fps in the game.

And about the decission of use Danceff keyboard is because if I use the Vita UI; I got working; throw system UI keyboard and write but when he returned to the game, the app crashed because the surface of the SDL rendering was corrupt.  After spending a lot of time and failed to correct Danzeff rescue of codes I had from PSP.

I take a look the code of Julius but he don't use an SDL renderer...

About the touching controls, yes SDL1 don't have support, and for controls too. So I "inject" the events as SDL_UserEvents. The Switch version of the code transform it to an a Muse Events

I also have to look for a while to include in the branch all the new code that AJenbo has put in the main branch.


And because that I use SDL1 and Danzeff.

**Comment by AJenbo** [comment]
> @rsn8887 yes i know SDL2 is better like SDL1 but in PSVita the performace is very very poor like SDL1. You can test It if you wish.

Hopefully, this will be better once we have support for setting the output to 8bit instead of 32bit, and also rendering using SDL instead of for-loops.

> About the touching controls, yes SDL1 don't have support, and for controls too. So I "inject" the events as SDL_UserEvents. The Switch version of the code transform it to an a Muse Events

Hopfully this won't be needed with the controller code in the master branch as it supports SDL1 joysticks as well as SDL2 game pads.

**Comment by AJenbo** [comment]
Implemented via https://github.com/diasurgical/devilutionX/pull/1036

**Pull request closed without merging**
