### PR TITLE
StormLib: Update to upstream

### PR DESCRIPTION
**Pull request by glebm**
Updates StormLib to https://github.com/ladislav-zezula/StormLib/commit/0a9057a09f083eb4791a55eb3d9538cea9822e37

Removes all DevilutionX changes except the `#ifdef FULL` functionality trimming.

This means we lose the Xbox changes but they'll likely need to be adjusted for the new Xbox SDK anyway.

### CODE REVIEW

**Comment by glebm** [comment]
The only remaining thing here is to test this on a platform without mmap (e.g. switch or 3ds)

**Comment by AJenbo** [comment]
@MBeijer this is the PR that updates stormLib. It looks to be playing the intro video, but stops working after that. I seem to remember a similar issue at some point, where the simple workaround was to skip the splash with -n. Still we should try and solve it properly :)

**Comment by glebm** [comment]
The intro video issue appears for me even without this PR

**Comment by glebm** [comment]
Rebased

**Comment by glebm** [comment]
This should be good to merge

**Pull request merged**
