### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ColinPitrat**

### CODE REVIEW

**Comment by AJenbo** [comment]
pease target upstram with this typ of corrections https://github.com/diasurgical/devilution

**Comment by ColinPitrat** [comment]
Ack, will do.
Some of them are not upstream though, it seems there are differences between their Source directories. Is that expected?

**Comment by AJenbo** [comment]
Yes, DevilutionX applies some level of refactoring, most often to simplify code to make it easier to fix a particular bug or introduce a new feature. So in those cases, the corrections should still be applied directly in this repo. It does mean a bit of extra work, but it keeps things cleaner overall.

**Comment by ColinPitrat** [comment]
Thanks, I'll do a separate PR later for the devilutionX only parts.

**Pull request closed without merging**
