### PR TITLE
Compiling ASIO for Switch

### PR DESCRIPTION
**Pull request by StephenCWills**
Looks like I got it to compile. This crashes Ryujinx when trying to create an ASIO socket with a `NullReferenceException`. There's a pretty good chance that this is an error in Ryujinx itself and not DevilutionX, but I can't say for sure.

### CODE REVIEW

**Comment by AJenbo** [comment]
@rsn8887, @spitfire would you have time to test this on a real Switch to see if you can start or join a multiplayer game?

https://46674-143324737-gh.circle-artifacts.com/0/devilutionx.nro

**Comment by StephenCWills** [comment]
I've gone about as far as I can on this for now. Based on my testing with Ryujinx...

* Switch should be able to join games hosted on other platforms so long as it supports the TCP NoDelay option. I would appreciate if someone could test this on their Switch console to verify.
* Switch should not be able to host games at this time. There is a bug in libnx that prevents ASIO from setting up the listening socket. I've filed a bug report with libnx, tested a fix, and submitted a PR with said fix. We'll need to wait for them to merge the PR, update the package on devkitPro, and finally update the docker image.

So it's a waiting game at this point to get support for hosting games. I don't know how much demand there is for multiplayer on the Switch, but it might be worth merging this anyway once we verify that joining games is working. In theory, the issue with hosting will eventually just go away when the docker image is updated so there won't be a need for another PR.

That's just a thought. I'm also perfectly fine with waiting.

**Comment by AJenbo** [comment]
@StephenCWills could you link the dependent PR/Issues from devkitPro here so that they are easier to track?

**Comment by StephenCWills** [comment]
Issue: https://github.com/switchbrew/libnx/issues/557
Accepted PR: https://github.com/switchbrew/libnx/pull/560
Rejected PR: https://github.com/switchbrew/libnx/pull/558

I hadn't opened any PRs or issues with devkitPro just yet. I was waiting for libnx to bump their version, which it looks like they've done. https://github.com/switchbrew/libnx/commit/bee27ba6076962975128697e8a458101834df121

And devkitPro has updated the pacman package as well. https://github.com/devkitPro/pacman-packages/commit/6b964221cb6c2f7cd9373a42ead2df3ebd0b8076

Perhaps they don't need to explicitly change anything in the docker image. I just pulled the latest image, and it already has the latest libnx version. All we should need to do is rerun the CI build for Switch. I've kicked off that process.

**Comment by StephenCWills** [comment]
I just tested this in Ryujinx, and I was able to host a game.
https://47830-143324737-gh.circle-artifacts.com/0/devilutionx.nro

All we are waiting on now is for this to be tested on the Switch console.

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Based on the feedback and testing done so fare I'm happy to merge this as is and have the final real console test at a later point.

**Comment by StephenCWills** [comment]
That's fine. The only reason I'm hesitant is because Ryujinx doesn't support TCP NoDelay so I wasn't sure if the Switch console supported it or not. That said, I do find it really unlikely that it wouldn't be supported, and we can always fix it later if necessary. I'll promote it from a draft PR, and you can merge if you like.

**Comment by spitfire** [comment]
Is there a build I can try (on the real console)?

**Comment by StephenCWills** [comment]
> Is there a build I can try (on the real console)?

This has been merged into master so you can try the latest test build.
https://47874-143324737-gh.circle-artifacts.com/0/devilutionx.nro

**Comment by spitfire** [comment]
Doesn't crash now, but it's saying unable to connect, whether I host it on Windows (I've let it through the firewall) or Switch.

**Pull request merged**
