### PR TITLE
Work around MSVC+CMake+LTO bug

### PR DESCRIPTION
**Pull request by glebm**
Disables tests by default in MSVC LTO configurations. Refs #3778

### CODE REVIEW

**Comment by ephphatha** [comment]
On my system MSVC isn't set until after the project call, using that variable this early doesn't get picked and tests are built no matter what config is chosen. I can't find documentation calling out whether this is expected behaviour...

Also release builds that include zerotier are broken due to a gcc flag being passed in to MSVC in libzt:
https://github.com/diasurgical/libzt/blob/a9974991b031fd8f84c4bcfd93f129b3938ed8c8/CMakeLists.txt#L286-L287

`-w` gets translated to `/w` to supress all warnings, but the `-wno-everything` flag is treated as `/W<int>` which fails to parse.

**Comment by StephenCWills** [comment]
> Also release builds that include zerotier are broken due to a gcc flag being passed in to MSVC in libzt: https://github.com/diasurgical/libzt/blob/a9974991b031fd8f84c4bcfd93f129b3938ed8c8/CMakeLists.txt#L286-L287
> 
> `-w` gets translated to `/w` to supress all warnings, but the `-wno-everything` flag is treated as `/W<int>` which fails to parse.

😩 I thought that AppVeyor would catch something like that, but it looks like it's using `RelWithDebInfo`.

**Comment by glebm** [comment]
Pushed a new fix, tested in VS2022, PTAL.

**Review by ephphatha — APPROVED** [review]
Looks good to me, release builds succeed and don't build tests.

**Pull request merged**
