### PR TITLE
3rdParty: Bump versions of libmpq and libsmacker dec

### PR DESCRIPTION
**Pull request by glebm**
These are the only new commits:

https://github.com/diasurgical/libmpq/commit/0f10bd1600f406b13932bf5351ba713361262184
https://github.com/diasurgical/libsmackerdec/commit/792527435722151aff1a5b11f0862b957563d10b

### CODE REVIEW

**Review by ephphatha — APPROVED** [review]

**Comment by AJenbo** [comment]
@glebm does the changes to libmpq solve any specific issue?

**Comment by glebm** [comment]
Maybe, @StephenCWills will check this at some point

**Comment by StephenCWills** [comment]
The libmpq change fixes `pl.mpq` on Windows x64. To be thorough, I also tested various release builds across Windows, Linux, and 3DS and it works fine. I believe the Windows x64 issue is likely the same as the Vita crash reported in https://github.com/diasurgical/devilutionX/issues/3350#issuecomment-980720995 so it's likely fixed as well.

**Comment by AJenbo** [comment]
That's great to hear sounds like 2/3 of 1.4.0 is already done 😄

**Pull request merged**
