### PR TITLE
CMake: Fix SimpleIni on vcpkg

### PR DESCRIPTION
**Pull request by glebm**
/cc @tsunamistate

### CODE REVIEW

**Comment by tsunamistate** [comment]
@glebm first time configuration on empty cache results in this error:
```
1> [CMake] -- Found simpleini
1> [CMake] -- 📚 simpleini: dynamic system library
1> [CMake] -- Found simpleini: D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/include (found suitable version "4.19", minimum required is "4.19") 
1> [CMake] CMake Error at D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:613 (_add_library):
1> [CMake]   _add_library cannot create target "simpleini" because another target with
1> [CMake]   the same name already exists.  The existing target is an interface library
1> [CMake]   created in source directory "D:/src/devilutionX".  See documentation for
1> [CMake]   policy CMP0002 for more details.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMake/finders/Findsimpleini.cmake:31 (add_library)
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:181 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
```
but after regenerating cache, CMake does find simpleini from vcpkg:
```
1> [CMake] -- 📚 simpleini: dynamic system library
1> [CMake] -- Found simpleini: D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/include (found suitable version "4.19", minimum required is "4.19") 
```

**Comment by tsunamistate** [comment]
@glebm with https://github.com/diasurgical/devilutionX/commit/63e3415ac7f3179126841c0bbeab209fb0947447 different error this time
```
1> [CMake] CMake Error at D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:613 (_add_library):
1> [CMake]   _add_library called with IMPORTED argument but no library type.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMake/finders/Findsimpleini.cmake:31 (add_library)
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:171 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
1> [CMake] CMake Error at CMake/finders/Findsimpleini.cmake:32 (set_target_properties):
1> [CMake]   set_target_properties called with illegal arguments, maybe missing a
1> [CMake]   PROPERTIES specifier?
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:171 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
1> [CMake] CMake Error at CMake/finders/Findsimpleini.cmake:35 (target_include_directories):
1> [CMake]   Cannot specify include directories for target "simpleini" which is not
1> [CMake]   built by this project.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:171 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
1> [CMake] -- Found simpleini
1> [CMake] -- 📚 simpleini: dynamic system library
1> [CMake] -- Found simpleini: D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/include (found suitable version "4.19", minimum required is "4.19") 
1> [CMake] CMake Error at D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:613 (_add_library):
1> [CMake]   _add_library called with IMPORTED argument but no library type.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMake/finders/Findsimpleini.cmake:31 (add_library)
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:181 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
1> [CMake] CMake Error at CMake/finders/Findsimpleini.cmake:32 (set_target_properties):
1> [CMake]   set_target_properties called with illegal arguments, maybe missing a
1> [CMake]   PROPERTIES specifier?
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:181 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
1> [CMake] CMake Error at CMake/finders/Findsimpleini.cmake:35 (target_include_directories):
1> [CMake]   Cannot specify include directories for target "simpleini" which is not
1> [CMake]   built by this project.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
1> [CMake]   CMake/Dependencies.cmake:181 (find_package)
1> [CMake]   CMakeLists.txt:252 (include)
```

**Comment by glebm** [comment]
Oops, forgot to exclude the old calls, can you please try again?

**Comment by tsunamistate** [comment]
Nope, still the same error

**Comment by tsunamistate** [comment]
OK, this is progress
At c2c594d20eb147a85acb4605bbef40d40a06bb9a CMake finds simpleini, and even finishes configuring, but then, on generating step, it spams the console with error `IMPORTED_LOCATION not set for imported target` like 50 times

```
1> [CMake] -- Found simpleini
1> [CMake] -- 📚 simpleini: dynamic system library
1> [CMake] -- Found simpleini: D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/include (found suitable version "4.19", minimum required is "4.19") 
1> [CMake] -- 📚 googletest: dynamic system library
1> [CMake] -- Found GTest: D:/src/devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/share/gtest/GTestConfig.cmake (found version "1.11.0")  
1> [CMake] -- Found Gettext: D:/src/vcpkg/installed/x64-windows/tools/gettext/bin/msgmerge.exe (found version "0.21") 
1> [CMake] -- Configuring done
1> [CMake] CMake Error in D:\src\devilutionX\CMakeLists.txt:
1> [CMake]   IMPORTED_LOCATION not set for imported target "simpleini::simpleini"
1> [CMake]   configuration "Debug".
...
Repeat 50 or so times
...
1> [CMake] -- Generating done
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by glebm** [comment]
Ah, I see, didn't realize IMPORTED_LOCATION was mandatory. Looking into it.

**Comment by tsunamistate** [comment]
Alright, 13556c18af4925af154cf1d41006e705c5a48e37 has it in the bag!
Configuration and generation with system simpleini complete, compiled just fine

**Comment by glebm** [comment]
Yay! :tada:

**Review by obligaron — APPROVED** [review]
I'm no CMake expert but I also verified that simpleini is found with vcpkg on windows with visual studio 2022.

> [CMake] -- 📚 simpleini: dynamic system library
> [CMake] -- Found simpleini: devilutionX/build/x64-Debug/vcpkg_installed/x64-windows/include (found suitable version "4.19", minimum required is "4.19")

**Pull request merged**
