### PR TITLE
Create fibo.py

### PR DESCRIPTION
**Pull request by Shruti30Goel**

### CODE REVIEW

**Comment by StephenCWills** [comment]
Please stop

**Comment by qndel** [comment]
@AJenbo can u ban him?

**Comment by AJenbo** [comment]
You have to be pretty crappy to be 1/8 people ever to be blocked from the org...

**Comment by AJenbo** [comment]
image

Guess they are desperately trying to get a t-shirt ...

**Comment by AJenbo** [comment]
Reported there content to Hacktoberfest as well, thanks for playing

**Pull request closed without merging**
