### PR TITLE
Fix MSVC build

### PR DESCRIPTION
**Pull request by BennyFranco**
I fixed the compilation with MSVC, but the executable builded with CL has some runtime crashes caused by code like:

```c++
short array[4];

for(int i = 0; i < sizeof(array); i++)
{
       array[i] = 0;
}
```

size of array is 8 not 4 and causes a runtime error, with ```gcc``` and ```clang``` can be ignored, I don't know if exist something similar for CL but I think which that is an insecure code, maybe can be changed for something like:

```c++
#define COUNT(x) sizeof(x)/sizeof(*x)

...

short array[4];

for(int i = 0; i < COUNT(array); i++)
{
       array[i] = 0;
}
```

### CODE REVIEW

**Comment by AJenbo** [comment]
Yeah it looks like this code was like that originally and that it would zero all bytes this way, probably we should create a ticket for fixing this in devilutionx.

Thanks for looking in to the msvc issue, much appreciated

**Comment by AJenbo** [comment]
Fixed a little bit of the counting: https://github.com/diasurgical/devilution/pull/1037

**Comment by AJenbo** [comment]
Figured out what was wrong with ThemeGoodIn https://github.com/diasurgical/devilution/pull/1049

Also going to try and upstream the headers:
https://github.com/diasurgical/devilution/pull/1048

**Comment by AJenbo** [comment]
Things have been solved upstream now, looks like things are already compiling. Is the remaining change to solve some warning?

**Comment by BennyFranco** [comment]
A building error, ``` strncasecmp ``` is undefined with MSVC

**Comment by AJenbo** [comment]
My bad I was looking at the wrong build log :D

**Pull request merged**
