### PR TITLE
🔨 ⚙️  CMake: Add DEFAULT_BLENDED_TRANSPARENCY option

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by AJenbo** [comment]
Do you see a meaningful difference in performance? I was considering completely removing the old transparency as I haven't see anyone complain about it. Even hardcore diablo players often do not notice it and rg300 doesn't seem to care one way or the other.

**Comment by glebm** [comment]
It seems to save 0.5 MiB RAM but maybe I'm imagining things?

**Comment by glebm** [comment]
The lookup table should only be 64 KiB; it's definitely variance or similar :|

**Comment by AJenbo** [comment]
> It seems to save 0.5 MiB RAM but maybe I'm imagining things / measuring wrong / variance?

Hmm didn't think of memory usage, but it should hopefully not use more then 64KiB

**Comment by glebm** [comment]
Oh wow but the loop iterates 256 x 256 x 256 = 16.7 million times at most

**Comment by glebm** [comment]
Nevermind then

**Pull request closed without merging**
