### PR TITLE
DiabloUI: Credits improvements

### PR DESCRIPTION
**Pull request by glebm**
1. Fix lines moving up and down on slower devices (was due to `GetAnimationFrame` rolling over).
2. Cache rendered text surfaces (in a ring buffer).
3. SDL_Delay(1) between event polls to reduce CPU usage (not sure if it actually does anything / is needed).
4. Move data to a separate compilation unit.

Refs #231

### CODE REVIEW

**Comment by glebm** [comment]
> I'm not sure the delay is needed as it waits for a full Fram each time it runs out of events

Do you know where this is documented? I couldn't find anything

**Comment by glebm** [comment]
`BlackPalette` is not called in the loop though

**Comment by glebm** [comment]
Most of the time is currently spent in the following code in `SetFadeLevel`:

```
		// Workaround for flickering mouse in caves https://github.com/diasurgical/devilutionX/issues/7
		SrcRect.left = 64;
		SrcRect.top = 160;
		SrcRect.right = BUFFER_WIDTH;
		SrcRect.bottom = BUFFER_HEIGHT; // menu isn't offset so make sure we copy all of it
		BltFast(0, 0, &SrcRect);
		RenderPresent();
```

**Comment by glebm** [comment]
Regardless, it's working (CPU usage is at ~15% for the credits screen for me on SDL2).

**Comment by AJenbo** [comment]
Sorry I might have gotten it mixed up with UiFadeIn(), only have a phone available today 😅

**Pull request merged**
