### PR TITLE
Remove the build directory from the repo

### PR DESCRIPTION
**Pull request by glebm**
There is no benefit to having it anymore.

The minimum CMake version we require supports the `cmake -S. -Bbuild` invocation which creates the directory. This is also the command we now use in the build instructions.

### CODE REVIEW

**Comment by tsunamistate** [comment]
I was worried that `build` folder will not be created using Visual Studio via File - Open - CMake (the method recommended in the docs).
However, folder `build/{arch}-{configuration}` (e.g. build/x64-Debug) is created automatically with fresh checkout of this PR.
Approved from Windows side 👍

**Review by StephenCWills — APPROVED** [review]

**Comment by AJenbo** [comment]
More special argument to remember i suppose :shrug:

**Comment by glebm** [comment]
Let go of the old ways! No need to `cd` anymore!

**Comment by StephenCWills** [comment]
There's no real reason to let go. You can still use `cd` if you `mkdir` first. IMO, the parameters are better for the automated scripts and the instructions.

**Comment by AJenbo** [comment]
True :)

**Pull request merged**
