### PR TITLE
  Fix ConsumeScroll

### LINKED ISSUE #5617: OOB access in ConsumeScroll()
### Operating System

Linux PowerPc

### DevilutionX version

https://github.com/diasurgical/devilutionX/commit/96c7b154be835bddcd80419163af2680a2944ec5

### Describe

```
[ RUN      ] InvTest.RemoveCurrentSpellScroll_inventory
/home/ajenbo/devilutionX/Source/inv.cpp:1947:35: runtime error: index -7 out of bounds for type 'Item [40]'
```

Source/inv.cpp:1947
```cpp
        int itemSlot = player.executedSpell.spellFrom;
        int itemIndex = 0;
        Item *item;
        if (itemSlot <= INVITEM_INV_LAST) {
                itemIndex = itemSlot - INVITEM_INV_FIRST;
                item = &player.InvList[itemIndex]; // <- 0 - 7
        } else {
                itemIndex = itemSlot - INVITEM_BELT_FIRST;
                item = &player.SpdList[itemIndex];
        }

```

### To Reproduce

run ./inv_test

### PR DESCRIPTION
**Pull request by glebm**
Fixes #5617

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by obligaron** [comment]
I don't think this is the correct approach cause spellFrom can be 0 if you cast a scroll from spell list. 🤔 But I need to check again.

**Comment by obligaron** [comment]
Check again: Using the spell list doesn't set `spellFrom`, so it can be 0.
That's why I would leave the unit tests as they are (or only change one of them) and would merge #5621.

**Comment by glebm** [comment]
I see. We should test all 3 cases, and set it to 0 explicitly in the third case.

**Comment by glebm** [comment]
I've added tests and incorporated the fixes from #5621

**Review by AJenbo — APPROVED** [review]
LGTM

**Pull request merged**
