### PR TITLE
Update AppVeyor CI to VS 2019

### PR DESCRIPTION
**Pull request by glebm**
VS 2019 should fix %ju/d printf format specifier support which we use in mpqapi logging

### CODE REVIEW

**Comment by AJenbo** [comment]
I would prefer that we keep things compatible with 2019 for modders, it's fine if it degrades error messages etc, even for all VS builds. They don't have ASAN either so they muse be used to using debuggeres :P

**Comment by glebm** [comment]
Modders should just update to VS 2019 already IMO.
There isn't a good reason to use 2017 considering bugs, performance, etc.

**Comment by glebm** [comment]
I'll make the mpqapi logging code compatible with VS 2017 though, because I think that might be causing the crash. And Windows users seem to often have a hard time setting up their dev environment...

**Comment by AJenbo** [comment]
Yeah, if we drop VS 2017 support we need to also have CMake warn them that it's not supported, so might even be more work then making it compatible :D

**Pull request closed without merging**
