### PR TITLE
Freebsd

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by malavon** [comment]
Everything still compiles and it runs. 

I updated the patch in the port. Also, the only other change that I have in the FreeBSD port is this at the bottom of CMakeLists.txt:
`install(TARGETS devilutionx DESTINATION ${BINDIR})`

If you're interested in an install phase on Unix-like OS's, that's probably all that's needed.

One more thing: I tested everything on amd64, didn't test i386 but I'm pretty sure it'll work anyway.

**Comment by AJenbo** [comment]
Thanks for testing.

`${BINDIR}` does not appear to be defined for Ubuntu so this probably isn't the way to go for adding a universal install path.

**Comment by malavon** [comment]
Yeah, I don't know much about installing using CMake at the moment, I just copied that from another port :)
If I ever get a bit more knowledgeable about CMake I'll create a PR for it.

**Comment by AJenbo** [comment]
I'll merge this as soon as I have tested it on my machine so that I can also update the readme.

**Comment by AJenbo** [comment]
Can confirm the game fully works on 32bit FreeBSD using GCC

**Pull request merged**
