### PR TITLE
Improve StartWalkX functions naming

### PR DESCRIPTION
**Pull request by canassa**
Renames `StartWalk`, `StartWalk2` and `StartWalk3` to more meaningful names

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Hm could you align the names with the functions for the player?

**Comment by canassa** [comment]
> Hm could you align the names with the functions for the player?

Sure!

**Comment by canassa** [comment]
@AJenbo The player seems to be a single `StartWalk` function, is that what you mean?

**Comment by AJenbo** [comment]
It in turn calls `WalkUpwards`, `WalkSides`, and `WalkDownwards`.
For monsters you called the equivalent `StartWalkNorthwards`, `StartWalkSideways`, `StartWalkSouthwards`.

**Pull request merged**
