### PR TITLE
fancy stairs up/down

### PR DESCRIPTION
**Pull request by qndel**
image

all that's left is mapping all stairs up for catas/caves/hell/crypt/hive 🎉 🤮 
If anyone finds a way that doesn't require mapping all stairs manually, let me know :D

### CODE REVIEW

**Comment by julealgon** [comment]
While it's nice to differentiate the stairs, I think this proposal does not make clear at all which one is up or down... the difference is too arbitrary imho.

Also, can you link with the issue?
- https://github.com/diasurgical/devilutionX/issues/1362

**Comment by qndel** [comment]
> While it's nice to differentiate the stairs, I think this proposal does not make clear at all which one is up or down... the difference is too arbitrary imho.
> 
> Also, can you link with the issue?
> 
> * #1362

didn't know there was an issue : p the way with which stairs up/down are marked can be changed, the biggest problem is detecting which stairs are up/down

**Comment by julealgon** [comment]
> didn't know there was an issue : p the way with which stairs up/down are marked can be changed, the biggest problem is detecting which stairs are up/down

Don't get me wrong: this is a very clear improvement IMHO and I'd be fine merging it. However, I believe we should think about a more intuitive graphic or something like that to better show which one is which.

**Comment by malvarenga123** [comment]
Can you write texts on the map? If yes, you could just write use the Diablo 2 solution of writing the level name next to the stairs.

**Comment by AJenbo** [comment]
@malvarenga123 do you have a picture of that.

**Comment by malvarenga123** [comment]
Here @AJenbo
image

**Comment by ChaosMarc** [comment]
Actually this is a maphack feature. D2 doesn't show the area names on the map. Nevertheless I like the proposal

**Comment by FitzRoyX** [comment]
I think the use of another color should be reserved for the shrine that reveals the map before you've explored it.

Why not just briefly show a number above the staircase that is in the same style and color as the stairs? By briefly I mean it shows for 1 second upon enabling the map. So if you want to see where stairs go, just toggle your map off and on.

**Comment by julealgon** [comment]
> Why not just briefly show a number above the staircase that is in the same style and color as the stairs? By briefly I mean it shows for 1 second upon enabling the map. So if you want to see where stairs go, just toggle your map off and on.

That seems incredibly unintuitive to me @FitzRoyX .

**Comment by FitzRoyX** [comment]
bubstairs4

**Comment by julealgon** [comment]
If that's displayed always, maybe I'd entertain the idea @FitzRoyX . Also have to think how to represent "non-numbered floors", like chamber of bone and town.

**Comment by FitzRoyX** [comment]
The Chamber of Bone is surrounded by pillars, and it also wouldn't have a number on it. Are we just trying to differentiate the stairs or label everything?

The font I used is Segoe UI 12pt italic. To my eye, it was the best looking of my collection of fonts. I don't think it's a font you can legally bundle, however, so I'll try to find something similar if we go with this.

**Comment by julealgon** [comment]
> The Chamber of Bone is surrounded by pillars, and it also wouldn't have a number on it. Are we just trying to differentiate the stairs or label everything?

I think we should support some indication for every stair, including chamber of bone and up to town. Otherwise we won't provide the necessary information for the player to know. Keep in mind that, even though chamber of bone has a unique graphic, this is not really needed per se (a mod could put the stairs wherever they want and they could look like normal stairs on the map.

Also, this applies to poisoned water supply (dark passage) and Leoric too.

**Comment by galaxyhaxz** [comment]
You'd have to rip the font from D2 as you need a small font for things like this. Here is what it'd look like.

Untitled

**Comment by yuripourre** [comment]
I have a suggestion, since stairs are represented by 3 lines, why not change the color of the upper line for **up** and the color of the last line for **down**? for other stairs/portals/quests, just keep them as-is.

**Comment by qndel** [comment]
> I have a suggestion, since stairs are represented by 3 lines, why not change the color of the upper line for **up** and the color of the last line for **down**? for other stairs/portals/quests, just keep them as-is.

uh look at my screenshot? that's what I did? :(

**Comment by julealgon** [comment]
What about drawing new elements besides lines into the middle of the stair square?

I think we should consider the possibility of
- Not using text
- Not using the existing graphic

Maybe just a `^` and `v` symbol in the middle of the square would be enough for "up" and "down" for example. That would be a start (but wouldn't cover differences in other entrances like "to town" and others).

**Comment by yuripourre** [comment]
@qndel Oops, sorry about it. I am color blind, didn't notice the red line on first stair. :facepalm:

**Comment by AJenbo** [comment]
> You'd have to rip the font from D2 as you need a small font for things like this

Maybe somewhere in the vast ocean that is the internet, there is a usable small font that isn't copyright encumbered :shrug:

**Comment by galaxyhaxz** [comment]
> I am color blind, didn't notice the red line on first stair.

@yuripourre  Ah, as a color blind person, is there anything you find that makes diablo difficult to play? Would be nice to know what can be done to make the game more accessible to people like you.

> Maybe somewhere in the vast ocean that is the internet, there is a usable small font that isn't copyright encumbered

Of course, I'm just too lazy to find one :P You can easily find a variety of 8x8 bitmap fonts everywhere which could serve this purpose.

**Comment by FitzRoyX** [comment]
> Actually this is a maphack feature. D2 doesn't show the area names on the map. Nevertheless I like the proposal

It's definitely a love or hate thing. The automap is something of a necessary evil as it is, obscuring gameplay a bit for the sake of better navigation. Text is more eye-catching than linework, and we already use them for ground item highlighting.

If we go with qndels idea, I suggest a pinker red as regular red is not a very standout color against dark tilesets.

bubstairs6ff

**Comment by julealgon** [comment]
> If we go with qndels idea, I suggest a pinker red as regular red is not a very standout color against dark tilesets.
> 
> bubstairs6ff

See... I just can't see any _semantic_ behind the red lines. Sure, you can clearly differentiate the stairs, but how do you know which one is up and which one is down? The line alone adds no way for you to associate it with "up" or "down" to me to the point where it would even be confusing and cause people to move to the incorrect one at times.

We need something less "abstract" to represent it.

**Comment by AJenbo** [comment]
> how do you know which one is up and which one is down?

You lean it the first time you find a couple of stairs?

**Comment by FitzRoyX** [comment]
Well I can't think of anything else besides this
bubstairs6jj
bubstairs6j

**Comment by AJenbo** [comment]
> > bubstairs6ff

Unfortunately, I don't think this works with how the cathedral is rendered since they are part of the wall. Probably the caves have a similar issue. The original image for the limitation.

This is my suggestions:
image

**Comment by julealgon** [comment]
@AJenbo 
> > how do you know which one is up and which one is down?
> 
> You lean it the first time you find a couple of stairs?

And then quickly forget it again since the lines themselves have no inherent semantic to them, so you cannot instinctively associate one with up and another with down.

It's not like associating colors with "go" and "stop", where everybody knows _green_ is more used for "go" and _red_ is more used for "stop" so the association is more obvious. 

There is nothing obvious to me in the red line's positions.

**Comment by qndel** [comment]
> @AJenbo
> 
> > > how do you know which one is up and which one is down?
> > 
> > 
> > You lean it the first time you find a couple of stairs?
> 
> And then quickly forget it again since the lines themselves have no inherent semantic to them, so you cannot instinctively associate one with up and another with down.
> 
> It's not like associating colors with "go" and "stop", where everybody knows _green_ is more used for "go" and _red_ is more used for "stop" so the association is more obvious.
> 
> There is nothing obvious to me in the red line's positions.

then how did you remember lines mean stairs? 🤪

**Comment by AJenbo** [comment]
@julealgon how do you feel about my suggestion for the stair graphics?

**Comment by NikoVP** [comment]
Or you color code them yellow - up, red - down, some other color special level, blue - town or something in that line of thought

**Comment by qndel** [comment]
I marked quick entrances too :(

**Comment by julealgon** [comment]
> Well I can't think of anything else besides this
> bubstairs6jj

I like this one @FitzRoyX 

---

> This is my suggestions:
> image

This doesn't help to me. I can't associate "up" and "down" with arrows going to the right or to the left. It is too arbitrary IMHO.

---

@qndel 
> then how did you remember lines mean stairs? 🤪

Well there is nothing to compare to... the problem is the comparison, no the actual representation. If you only have 1 thing to represent, then you can use whatever you want and there is just one association to make. Walls are obvious, doors are obvious, "oh this must be the stairs then".

It is a whole different thing when you now have to differentiate and be able to tell 2 variations of something apart.

**Comment by FitzRoyX** [comment]
I kinda like it, clever but a bit chaotic looking at first.

Would my 2nd image actually be possible? Could we just replace the lines with a simple up and down arrow?

**Comment by qndel** [comment]
still better than having 0 info, even if you don't remember (duh), you have the same info you had before, but smart pebbles will be able to figure out which is quick entrace/stairs down/stairs up

**Comment by qndel** [comment]
image

**Comment by julealgon** [comment]
> still better than having 0 info

That's actually debatable, since if you confuse the symbols, you could actually be mislead to the _wrong_ stairs.

**Comment by qndel** [comment]
> > still better than having 0 info
> 
> That's actually debatable, since if you confuse the symbols, you could actually be mislead to the _wrong_ stairs.

then you will remember better next time

**Comment by malvarenga123** [comment]
Text would be completley unambiguous and also solves the problem of entrances that don't go up or down.
Of all alternatives, @galaxyhaxz's one looks the best, IMO.
The font's copyright is secondary, because other fonts can be used as said before.

**Comment by AJenbo** [comment]
> This doesn't help to me. I can't associate "up" and "down" with arrows going to the right or to the left. It is too arbitrary IMHO.

.. you must behave your head at a funny tilt. It's up/down at a 45° incline.

Here is an actual symbol for stairs up as done by the US department of transportation:
image

Straight up/down is usually denoting an elevator.

**Comment by julealgon** [comment]
> .. you must have your head at a funny tilt. It's up/down at a 45° incline.

Fair enough... fair enough 😅

**Comment by yuripourre** [comment]
> @yuripourre Ah, as a color blind person, is there anything you find that makes diablo difficult to play? Would be nice to know what can be done to make the game more accessible to people like you.
> 
@galaxyhaxz I am not total color blind but I cannot see all the colors.
The hardest part of playing Diablo is definitely searching for items on the ground. I always play with sound so I can hear when an item drops, especially when playing as rogue. Item highlight solves this problem.

A bunch of times I used "elixir of magic" expecting a "full health potion".

I will try to remember other situations, I am sure there are more.

**Comment by qndel** [comment]
> > @yuripourre Ah, as a color blind person, is there anything you find that makes diablo difficult to play? Would be nice to know what can be done to make the game more accessible to people like you.
> 
> @galaxyhaxz I am not total color blind but I cannot see all the colors.
> The hardest part of playing Diablo is definitely searching for items on the ground. I always play with sound so I can hear when an item drops, especially when playing as rogue. Item highlight solves this problem.
> 
> A bunch of times I used "elixir of magic" expecting a "full health potion".
> 
> I will try to remember other situations, I am sure there are more.

highlighting items will handle that ;p

**Pull request closed without merging**
