### PR TITLE
Introduce std::thread-like class; get rid of utils/thread.{h,cpp}

### PR DESCRIPTION
**Pull request by vlolteanu**

### CODE REVIEW

**Comment by AJenbo** [comment]
@vlolteanu could you share some of the thinking behind this change.

@StephenCWills could you test this on 3DS since it's a bit sensitive to having this changed?

**Comment by vlolteanu** [comment]
This is a straightforward imitation of std::thread, albeit using SDL_Thread underneath. The basics apply: it can't be copied, only moved; destroying without joining and joining from the same thread are considered errors and terminate the program.

The old stuff was an imitation of the Windows API.

Functionally, I didn't change anything.

**Review by AJenbo — APPROVED** [review]

**Comment by StephenCWills** [comment]
> could you test this on 3DS since it's a bit sensitive to having this changed?

It seems the latest master crashes at startup on 3DS so my test was inconclusive.

**Comment by AJenbo** [comment]
Ok, thanks for testing. in that case I think we won't have it block this PR. Hopefully it won't cause any issues with getting 3DS back up and running.

**Comment by StephenCWills** [comment]
I was able to fix the crash. I ran the test again, and there's no problem.

**Pull request merged**
