### PR TITLE
fix shrine rng

### PR DESCRIPTION
**Pull request by qndel**
Resolves https://github.com/diasurgical/devilutionX/issues/1874

### CODE REVIEW

**Comment by Apocalypse612** [comment]
Just tested this, and my chain lightning is now leveling from Enchanted Shrines. Glorious!

**Comment by StephenCWills** [comment]
This change will cause dungeon generation to diverge between mid2 and mid3.

Before:
image

After:
image

**Comment by qndel** [comment]
```cpp
				[[maybe_unused]] uint32_t mid2Seed = GetLCGEngineState();
				IncProgress();
				InitMonsters();
				InitItems();
				if (currlevel < 17)
					CreateThemeRooms();
				IncProgress();
				[[maybe_unused]] uint32_t mid3Seed = GetLCGEngineState();
				InitMissiles();
				InitCorpses();
```
Shrines affect CreateThemeRooms so only theme rooms would be affected
Do you think I should move assigning seed to them after theme rooms finish generating?

**Comment by StephenCWills** [comment]
Hmm.. Yeah, I think it would be nice if we could rely on the seed to generate the same theme rooms in vanilla in case we need to test something specific. Assigning the seed at the end would certainly solve that problem.

**Review by StephenCWills — APPROVED** [review]

**Comment by ikonomov** [comment]
This is absolutely fantastic.

**Review by AJenbo — APPROVED** [review]
Rolled back to the original proposal as it turns out not to be an issue :+1:

**Pull request merged**
