### PR TITLE
Automap: Don't close automap when pressing spacebar with other windows open

### PR DESCRIPTION
**Pull request by tetektoza**
Resolves: https://github.com/diasurgical/devilutionX/issues/2622

Currently if we open a lot of windows and have automap enabled, and we press space - all of the windows along with automap get closed. This patch removes that, and allows to close automap with spacebar, but only if every window is closed.

### CODE REVIEW

**Comment by tetektoza** [comment]
Measuring time might be an overkill, and maybe it would be better to use something else than std::chrono, or move this newly added function's logic inside the lambda of AddAction(), but let me know if you see it differently.

**Comment by julealgon** [comment]
Wouldn't it be significantly more straightforward to check whether _only_ the automap is opened, or if there are other windows opened? In the former, you'd close the automap. In the latter, only the other windows would be closed.

No need for timers, or keeping track of previous actions, etc.

**Comment by tetektoza** [comment]
@julealgon great idea, thanks, missed those flags tbh. Changed so now only if the windows are closed automap can be closed too. I may have missed some flag and I didn't see a flag for GameMenu, so I've added it. Let me know if there's something missing.

**Review by AJenbo — APPROVED** [review]
LGTM

**Pull request merged**
