### PR TITLE
Use the largest available area when placing theme rooms

### PR DESCRIPTION
**Pull request by ephphatha**
Splitting this into a separate PR from #4778 as this does change the boundaries of theme rooms. It could potentially put someone in a wall if they load a save made from an old version (though they can walk off it), and could lead to bodies/objects/items/monsters floating in the air/inside walls.

For example:
cat_7
cat_7_fixed
cat_8
cat_8_fixed

But since it's one of the last phases of dungeon generation, it's relatively minor :D. Also got rid of the buggy bounds check since this changes behaviour anyway.

### CODE REVIEW

**Comment by AJenbo** [comment]
Yikes, I'm not to happy with the walls being moved around :/

**Comment by julealgon** [comment]
It's not exactly clear to me why this change is needed: at first glance, it seems like an arbitrary (and ultimately subjective) behavior change. Can someone elaborate? Are we considering vanilla behavior "incorrect" for some reason?

**Comment by ephphatha** [comment]
I'll preface this by saying that I'm not 100% sure what the true intent of the original code actually was, it was either attempting to find the largest total area or possibly the squarest region that avoids corners? It ends up with some odd behaviour with certain layouts.

For a caves level (minSize is 5) the vanilla logic chooses the following areas:
```
++++++++-#
++++++++--
++++++++--
++++++++--
++++++++--
++++++++-# Same width as one of the first 5 rows, so doesn't trigger the early break/return
--------## This row does trigger the early return, and because
--------## the width is not smaller than minSize also defines the boundary
-------###
-------###
```
```
+++++++++-
+++++++++-
+++++++++-
+++++++++-
+++++++++-
---------# Now it's the first corner encountered and the row is still not less than minSize, so this defines the area
--------## End result is a wider/shorter area despite the only difference being no wall tiles in the first 5 rows.
--------##
-------###
-------###
```
```
++++++++++
++++++++++
++++++++++
++++++++++
++++++++++
----####-# This time the row is less than minSize, so we use the full width instead?
--------##
--------##
-------###
-------###
```
```
+++++++###
+++++++---
+++++++---
+++++++---
+++++++---
+++++++--#
+++++++-##
+++++++-##
+++++++### Not detected as a corner since it's the same width as one of the first
+++++++### 5 rows, so the region continues to the full height?
```

Is it intentional that case 2 gives a smaller total area than case 3? Is it more appropriate to use an 8x6 area for case 1 instead of a 7x10 area like what ends up getting chosen for case 4?

I don't wanna call this a fix because it's not clear what the actual "correct" behaviour is for this code. It's one possible interpretation, another could be to pick out corners better. This PR is more of an experiment following a comment in discord about #4778, that PR keeps the original logic and hopefully just makes the code easier to understand.

**Comment by ephphatha** [comment]
Gonna close this one since it does change the placement of wall tiles, keeping the original behaviour is simpler anyway

**Pull request closed without merging**
