### PR TITLE
Update SDL_audiolib from upstream 

### PR DESCRIPTION
**Pull request by glebm**
Includes updates of drwav and drmp3 to the latest versions

### CODE REVIEW

**Comment by AJenbo** [comment]
Are there any specific fixes or improvements that affect us here? I see a bit of fixing of warnings and compiler support, but nothing that jumps out at me.

**Comment by glebm** [comment]
My motivation was this entry in the mp3 [changelog](https://github.com/mackron/dr_libs/blob/15f37e3ab01654c1a3bc98cff2a9ca64e8296fa9/dr_mp3.h#L4474-L4475):

```
v0.6.31 - 2021-08-22
  - Fix a bug when loading from memory.
```

**Comment by AJenbo** [comment]
Yeah saw that as well, but assumed we might not be affected since the audio is playing :)

**Comment by AJenbo** [comment]
I'm a bit hesitant to upgrade such a critical component this close to a release. Do you have an option to test it on Windows a bit?

**Comment by glebm** [comment]
As I understand it may be skipping a frame (?) but that would be very difficult to notice

@AJenbo I'll test on Windows!

**Review by AJenbo — APPROVED** [review]

**Comment by glebm** [comment]
Tested on Windows and Linux with English, Polish, and Russian

**Pull request merged**
