### PR TITLE
Distributed skipped frames in hit recovery animations.

### LINKED ISSUE #984: Smoother block animations
Currently block animations frame skipping is unevenliy distributed leading to some bad jitter during playback. This is controlled from PM_DoGotHit and the resulting behavior is as follows (note in helfire there is no zen combination):
```
-= Diablo =-

Warrior  Normal  : 1, 2, 3, 4, 5, 6
Warrior  bal     : 1, 2, 3, -, 5, 6
Warrior  sta     : 1, 2, 3, -, 5, -
Warrior  har     : 1, -, 3, -, 5, -
Warrior  bal+sta : 1, 2, 3, -, -, 6
Warrior  bal+har : 1, -, 3, -, -, 6
Warrior  sta+har : 1, -, 3, -, -, 6
Warrior  zen     : 1, -, 3, -, -, -

Rogue    Normal  : 1, 2, 3, 4, 5, 6, 7
Rogue    bal     : 1, 2, 3, -, 5, 6, 7
Rogue    sta     : 1, 2, 3, -, 5, -, 7
Rogue    har     : 1, -, 3, -, 5, -, 7
Rogue    bal+sta : 1, 2, 3, -, -, 6, 7
Rogue    bal+har : 1, -, 3, -, -, 6, 7
Rogue    sta+har : 1, -, 3, -, -, 6, 7
Rogue    zen     : 1, -, 3, -, -, -, 7

Sorceror Normal  : 1, 2, 3, 4, 5, 6, 7, 8
Sorceror bal     : 1, 2, 3, -, 5, 6, 7, 8
Sorceror sta     : 1, 2, 3, -, 5, -, 7, 8
Sorceror har     : 1, -, 3, -, 5, -, 7, 8
Sorceror bal+sta : 1, 2, 3, -, -, 6, 7, 8
Sorceror bal+har : 1, -, 3, -, -, 6, 7, 8
Sorceror sta+har : 1, -, 3, -, -, 6, 7, 8
Sorceror zen     : 1, -, 3, -, -, -, 7, 8
```

A better pattern would be the following:
```
Warrior  Normal  : 1, 2, 3, 4, 5, 6
Warrior  bal     : 1, 2, 3, -, 5, 6
Warrior  sta     : 1, -, 3, 4, -, 6
Warrior  har     : 1, -, 3, -, 5, -
Warrior  bal+sta : 1, -, 3, 4, -, 6
Warrior  bal+har : 1, -, 3, -, 5, -
Warrior  sta+har : 1, -, 3, -, 5, -
Warrior  zen     : -, 2, -, -, 5, -

Rogue    Normal  : 1, 2, 3, 4, 5, 6, 7
Rogue    bal     : 1, 2, 3, -, 5, 6, 7
Rogue    sta     : 1, -, 3, 4, 5, -, 7
Rogue    har     : 1, -, 3, -, 5, -, 7
Rogue    bal+sta : 1, -, 3, 4, 5, -, 7
Rogue    bal+har : 1, -, 3, -, 5, -, 7
Rogue    sta+har : 1, -, 3, -, 5, -, 7
Rogue    zen     : 1, -, -, 3, -, -, 7

Sorceror Normal  : 1, 2, 3, 4, 5, 6, 7, 8
Sorceror bal     : 1, 2, 3, -, 5, 6, 7, 8
Sorceror sta     : 1, 2, -, 4, 5, -, 7, 8
Sorceror har     : 1, -, 3, -, 5, -, 7, 8
Sorceror bal+sta : 1, 2, -, 4, 5, -, 7, 8
Sorceror bal+har : 1, -, 3, 4, -, 6, 7, -
Sorceror sta+har : 1, -, 3, 4, -, 6, 7, -
Sorceror zen     : 1, -, 3, -, 5, -, 7, -
```

### PR DESCRIPTION
**Pull request by StephenCWills**
Smooths hit recovery animations by distributing frame skips more evenly.

As a note for reviewers, I added a check to disable the zen combination for Hellfire. This is more consistent with the original behavior in Hellfire, but not with prior versions of devilutionX.

This logic was tested using the output from log messages, but I did not test Hellfire. Feel free to use the attached save files for testing.
[warrior.zip](https://github.com/diasurgical/devilutionX/files/6275863/warrior.zip)
[rogue.zip](https://github.com/diasurgical/devilutionX/files/6275861/rogue.zip)
[sorcerer.zip](https://github.com/diasurgical/devilutionX/files/6275862/sorcerer.zip)

This resolves #984

### CODE REVIEW

**Comment by StephenCWills** [comment]
Is testflow the check that runs unit tests?

**Comment by AJenbo** [comment]
Yes testflow runns all build tests asn the unit tests.

**Comment by StephenCWills** [comment]
Okay, I expected that to fail. I still need to update player_test.cpp. I wanted to see what it ends up saying, but it's taking quite a while.

**Comment by AJenbo** [comment]
It's not running on your fork, don't know why, try login into circleci and see what's up.

**Comment by StephenCWills** [comment]
Thanks, that helped. I was able to get it working.

**Comment by AJenbo** [comment]
nice :)

**Comment by StephenCWills** [comment]
There's still something wrong with the status check at the end of the workflow. After looking into it deeply, I found this suggestion that I shouldn't be following my fork, but rather the source project.
https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

Actually, I don't even appear to have the option of following the source project since I'm not an owner. Rather, I think I'm not supposed to be using CircleCI at all for this project. The source project should already be triggering jobs against new pull requests, and I'm not sure why it didn't work the first time. I'm not sure there's anything I can do to fix it for this PR or #1420. However, it does look like all the tests are passing.

**Comment by AJenbo** [comment]
odd, i think you are missing the code coverage check also, i dont see this issue with other prs. no worries now that things are passing its good enough

**Comment by StephenCWills** [comment]
Looks like it fixed itself after the merge commit.

**Comment by julealgon** [comment]
Would recommend rebasing instead of merge committing from master to update the PR branch.

**Comment by AJenbo** [comment]
Unless you are happy with your change getting squashed in to a single commit.

**Comment by AJenbo** [comment]
Going to close this as I think the underlying issue is better solved by https://github.com/diasurgical/devilutionX/pull/1468

Still i think your research when doing this led to some nice finds and helped to improve the implementation of #1468

Hope to see more contributions from you :)

**Comment by StephenCWills** [comment]
Yep, I agree. I was just attempting to tackle #984 to the letter, but #1468 is an impressive solution and more broadly applicable. I'll certainly keep poking around for more ways to contribute.

**Pull request closed without merging**
