### PR TITLE
Replace NULL with nullptr

### PR DESCRIPTION
**Pull request by Jmgr**
This replaces `NULL` with `nullptr`. More info: https://dzone.com/articles/what-exactly-nullptr-is-in-c

### CODE REVIEW

**Comment by glebm** [comment]
Once @AJenbo updates `.clang-tidy` to his liking :eyes: , we can apply all such changes automatically in one go.

This particular one is:

```bash
run-clang-tidy -checks='-*,modernize-use-nullptr' -p build 'Source.*' -fix -format
```

**Comment by Jmgr** [comment]
Sure, but why not apply this one now? It's completely risk free AFAIK.

**Comment by glebm** [comment]
Other than introducing merge conflicts with any of the 80 open pull requests? :)

**Comment by glebm** [comment]
I think this is fine but I'd rather we do all modernization changes in one go, so that people don't have to rebase and resolve conflicts more than once

**Comment by Jmgr** [comment]
> I think this is fine but I'd rather we do all modernization changes in one go, so that people don't have to rebase and resolve conflicts more than once

Well, maybe there should not be so many open PRs then ;)

**Comment by AJenbo** [comment]
> Well, maybe there should not be so many open PRs then ;)

Hard to merge things that aren't ready :D

I don't mind doing some rebasing as I merge things, so it's not too big of an issue from where I'm sitting. Of cause people doing the rebasing before hand is much appreciated :heart: 

I usually let people know when I'm about to go over their PR so that gives them a chance to rebase if they are willing to do so.

**Comment by AJenbo** [comment]
P.s. it was down to 50 last week something about 1.2.0 seams to have attracted new developers :D

**Comment by Jmgr** [comment]
> > Well, maybe there should not be so many open PRs then ;)
> 
> Hard to merge things that aren't ready :D
> 
> I don't mind doing some rebasing as I merge things, so it's not too big of an issue from where I'm sitting. Of cause people doing the rebasing before hand is much appreciated heart
> 
> I usually let people know when I'm about to go over their PR so that gives them a chance to rebase if they are willing to do so.

That seems totally reasonable :+1:

**Comment by Jmgr** [comment]
> P.s. it was down to 50 last week something about 1.2.0 seams to have attracted new developers :D

That's very good. But more people means more arguing about stuff though. And developers are known to have their own habits. Oh well.

**Comment by Jmgr** [comment]
Closing this as it will be included into a bigger set of changed later.

**Comment by AJenbo** [comment]
Oh, I was actually good with merging this, but if you are happy with it coming via a clean-up from me in a couple of days that works too. Sorry things are a bit chaotic :)

**Comment by Jmgr** [comment]
> Oh, I was actually good with merging this, but if you are happy with it coming via a clean-up from me in a couple of days that works too. Sorry things are a bit chaotic :)

Ah ok, reopening then.

**Comment by glebm** [comment]
Please let's do all the cleanups in a single PR once `.clang-tidy` is finalized.

How many times will I have to rebase my PRs if this is piecemeal?

Without an agreed-upon `.clang-tidy` it's also easy for these to regress.

**Comment by AJenbo** [comment]
Once, if I merge them at the same times. I'll get `.clang-tidy` done this week.

**Comment by julealgon** [comment]
> Please let's do all the cleanups in a single PR once .clang-tidy is finalized.
> 
> How many times will I have to rebase my PRs if this is piecemeal?

I think having each category of change done in separate commits is much better as well. Otherwise you end up with a huge commit containing all sorts of things and it is very hard to review/navigate it.

Rebasing should take the same effort whether it is one or many commits as long as the commits don't touch the same things twice (which shouldn't be the case).

Making all changes at the same time is a bad idea imho.

**Comment by glebm** [comment]
Separate commits are definitely good, but doing them all around the same time is also good

**Comment by AJenbo** [comment]
Sorry but it looks like this might be simpler to do using clang-tidy.

**Comment by AJenbo** [comment]
Applied via https://github.com/diasurgical/devilutionX/commit/bb4e1960e73b0107a0a26fcbd7036a2074418c99

> This replaces `NULL` with `nullptr`. More info: https://dzone.com/articles/what-exactly-nullptr-is-in-c

Thanks for the read.

**Pull request closed without merging**
