### PR TITLE
CMakeLists.txt: "lib" -> "${CMAKE_INSTALL_LIBDIR}"

### PR DESCRIPTION
**Pull request by glebm**
Refs #7470

@Espionage724 Can you please check if the resulting RPM package is correct?

### CODE REVIEW

**Comment by glebm** [comment]
Checked myself, the above still installs to /usr/lib

```
cmake -S. -Bbuild-rel -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISCORD_INTEGRATION=ON
cmake --build build-rel -j --target package && rpm -qlp build-rel/devilutionx-1.6.0-1.x86_64.rpm
```

**Comment by glebm** [comment]
I'm guessing we're somehow supposed to tell the CPack RPM generator to use RPM's `%{_libdir}` macro

**Comment by glebm** [comment]
I haven't figured out a way to do this.

**Comment by AJenbo** [comment]
Maybe an issue with CPack?

**Pull request closed without merging**
