### PR TITLE
Fix incorrect SOLData for L1 arched/pillar Pieces (BlockLight and BlockMissile is missing)

### LINKED ISSUE #1690: Transparent room
**Important information**
Windows 10 Pro 64 / DevilutionX version 1.2.1 / downloaded release

**Describe**
Can see contents of room (monsters, barrels) in cathedral despite no line of sight.

**To Reproduce**
1. Load [single_2.zip](https://github.com/diasurgical/devilutionX/files/6371623/single_2.zip)

**Screenshots**
transparent wall

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #1690

### CODE REVIEW

**Comment by obligaron** [comment]
I checked all arches I could find (perhaps missed one) and set for all of them block missile and block lightning constantly.

They are often not set consistent.
<details><summary>Examples from Master</summary>
1. Example:
Top arch blocks vision and blocks missiles
grafik
Bottom arch doesn't block vision and missiles
grafik

2. Example:
Top arch blocks vision and blocks missiles
grafik
Bottom arch doesn't block vision and missiles
grafik
</details>

This changes gameplay (difference in vision affects monster behavior/ai and difference in block affects missiles).
That's why the timedemo fails.
Should we accept this changes (and make a new timedemo) or leave it (for now) and close the pr? 🤔

**Comment by FitzRoyX** [comment]
>Should we accept this changes (and make a new timedemo) or leave it (for now) and close the pr? 🤔

Many other fixes in the past would've also changed the timedemo, we can't have fixes anymore? I do think that it's good idea for someone else to see if they can find any you missed, though.

**Comment by obligaron** [comment]
Sorry if I was unclear.
I have no problem with recording a new timedemo (for this pr and future pr's).
But if we don't want to take this changes (cause it affects gameplay), I would rather not do the work to make a new recording. That's why I asked beforehand. 😁 

It would be cool if someones else could look at the pieces again and check them. 🙂 

btw: if we want to take the pr. I'm thinking of adding a commit that removes the [special case for object selection](https://github.com/diasurgical/devilutionX/pull/4987#discussion_r924339583) and then record the new timedemo with both changes. 🙂

**Comment by AJenbo** [comment]
There now I can finally review this :)

image

**Review by AJenbo — DISMISSED** [review]

**Comment by AJenbo** [comment]
I think this fix makes sens, but it's going to need a new demo I guess. Should we maybe go over all tiles to make sure they are correct first?

**Comment by obligaron** [comment]
I think it would be a good idea to look over all cathedral tiles.
The other tile sets are not tested with the shareware, so they don't affect the demo recording.

Do you know other incorrect tiles (expect walls and arches)?
I know #1283 but that's a more complex issue.

**Comment by obligaron** [comment]
I checked all d1 tiles again with the [new tooling](https://github.com/diasurgical/devilutionX/pull/5264#issuecomment-1234976881).
Note: I didn't test all cases.

**Comment by AJenbo** [comment]
Nice. Lets just keep this PR to the cathedral tiles, we can look at the others later.

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
