### PR TITLE
Segment Japanese translation with ZWSP using Sudachi

### PR DESCRIPTION
**Pull request by glebm**
image

Also includes a fix to the removal of redundant ZWSP in the Chinese segmentation.

For now, I went with [Sudachi's](https://github.com/WorksApplications/sudachi.rs) default tokenization granularity (`C`, long word units). We can reduce the granularity to `B` or `A` if this turns out to look a bit janky.

Follow-up to #3438, which did something similar for Chinese.

Example of Sudachi segmentation:

```shell
tools/segmenter/segment_ja.py --debug '迷宮の住人たちはさらに強化され、より大きな挑戦となるでしょう。経験豊富なキャラクターにのみお勧めです'
```
> 迷宮｜の｜住人｜たち｜は｜さらに｜強化｜さ｜れ、より｜大きな｜挑戦｜と｜なる｜でしょう。経験｜豊富｜な｜キャラクター｜に｜のみ｜お勧め｜です

/cc @bubio

### CODE REVIEW

**Review by AJenbo — DISMISSED** [review]

**Comment by glebm** [comment]
Made some last-minute fixes, needs re-approval

**Review by AJenbo — APPROVED** [review]

**Comment by bubio** [comment]
@glebm 

I tried it on Android.
Maybe it's because the screen is horizontal(1080x2340), but there's a lot of white space on the right.


Screenshot_2021-11-19-16-09-15-331_org diasurgical devilutionx
Screenshot_2021-11-19-16-14-24-200_org diasurgical devilutionx

**Comment by glebm** [comment]
That's fixed on master, the fix just isn't in the Android version yet.

**Comment by bubio** [comment]
I've tried it with the latest test version!
It's perfect!

Screenshot_2021-11-19-19-04-59-575_org diasurgical devilutionx

**Pull request merged**
