### PR TITLE
Remove unused Warrior sounds

### PR DESCRIPTION
**Pull request by glebm**
List taken from the PS2 PR (https://github.com/diasurgical/devilutionX/pull/5238) and these 2 files:

1. sfx/warrior/warior96.wav
2. sfx/warrior/warior97.wav

PR for devilutionx-mpq-tools: https://github.com/diasurgical/devilutionx-mpq-tools/pull/9

### CODE REVIEW

**Comment by AJenbo** [comment]
The same sounds can be removed from all heroes, I didn't get around to making a PR for it since I didn't check to make sure that they where all fully unused. But I guess since you removed them that takes care of validating that they are unused :)

**Comment by glebm** [comment]
> But I guess since you removed them that takes care of validating that they are unused

I didn't actually check anything, I simply copied the list from the PR!

**Comment by FitzRoyX** [comment]
I feel like this is one of many reasons why portathon to outdated hardware is problematic. Any modder that wants to use unused assets now has to laboriously add them back in, all because the PS2 has some ridiculously low ram limit? How many people have a ps2 but not a pc?

**Comment by DakkJaniels** [comment]
> Any modder that wants to use unused assets now has to laboriously add them back in, all because the PS2 has some ridiculously low ram limit?

I kind of agree - can't we use a preprocessor directives for a low ram build, or just comment out the lines so they can be added back in easily enough?

**Comment by glebm** [comment]
We already removed a ton of unused stuff from the codebase, ifdefs here alone would not be enough.
Eventually we'd probably want to move this from the code into configuration files anyway.

**Comment by AJenbo** [comment]
yeah having this cleaned out would make it easier to solve issues like https://github.com/diasurgical/devilutionX/issues/3532 and making things data driven which should make modding a lot easier all in all.

**Comment by DakkJaniels** [comment]
Fair enough - I guess if everything is being pulled at some point and we've already pulled a lot of this stuff, no sense in keeping this around now.

**Comment by FitzRoyX** [comment]
> yeah having this cleaned out would make it easier to solve issues like #3532 and making things data driven which should make modding a lot easier all in all.

So why did we add dialog for the unused quest wavs then such as this https://github.com/diasurgical/devilutionX/pull/1092 if we're now removing the wavs themselves?

#3532 doesn't even look like a real issue, it just looks like a mod issue. They could've easily done all the wavs.

**Comment by AJenbo** [comment]
Ok , feel free to record the missing lines

**Comment by StephenCWills** [comment]
> So why did we add dialog for the unused quest wavs then such as this #1092 if we're now removing the wavs themselves?

Perhaps if the lines being removed here were providing any real value at all, you might have a point. It's all just `PS_WARR#` enum values and the corresponding array entries that reference the `warior#.wav` files. We could comment them like the speech entries in the PR you referenced, but I fail to see how that would be useful in this case.

At best, you can claim that this PR would be eliminating the mapping that enables you to determine which wav file each `HeroSpeech` enum value can be found in. However, if you look a bit closer, you'll notice that `herosounds` just lays out the sound files in ascending order by number so it's still not hard to reconstruct it.

It's a bit annoying for modders that have to add these back in, but it's not a huge amount of work. As has been already mentioned, we have future plans for making things easier on modders anyway.

**Comment by glebm** [comment]
Retargeted to development

**Pull request closed without merging**
