### PR TITLE
Update Japanese translations 

### PR DESCRIPTION
**Pull request by bubio**
- **100% translated!**
- Translated a sentence from Hellfire.
- The wording for the credits has been changed back to English.
  (Because it looks better that way!)
- Fixed minor mistranslations.

### When I test-played the game, it frequently crashed during combat with enemies.
- Debug build of commit 366b596
- Hellfire
- GOD mode
- In situations where there are a lot of enemies, like level 15, attacking an enemy may cause it to crash.
- I tried the same thing in English, but it didn't crash.
- Crash log is attached.
   [hellfire_crash_ja_debug.txt](https://github.com/diasurgical/devilutionX/files/7532010/hellfire_crash_ja_debug.txt)

### CODE REVIEW

**Comment by glebm** [comment]
Thanks! Could you please file a bug for the crash with a save attached?

**Comment by bubio** [comment]
hellfire_crash_en_debug.txt
is the crash log

**Comment by glebm** [comment]
Yeah I’ve seen the crash log but it would also be helpful if you could attach a save game just before the crash, so that it’s easy to reproduce

**Comment by bubio** [comment]
Oh, that's what you mean!

I saved the game when I was surrounded by enemies.
After this, I attacked an enemy and it crashed.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7532105/single_0.hsv.zip)

The crash log from that time is also attached.
[hellfire_crash_ja_debug_level15.txt](https://github.com/diasurgical/devilutionX/files/7532103/hellfire_crash_ja_debug_level15.txt)

**Comment by bubio** [comment]
There's a conflict...
What am I supposed to do?

**Comment by AJenbo** [comment]
> There's a conflict... What am I supposed to do?

When thing are merged you need to rebase your fork. The problem is that you are asking to have both the previous and the new changes applied.

**Comment by bubio** [comment]
Hi, AJenbo

Thank you.

But I don't know how to do that.
Does it mean I can keep this pull request and change what to merge?

**Comment by AJenbo** [comment]
Yes, but the revert you did effectively means that you asked for no changes to be made. I assume that was not your intent and have merged the changes instead: https://github.com/diasurgical/devilutionX/commit/cd4ccefbc81758740b28b4cb12cbf1613e9e3aba

You should reset your fork before doing further work to avoid having this issue again.

If you have not already added us as an upstream:
```bash
git remove add diasurgical https://github.com/diasurgical/devilutionX.git
```
Then to reset:
```
git fetch
git reset --hard diasurgical/master
git push --force
```
Note that this will loos any changes that have not yet been merged, so only do it if your changes are merged and you have not made any new ones since then.

A safer way, but that can get more complicated if things where changed in other ways then what you did:
```
git fetch
git rebase diasurgical/master
git push --force
```

**Comment by AJenbo** [comment]
I created the crash report for you: https://github.com/diasurgical/devilutionX/issues/3490

**Comment by bubio** [comment]
Thank you so much for the explanation!

The procedure is to run it in a forked local repository, right?
```shell
cd [local repository]
git remote add diasurgical https://github.com/diasurgical/devilutionX.git

```
It's remote, not remove, right?

```shell
git fetch
```
This is OK.


```shell
git reset --hard diasurgical/master
```
This will cause an error.

`fatal: ambiguous argument 'diasurgical/master': unknown revision or path not in the working tree.`


Is there any difference?

**Comment by AJenbo** [comment]
Correct, maybe it needs to be `git fetch --all` for it to get the non-default remote.

**Comment by bubio** [comment]
It's done!

Thank you so much for taking the time to help me!

**Pull request closed without merging**
