### PR TITLE
fix mac builds

### PR DESCRIPTION
**Pull request by qndel**
latest asio changes break mac builds, this is a working asio build + my fix for double windows errors

### CODE REVIEW

**Comment by AJenbo** [comment]
kinda depressing... ps maybe we should fork it on diasurgical and not your private account :)

**Comment by qndel** [comment]
> kinda depressing... ps maybe we should fork it on diasurgical and not your private account :)

up to you, atm I just wanted to get the mac build to work 😅

**Comment by StephenCWills** [comment]
We may end up needing our own fork anyway because 3DS doesn't support the `pipe()` system call. Switching the `select_interrupter` implementation to the `socket_select_interrupter` is the simplest solution, but for some reason they added the following preprocessor logic to both `socket_select_interrupter.hpp` and `socket_select_interrupter.ipp` so we can't just override this one header.
https://github.com/chriskohlhoff/asio/blob/a41c0b5299115264d2740ae0f19fb88e6124d90d/asio/include/asio/detail/select_interrupter.hpp#L33-L39

@qndel Unless you want to manage all the PRs for the fork by yourself, it might be a good idea to put it on diasurgical.

**Comment by qndel** [comment]
> We may end up needing our own fork anyway because 3DS doesn't support the `pipe()` system call. Switching the `select_interrupter` implementation to the `socket_select_interrupter` is the simplest solution, but for some reason they added the following preprocessor logic to both `socket_select_interrupter.hpp` and `socket_select_interrupter.ipp` so we can't just override this one header.
> https://github.com/chriskohlhoff/asio/blob/a41c0b5299115264d2740ae0f19fb88e6124d90d/asio/include/asio/detail/select_interrupter.hpp#L33-L39
> 
> @qndel Unless you want to manage all the PRs for the fork by yourself, it might be a good idea to put it on diasurgical.

good point lol!

**Comment by AJenbo** [comment]
https://github.com/diasurgical/asio

**Pull request merged**
