### PR TITLE
Fix invalid file and line constants

### PR DESCRIPTION
**Pull request by FooSoft**
Fixing call sites which were lying about both the current file and line number. The line number specifically was annoying since it is not immediately obvious what it is when skimming function calls.

### CODE REVIEW

**Comment by OrangBuangan** [comment]
Maybe this should be a macro?

**Comment by FooSoft** [comment]
Sure, makes sense to me

**Comment by FooSoft** [comment]
Updated!

**Comment by galaxyhaxz** [comment]
The macro `#define ASSERT_FAIL(failMsg)` isn't needed since those were just comments added by Ajenbo. We already have the macro `assert(exp)` for assertions.

**Pull request merged**
