### PR TITLE
Stream demo messages

### PR DESCRIPTION
**Pull request by glebm**
This entirely eliminates the demo memory overhead.

### CODE REVIEW

**Comment by glebm** [comment]
This is based on #6549 which is based on #6548, so you can just merge this PR and close the other ones

**Comment by glebm** [comment]
Oddly, this segfaults when profiling on rg99

**Comment by AJenbo** [comment]
> This is based on https://github.com/diasurgical/devilutionX/pull/6549 which is based on https://github.com/diasurgical/devilutionX/pull/6548, so feel to only merge this PR and close the other ones

Saw this one last :) Sorry it needs a rebase now :/

**Comment by glebm** [comment]
Rebased :+1:

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
