### PR TITLE
Add info popup to the Import Data activity

### LINKED ISSUE #6756: [Issue Report]: import data breaks mpq files
### Operating System

Android

### DevilutionX version

1.5.1

### Describe

I tried the "import data" function, which wasn't described. As the game couldn't find mpq files (they were there, tho), I thought maybe importing mpq will help. After selecting diabdat.mpq there weren't any error message, but next time I opened the game, game served error saying data is broken. Indeed after "import" diabdat was 0 byte long. I still don't know exactly what "import data" does, but I'm sure it's not supposed to nullify files.

### To Reproduce

1. Long tap on the devilution icon
2. choose "import data"
3. choose diabdat.mpg

### Expected Behavior

show error message or info what "import data" really is

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by StephenCWills**
image

This resolves #6756

### CODE REVIEW

**Review by AJenbo — DISMISSED** [review]
Should we add a settings that guards this so it's only shown the first time?

**Comment by StephenCWills** [comment]
I don't think it's annoying enough to warrant skipping it. IMO, better to risk annoying the user than jump through hoops to potentially shoot them in the foot, like if they ever move files to their SD card or their friend/sibling dismisses the dialog for them.

**Comment by StephenCWills** [comment]
> Might still be good to notify them that they are about to overwrite a file (if we can do that).

Like with everything in Java, this was harder than it should have been.

image

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Nice work, both should help people realize what this option is doing.

**Pull request merged**
