### PR TITLE
Updating Xcode project with new files

### PR DESCRIPTION
**Pull request by BennyFranco**
This fix the macOS build for x86

### CODE REVIEW

**Comment by AJenbo** [comment]
Oh thanks, I was hoping you would be able to help with solving this :)

**Comment by BennyFranco** [comment]
Sure, no problem :D

**Comment by AJenbo** [comment]
Now we just need to figure out the MSVC issue :/

**Comment by AJenbo** [comment]
@BennyFranco looks like we broke the 32bit mac build again, could you update the xcode project with the new *dat.cpp files?

**Comment by BennyFranco** [comment]
Sure, I'll fix it tonight after work :D

**Pull request merged**
