### PR TITLE
fix reflect on loading

### PR DESCRIPTION
**Pull request by qndel**
Fixes https://github.com/diasurgical/devilutionX/issues/2632
Manashield and reflect should get a full rewrite at some point, current code is beyond garbage, that's why it needs to be patched out in seemingly random places :D

I made reflect replicate manashield logic.

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
Pretty sure I would reject most of this if it wasn't copied from the manashild code. I do have a nagging feeling that a bunch of it is however redundant and could be done with some shared function, but we can look at that later.

**Comment by qndel** [comment]
Yeah that's why I'm saying it should be rewritten anyway - tbh old reflect's code seemed to work just fine, it only had 1 flaw - always removing reflect on InitMissiles() which also happened on reloading the game so I guess a quick and dirty fix would be just letting that function know if you reloaded the game, if yes, don't remove reflect :D 

Also I'm suspecting that infravision is getting removed on load as well

**Comment by julealgon** [comment]
Holy shit at this change! this code man... 🤦‍♂️

**Comment by qndel** [comment]
> Holy shit at this change! this code man... 🤦‍♂️

I mean old reflect probably worked just fine, it'd only require a dirty hack to stop deleting it on loading, but since manashield works fine, I just duplicated it

**Pull request merged**
