### PR TITLE
Make SourceX/dvlnet C++11 compatible

### PR DESCRIPTION
**Pull request by glebm**
std::make_unique is only available in C++17 and above

### CODE REVIEW

**Comment by AJenbo** [comment]
Can confirm that the game now builds correctly on CLang 3.8.1 :+1:

**Comment by kraileth** [comment]
Dang, should have thought about the c++11 option, as I've seen that issue before with another application... Anyway - this fixes native builds on FreeBSD, too (tested with Clang 6.0.1 on FreeBSD 12.0)! Also the segfault that I got before is gone now. It just segfaults when trying to load an older save game, but that's expected.

Perfect timing for this change now that 0.5 is around the corner from what I read! Many thanks @glebm!

**Comment by AJenbo** [comment]
@kraileth thanks for reporting this, this will be very helpful for doing the release. Regarding the release, I'm mostly just bringing some of the out of branch ports up to speed so that things are aligned. Plus buying time for little fixes like this to trickle in :)

Was the save game you mentioned generated with a previous 64bit build?

**Comment by kraileth** [comment]
@AJenbo Yes, the save was made on my amd64 workstation with DevilutionX installed from the official FreeBSD package repo (which is built from the 0.4.0 distfile).

At some point DevilutionX stopped working on FreeBSD (at least on amd64, didn't check i386). I intended to try out various versions to find out when it started segfaulting, but didn't find the time, yet. And now I'm pretty happy that this planned work is already obsolete! :)

**Comment by AJenbo** [comment]
Ok sounds like your right about the save being invalid since it was basically from a development version of the 64bit version. As you might have seen this produced invalid saves up until just 8 days ago when the last issue was solved.

**Pull request merged**
