### PR TITLE
Fix MSVC warnings in stores.cpp

### PR DESCRIPTION
**Pull request by obligaron**
This PR reduces warnings by 4 (from 17 to 13).

I thought about doing more refactoring... but stores.cpp needs a more general approach.

Now only `mpq_writer` and `mpq_sdl_rwops` is missing. And there I'm unsure if I should change everything size related to `size_t`, `uint32_t` or `uintmax_t`. 😁

### CODE REVIEW

**Comment by AJenbo** [comment]
Store needs a rewrite, it's a mess :/

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
> Now only mpq_writer and mpq_sdl_rwops is missing. And there I'm unsure if I should change everything size related to size_t, uint32_t or uintmax_t. 😁

Since it's dealing with files I would have thought `size_t` would be the right option

**Comment by obligaron** [comment]
> Since it's dealing with files I would have thought `size_t` would be the right option

It's also complicated...

libmpq has
```cpp
/* file offset data type for API*/
typedef int64_t libmpq__off_t;
```

SDL `SDL_RWops` needs
```cpp
#ifndef USE_SDL1
using OffsetType = Sint64;
using SizeType = size_t;
#else
using OffsetType = int;
using SizeType = int;
#endif
```

🤔

**Comment by AJenbo** [comment]
Mmm, I see what you are saying. Well if it's any help SDL1 is the fall back so it should have all the ugly casts and we should go with what SDL2 preferes when that comes up.

**Pull request merged**
