### PR TITLE
Text rendering: Clip text to the given rect

### PR DESCRIPTION
**Pull request by glebm**
Previously, we only clipped to the given surface, without clipping to the given rect.

We do not actually need this for anything, I was just taken by surprise when this did not work as I'd expected.

### CODE REVIEW

**Comment by StephenCWills** [comment]
Does this only clip the right and bottom edges of the rect?

If so, do we need to clip the left and top edges as well? What happens if text is centered horizontally or vertically?

**Comment by glebm** [comment]
I assumed that text is only rendered left-to-right, top-to-bottom, so no need for left/top clipping.
If the text is centered, it is still centered within the same rect, so I think the clipping should stay the same?

**Comment by StephenCWills** [comment]
Now that you mention it, I should have known that.. #5367 😅

**Review by StephenCWills — APPROVED** [review]

**Comment by AJenbo** [comment]
Starting to feel like a real professionel here:

image

**Pull request merged**
