### PR TITLE
Remove vegtable dialog

### PR DESCRIPTION
**Pull request by AJenbo**
It's kinda silly and may have been deliberately disabled

### CODE REVIEW

**Comment by qndel** [comment]
it's not silly, it's classic! + not everyone knows what it says backwards

**Comment by StephenCWills** [comment]
I'm not sure I understand the reasoning behind the conclusion that this may have been deliberately disabled. [You said](https://github.com/diasurgical/devilution/pull/454#issuecomment-436787042) it was broken in vanilla v1.0.0, so were you thinking they deliberately didn't fix it in any of their patches? Maybe it was just a low-priority bug that few ever noticed and no one ever bothered to resolve.

**Comment by qndel** [comment]
Or like galaxy wrote 
> "Funny enough, I never realized this was broken, because I always use the command line to start at level 16 directly, therefore 15 is still "never visited"."

Maybe it was the exact same case with them.

**Comment by AJenbo** [comment]
> it's not silly, it's classic! + not everyone knows what it says backwards

I think it's silly not even knowing what it is saying :shrug:

**Comment by AJenbo** [comment]
> [You said](https://github.com/diasurgical/devilution/pull/454#issuecomment-436787042) it was broken in vanilla v1.0.0, so were you thinking they deliberately didn't fix it in any of their patches?

Like I said in that quote, it was never functional in any version. My thinking is that they deliberately changed the code to be non function before release in order to disable it.

**Comment by qndel** [comment]
> > [You said](https://github.com/diasurgical/devilution/pull/454#issuecomment-436787042) it was broken in vanilla v1.0.0, so were you thinking they deliberately didn't fix it in any of their patches?
> 
> Like I said in that quote, it was never functional in any version. My thinking is that they deliberately changed the code to be non function before release in order to disable it.

Even they weren't that special to leave code in and just break it on purpose xD

**Comment by AJenbo** [comment]
🥕 🪥

**Pull request closed without merging**
