### PR TITLE
Enable/disable automap in town using "Settings"->"Gameplay"->"Automap in town"

### PR DESCRIPTION
**Pull request by PaintingTs**
**Motivation**: Many "Quality of Life" features can be switched off in the "Settings" to preserve authentic game experience. There is no such switch for "Automap in town" feature.

**Solution**: 

- Switch is added in the settings ("Settings"->"Gameplay"->"Automap in town")
- By default Automap is switched on
- If switched off, message "No automap available in town" will be displayed when attempting to open automap in town
(just like in vanilla)

Screenshot from 2024-02-25 15-33-18
Screenshot from 2024-02-25 15-33-37

### CODE REVIEW

**Comment by qndel** [comment]
If people don't want automap in town, they can press tab to turn it off, duh

**Comment by PaintingTs** [comment]
> If people don't want automap in town, they can press tab to turn it off, duh

true, but I would still consider it as modification, and would suggest to make it opt-out.

Besides that, for mod-makers it might be helpful to know how to disable town automap, since any changes in the town layout will not automatically project to the automap.

**Comment by PaintingTs** [comment]
Any thoughts from maintainers? Should I close this PR? Should I modify it in some way?

**Comment by DakkJaniels** [comment]
> Any thoughts from maintainers? Should I close this PR? Should I modify it in some way?

One of them did respond to you. I would agree though that if you don't want to see it, just press tab. I don't see why we need to add another toggle to the huge list of settings for something that can be easily disabled with a button press.

**Comment by julealgon** [comment]
> Any thoughts from maintainers? Should I close this PR? Should I modify it in some way?

Not a maintainer. The only thing I can suggest that might be helpful, is to start a discussion/issue before sending a PR with a change. That might save you some effort (depending of course on how simple the change is). 

DevilutionX is purposefully a very opinionated project and you'll get a lot of pushback if reasoning for a change is just for purity reasons (in comparison to the original).

I also think this is quite unnecessary, and thus am against it. Your argument to support mods in the future when towns are modified is a YAGNI violation IMHO. Besides, if the map currently isn't synched with the town (in that changing the town layout would not update the map) then _that_ should be considered a bug/technical debt instead and fixed so it _does_ sync properly: a toggle to not show it would not be a good solution to that.

**Pull request closed without merging**
