### PR TITLE
Implement baked lighting dungeon frame cache

### LINKED ISSUE #6631: Bake lighting into dungeon CELs at load time
Original Diablo pre-renders up to 128 frames / 1 MiB of dungeon CELs with baked lighting on load.

In the original, it is created by [`MakeSpeedCels`](https://github.com/diasurgical/devilution/blob/a982e4c7b0ad62b4c22c4cbb6b3136e36ebdf4e0/Source/gendung.cpp#L263).
The baked-lighting CELs are stored in `pSpeedCels` and are indexed via `SpeedFrameTbl`.
CELs that appear more often on the map have priority when baking ([`SortTiles`](https://github.com/diasurgical/devilution/blob/a982e4c7b0ad62b4c22c4cbb6b3136e36ebdf4e0/Source/gendung.cpp#L245)).
For the baked CELs, `level_cel_block |= 0x8000` flag is set.

Baked lighting cache size should probably be a compile-time option (completely disabled when 0).

We do better than the original in a few aspects:

1. `SortTiles` was bubble sort (4 million iterations), we can just use `std::sort` or `std::priority_queue`.
2. Rather than limiting on RAM and 128 frames, we can limit on RAM alone and allocate `SpeedFrameTbl` dynamically.
3. We can avoid storing `SpeedFrameTable` for fully lit and fully dark tiles.

These optimizations were removed from DevilutionX in https://github.com/diasurgical/devilutionX/pull/361. This may explain the performance difference between DevilutionX and the original on older CPUs (such as Pentium on Windows 98 that we've been measuring). When the optimizations were removed in DevX, the FPS only dropped from 90 to 76 on @AJenbo's Raspberry Pi (https://github.com/diasurgical/devilutionX/pull/361#issuecomment-544253749) but the impact could be much larger on a Pentium.

### PR DESCRIPTION
**Pull request by glebm**
Fixes #6631

I don't see any performance improvement with this on Windows 98. In fact I see a drop. :thinking:

### CODE REVIEW

**Comment by galaxyhaxz** [comment]
> In fact I see a drop.

I don't know where the old conversation is, would have to dig it up (2019 or so, either discord or here). But basically I ran some tests when we were cleaning up devilution and found that the speed cel optimization decreased rendering speed rather than improving it. It was a crap optimization and Ajenbo removed it in the rewrite subsequently.

The drop is most certainly due to the original being 10k lines of pure asm, creating a path for every possible micro tile and all possible configurations. Converting that to C had a slight performance hit, and then that version was used for DevilutionX when refactoring, and any further changes you made probably didn't get it on par with the assembly version.

**Comment by glebm** [comment]
Yeah but I don't quite understand why baking the lighting for some tiles would cause a performance drop.
The only thing I can think of is that more of the non-baked tiles fit in cache. These old Pentiums don't have that much cache so that's also a bit surprising.

**Comment by AJenbo** [comment]
At over half a MB of cache the Pentium II could probably hold most of the tiles in memory. But we can be sure that it would not be able to hold that + 1MB of pre-baked ones.

**Comment by glebm** [comment]
Our rendering code is even more specialized than the original through the magic of templates:

```
$ du -sh build-windows9x/Source/CMakeFiles/libdevilutionx.dir/engine/render/dun_render.cpp.obj
336K	build-windows9x/Source/CMakeFiles/libdevilutionx.dir/engine/render/dun_render.cpp.obj
```

This is great for modern CPUs with huge caches but may not be so great for Pentium.

Perhaps adding a compile-time option for it to be more dynamic would improve performance on the Pentium.

**Comment by AJenbo** [comment]
That bit be interesting to investigate, the emulator I have been using was set up with a 150 MHz Pentium Pro (256 KB L2).

Diablo 1.09
Pentium Pro 150mhz:  120fps
Pentium Pro 200mhz: 164fps
P2 OverDrive 333mhz: 287fps

DevilutionX164
Pentium Pro 150mhz: 51fps
Pentium Pro 200mhz: 48fps
P2 OverDrive 333mhz: 50fps

We do indeed seem to be hitting some sort of bottle neck that isn't clock related. The good news here is that we might actually be competitive with the original at lower clock values.

**Pull request closed without merging**
