### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by majek**

### CODE REVIEW

**Comment by AJenbo** [comment]
what cpu does this affect?

**Comment by majek** [comment]
> what cpu does this affect?

All cpus take performance hit on unaligned loads. On ARM AFAIU by default all loads are supposed to be aligned. I fixed this specific function because I got a nice clang warning on one of my builds (was mac?). I will try to reproduce. Anyhow, this is a pretty trivial fix.

**Comment by majek** [comment]
> This appears to break big endian support.

I'm not sure how.

`
#if SDL_BYTEORDER == SDL_LIL_ENDIAN
#define SDL_SwapLE32(X) (X)
#else
#define SDL_SwapLE32(X) SDL_Swap32(X)
#endif
`

**Comment by AJenbo** [comment]
You replaced two calls to SDL_SwapLE32 with LOAD_LE32 which doesn't take BYTEORDER in to account.

**Comment by majek** [comment]
> You replaced two calls to SDL_SwapLE32 with LOAD_LE32 which doesn't take BYTEORDER in to account.

This is because the code I propose is endian-independent. For example, this snippet returns the same value on LE as on BE.

```
#include <stdio.h>
#include <stdint.h>

int main() {
	uint8_t b[4] = {0x4,0x3,0x2,0x1};
	uint32_t v = (b[0] << 24) | (b[1] << 16) | (b[2] << 8) | (b[3]);
	printf("%08x\n", v);
}
```

**Comment by AJenbo** [comment]
Thanks for the fix

**Pull request merged**
