### PR TITLE
Get rid of unused immunity

### PR DESCRIPTION
**Pull request by vlolteanu**
Does immunity to acid do anything at all? Is it possible to get a monster to take acid damage? AFAIK no player spells/skills do acid damage, and monsters don't have friendly fire.

### CODE REVIEW

**Comment by DakkJaniels** [comment]
I believe acid is used for some check in hellfire.

**Comment by vlolteanu** [comment]
@DakkJaniels Are you related to Whonnie Jalker, by any chance?

**Comment by DakkJaniels** [comment]
Yeah he's my cousin 🤣

**Comment by qndel** [comment]
how did this fail on timedemo? xD

**Comment by vlolteanu** [comment]
It's just a guess, but maybe the immunity flags for the monsters get written to the save file, and since I've just removed one of them, the save files are no longer identical.

**Comment by AJenbo** [comment]
Yeah that lines up, resistance is copied to the monsters which gets stored in the save game.

**Comment by AJenbo** [comment]
> Does immunity to acid do anything at all? Is it possible to get a monster to take acid damage? AFAIK no player spells/skills do acid damage, and monsters don't have friendly fire.

Correct, can be removed.

**Review by AJenbo — APPROVED** [review]

**Comment by StephenCWills** [comment]
> > Does immunity to acid do anything at all? Is it possible to get a monster to take acid damage? AFAIK no player spells/skills do acid damage, and monsters don't have friendly fire.
> 
> Correct, can be removed.

Is this still true despite #4826?

**Comment by DakkJaniels** [comment]
There are missiles in the game that use MISR_ACID. Even if it's not necessarily applicable in the base game, why remove the checks for acid immunity? Should we then just remove MISR_ACID, and replace it with MISR_MAGIC, since it seems that's what's happening anyway?

**Comment by AJenbo** [comment]
> we should probably also remove MISR_ACID, and replace it with MISR_MAGIC.

Probably not because then you can start being immune to it.

**Comment by AJenbo** [comment]
> > > Does immunity to acid do anything at all? Is it possible to get a monster to take acid damage? AFAIK no player spells/skills do acid damage, and monsters don't have friendly fire.
> > 
> > 
> > Correct, can be removed.
> 
> Is this still true despite #4800 and #4826?

Hmm you might be right, I guess we need to test that.

**Comment by vlolteanu** [comment]
AFAIK magic resistance mitigates acid damage for players.

As for the issue at hand, can berserked monsters spit acid at one another? (I guess berserk is a Hellfire thing; I don't play Hellfire.)

**Comment by DakkJaniels** [comment]
> AFAIK magic resistance mitigates acid damage for players.
> 
> As for the issue at hand, can berserked monsters spit acid at one another? (I guess berserk is a Hellfire thing; I don't play Hellfire.)

Yeah, magic resistance mitigates acid damage for players, that is correct. I don't believe players have a way of doing acid damage. It looks like `MISR_ACID` and `IMMUNE_ACID` was in the game originally (per Devilution), but Hellfire and berserk would use that acid damage type and immunity.

**Comment by vlolteanu** [comment]
Ok, acid immunity is back.

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
