### PR TITLE
PVP Arena Rebalance Tweaks

### PR DESCRIPTION
**Pull request by kphoenix137**
Tweaks that occur only in arena levels:
Items:
* No item durability damage

Animation Speed Adjustments:
* Rogue bow attack is 1 frame longer
* Warrior Axe and Staff attack is 1 frame shorter
* Sorcerer casting is 2 frames longer
* Barbarian casting is 1 frame longer

Spell Rebalance:
Spell - Damage - Cast Animation Frame Skips
* Firebolt: +100% damage, 3 frame skips
* Charged Bolt: +100% damage, 2 frame skips
* Inferno: +900% damage, 2 frame skips
* Lightning: +100% damage, 2 frame skips
* Town Portal: 4 frame skips
* Flash: +0% damage, 1 frame skip
* Phasing: 1 frame skip
* Guardian: +100% damage, 4 frame skips (WIP)
    - Targets players (WIP)
    - Can only have 1 active at a time (WIP)
* Teleport: 1 frame skip
* Bone Spirit: 1/3 of Max HP damage (ignores resistance), 1 frame skip
    - Targets players
    - Can attack its caster (WIP)
    - Uses life with Mana Shield active (WIP)
* Blood Star: +700% damage, 2 frame skips
    - Uses life with Mana Shield active (WIP)
* Elemental: +20% damage, 0 frame skips
    - Targets players
* Fireball: -20% damage, 0 frame skips
    - Reduced velocity by ~18%
* Fire Wall: +200% damage, 0 frame skips
    - Duration of slvl 0, regardless of actual slvl
* Flame Wave: +300% damage, 0 frame skips
* Chain Lightning: +100% damage, 0 frame skips
    - Targets players
* Nova: +100% damage, 0 frame skips
* Warp: 4 frame skips

The idea behind adjusting cast speeds of different spells were to help create better use-case scenarios for spells. When damaging spells have all the same cast rate, the only incentive is to pick the spell which is most likely to hit and does the most damage. Weaker spells and spell that are harder to make hit the opponent (and some utility spells) were given boosted speeds to give them a direct upgrade to their usefulness without just giving them a damage increase. Quite a few spells have had their damage increased however, since their original damage values are so pitiful that they simply cannot compete with the damage output of Fireball. This should offer more strategic alternatives to just spamming Fireball at the opponent.

During playtesting, Constantine has made masterful use of alternating between Fireball and Blood Star as a Sorcerer, casting Blood Star when in close proximity to the enemy, as it's faster to cast despite having less velocity, but hard to predict and avoid, resulting in massive damage.
 
Movement Tweaks:
* DIAGONAL WALK: Players in the arena begin taking damage if their total diagonal walk movements in the last 32 movements exceeds 80% of their total movements. Each diagonal walk movement above the threshold deals 1 HP damage * the % above the threshold. This is to deter excessive use of diagonal walk to avoid missiles.

Controls:
* Unable to retain targets by clicking and holding, replicating the vanilla behavior

Combat Mechanics:
* HIT RECOVERY: Hit recovery uses a formula based on incoming damage vs life, instead of being a flat threshold of clvl. Hit Recovery chance is 5%-95%.
`Chance of hit recovery = damage - (max hp / 6) + 100`
* CRITICAL HITS: All damage types can do critical hit damage now. Critical hit chance uses a formula based on Str for melee, Dex for ranged, and Mag for spells. Critical hit damage is +100% for melee, +50% for ranged, and +25% for spells. Bone Spirit cannot do critical hit.
Melee:
`crit chance = (clvl * 2 + str) / 10`
Ranged:
`crit chance = (clvl * 2 + dex) / 10`
Spell:
`crit chance = (clvl * 2 + mag) / 10`
* MISSILE ACCURACY: Fixed a lousy game mechanic that causes missiles to be more inaccurate the longer the animation takes before it reaches the action frame. Now all classes shooting a bow are equally accurate, and all classes casting spells are equally accurate. Accuracy in general is also improved without being too accurate, which would cause unintentional "auto-aim".

### CODE REVIEW

**Comment by kphoenix137** [comment]
Did some playtesting with curses and ericmdk, different class matchups and FFA. So far the results are quite appealing and rebalance PVP in DevilutionX quite well. I think more tweaks might be necessary. It seems that Sorcerer is a bit too crippled, and despite Warrior casting faster, he lacks the speed to catch the Rogue effectively after beginning to swing at her.

**Comment by julealgon** [comment]
@kphoenix137 , remember, if this is not final, use a draft PR instead to avoid notifying everyone.

**Comment by kphoenix137** [comment]
> @kphoenix137 , remember, if this is not final, use a draft PR instead to avoid notifying everyone.

Then it won't build

**Comment by ikonomov** [comment]
You can create a PR in a separate fork, if you keep the workflows enabled it will compile just as it does here.

**Comment by kphoenix137** [comment]
This is definitely a bit too ambitious for its own good and doesn't really fit well within the scope of the project. I'll have to create a mod at a later date.

**Pull request closed without merging**
