### PR TITLE
assign seed to quest items + rng cleanup

### PR DESCRIPTION
**Pull request by qndel**
@AJenbo I know you wanted to get rid of the whole searching for items on the ground by seed, but since you haven't done that yet, it's a simple fix we can remove later and makes picking bloodstones less annoying

### CODE REVIEW

**Comment by AJenbo** [comment]
Isn't this going to affect RNG?

**Comment by qndel** [comment]
how?

**Comment by julealgon** [comment]
What exactly is this "fixing"? Shouldn't we reserve that tag for actual bugs? Is this a bug?

**Comment by AJenbo** [comment]
That you sometimes can't pick up unique quest items like the blood stones. Context was in discord and should have been put in the issue.

**Comment by julealgon** [comment]
> That you sometimes can't pick up unique quest items like the blood stones. 

Ohh ok. Felt like we were just changing something without affecting behavior. Cool.

**Pull request merged**
