### PR TITLE
Update Korean localization

### PR DESCRIPTION
**Pull request by nsm53project**
130/1773 lines

### CODE REVIEW

**Comment by nsm53project** [comment]
AAAAGH, I don't know why the conflict happens. :(

**Comment by AJenbo** [comment]
> AAAAGH, I don't know why the conflict happens. :(

We usually merge by rebasing or squashing, this means that your branch is not directly related to ours. So after a merge you might want to reset yours based on ours.

**Comment by AJenbo** [comment]
Merged manually via https://github.com/diasurgical/devilutionX/commit/6580dc6fb15ad850d96b70c1d07000250e55bf39

**Comment by AJenbo** [comment]
It looks like you are starting with all the difficult ones, but probably really good for the user that all the story parts are translated.

**Comment by nsm53project** [comment]
> It looks like you are starting with all the difficult ones, but probably really good for the user that all the story parts are translated.

I just enjoy translating Diablo because devilutionX is a really good project.

**Pull request closed without merging**
