### PR TITLE
Update Ukrainian translation

### LINKED ISSUE #4807: Extra bracket in translatable text for disabled crippling shrines
**Important information**
Windows 10/ blamed on 1fc8ecb6f6b11b06cc0331bb7395611aa6d34b2d / self-compile

**Describe**
After updating from code, the text for disabled crippling shrines in POEdit is shown as `{:s} (disabled))`
Relevant source code:
https://github.com/diasurgical/devilutionX/blob/4c62905381f2fe8364d18d5c3d67a28270596949/Source/objects.cpp#L5504

**Expected behavior**
Text for disabled crippling shrines in POEdit is shown as `{:s} (disabled)`

### PR DESCRIPTION
**Pull request by tsunamistate**
Also fix #4807 while I'm at it
If anyone bothers to review this - do just the last commit

### CODE REVIEW

**Comment by AJenbo** [comment]
@SourceCodeDeleted do you have time to review?

**Comment by tsunamistate** [comment]
@AJenbo now that #4807 was fixed via https://github.com/diasurgical/devilutionX/pull/4868, does that mean I should delete the first commit?

**Comment by ephphatha** [comment]
Looks like github picks up that it'll be an empty commit and will skip it when the PR is merged.

**Comment by tsunamistate** [comment]
Removed the commit anyway :)

**Comment by tsunamistate** [comment]
@AJenbo looks like @SourceCodeDeleted is out (hope they're OK)
This is low risk PR, can we get this merged please?

**Comment by SourceCodeDeleted** [comment]
sorry I was sick this weekend.

It looks good.

**Comment by AJenbo** [comment]
@SourceCodeDeleted thanks, good to hear you are well again :)

**Pull request merged**
