### PR TITLE
Reset button mapping for MiyooMini to the current default layout

### PR DESCRIPTION
**Pull request by Trihedraf**
There is no way to confirm in the in-game menu with this being set. With this change both the start button and A button work for confirm. There is a dedicated Menu button on the MiyooMini making there be no reason the start button needs to be the menu button.

### CODE REVIEW

**Comment by glebm** [comment]
> There is no way to confirm in the in-game menu with this being set.

Why doesn't A work when start is mapped to the menu?

**Comment by glebm** [comment]
Ah, I see, start is actually `TAB`.
By the way, the menu can also be triggered with START + SELECT

**Comment by glebm** [comment]
We've actually introduced remappable controls in 1.5.0, so it'd be better to change all the mappings to the actual buttons.

So e.g. instead of:

```diff
- set(KBCTRL_BUTTON_BACK SDLK_BACKSPACE)
+ set(KBCTRL_BUTTON_BACK SDLK_RCTRL)
```

This way they'll be configurable, for now in the ini, hopefully in the UI before 1.5.0.

**Comment by Trihedraf** [comment]
Ok I've set all the buttons to the default layout, so it should all be remappable with the new system

**Review by glebm — APPROVED** [review]

**Pull request merged**
