### PR TITLE
add a check for trap missiles for TRNs

### PR DESCRIPTION
**Pull request by qndel**
Resolves https://github.com/diasurgical/devilutionX/issues/4078
Thanks @obligaron :)

### CODE REVIEW

**Review by obligaron — APPROVED** [review]

**Review by StephenCWills — APPROVED** [review]

**Comment by Chance4us** [comment]
Unfortunately, I had the impression that if the unique skeleton "Skullfire (Corpse Bow)", see https://diablo2.diablowiki.net/D1_Skeleton_Archer_Bosses, comes into view, a crash can occur. Unfortunately, I could not determine for sure whether the bug is related to TRNs. Unfortunately, the crash behavior was irregular.

**Comment by qndel** [comment]
> Unfortunately, I had the impression that if the unique skeleton "Skullfire (Corpse Bow)", see https://diablo2.diablowiki.net/D1_Skeleton_Archer_Bosses, comes into view, a crash can occur. Unfortunately, I could not determine for sure whether the bug is related to TRNs. Unfortunately, the crash behavior was irregular.

image
works fine for me

**Comment by Chance4us** [comment]
Good that makes me happy. I'll keep an eye on it. Can the TRN changes affect the savegame files in some kind?

**Comment by Trihedraf** [comment]
Thanks for fixing @qndel

**Comment by qndel** [comment]
> Good that makes me happy. I'll keep an eye on it. Can the TRN changes affect the savegame files in some kind?
I moved a devilutionx save to hellfire and hellfire save to devilutionx and noticed no side effects.

**Comment by Chance4us** [comment]
> > Good that makes me happy. I'll keep an eye on it. Can the TRN changes affect the savegame files in some kind?
> 
> I moved a devilutionx save to hellfire and hellfire save to devilutionx and noticed no side effects.
> 
> @Chance4us also pls report every crash, I don't think anything should be crashing in devilutionx so I'm a bit worried when you mention random crashes lol

All right, I'll take really good care of it.

**Pull request merged**
