### PR TITLE
Spell and Missile enum revision and SpellPages cleanup

### PR DESCRIPTION
**Pull request by kphoenix137**

### CODE REVIEW

**Comment by FitzRoyX** [comment]
Is there some reason we can't just rename the enums so that they are self-explanatory? i.e. SPL_RNDTELEPORT becomes SPL_PHASING, and SPL_FLAME becomes SPL_INFERNO

**Comment by DakkJaniels** [comment]
> Is there some reason we can't just rename the enums so that they are self-explanatory? i.e. SPL_RNDTELEPORT becomes SPL_PHASING, and SPL_FLAME becomes SPL_INFERNO

They probably should, and change them to enum class like the others 🤷🏽‍♂️

**Comment by kphoenix137** [comment]
> Is there some reason we can't just rename the enums so that they are self-explanatory? i.e. SPL_RNDTELEPORT becomes SPL_PHASING, and SPL_FLAME becomes SPL_INFERNO

image
YOUR WISH.. HAS BEEN GRANTED

**Comment by qndel** [comment]
btw SPL_RUNEOFSTONE has a confusing name, you can rename it to SPL_RUNEOFSTONECURSE (it won't even be the longest name, same length as SPL_RUNEOFIMMOLATION :D)

**Comment by AJenbo** [comment]
Replaced by https://github.com/diasurgical/devilutionX/pull/5681

**Pull request closed without merging**
