### PR TITLE
CircleCi, CMake, AppImage updates

### PR DESCRIPTION
**Pull request by Trihedraf**

### CODE REVIEW

**Comment by AJenbo** [comment]
A lot nicer to look at. By the way, I noticed the old process didn't work on ARM as I downloaded an x86_64 prebuild tool. Does this do anything to improve that?

Also, I had a report from an Arch user that hitting enter in the menu results in two clicks in the menu. I'm guessing this is related to the embedded SDL?

**Comment by Trihedraf** [comment]
> A lot nicer to look at. By the way, I noticed the old process didn't work on ARM as I downloaded an x86_64 prebuild tool. Does this do anything to improve that?

Which process are you talking about?

> Also, I had a report from an Arch user that hitting enter in the menu results in two clicks in the menu. I'm guessing this is related to the embedded SDL?

That would be my guess. Going to Testing takes SDL2 from 2.0.9 to 2.0.14.

**Comment by AJenbo** [comment]
> > A lot nicer to look at. By the way, I noticed the old process didn't work on ARM as I downloaded an x86_64 prebuild tool. Does this do anything to improve that?
> 
> Which process are you talking about?

Generating a .appimage file. I checked the repo that you downloaded the application from, but they do not provide an ARM build.

**Comment by Trihedraf** [comment]
Oh yeah, it's kind of annoying.

**Comment by Trihedraf** [comment]
> Also, I had a report from an Arch user that hitting enter in the menu results in two clicks in the menu. I'm guessing this is related to the embedded SDL?

I just tried 1.2 release appimage on Arch as was stated in the issue and it didn't double input for me.

**Pull request merged**
