### PR TITLE
Fix OOB in DoLighting

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by qndel** [comment]
is it oob? I'd say it's just a fancy way of accessing stuff :D

**Comment by glebm** [comment]
This does result in OOB and a crash with the MIPS gcc compiler in `-O2` mode.

The compiler can assume the second index fits when generating the code, and generate something very different from what was intended.

**Comment by qndel** [comment]
huh, interesting

**Comment by glebm** [comment]
Closing in favour of a binexact upstream fix: https://github.com/diasurgical/devilution/pull/1840

**Comment by AJenbo** [comment]
It has now been merged https://github.com/diasurgical/devilutionX/commit/b6695fe26b68e0d4c39d7c9ee67bfa85d50a6520

**Pull request closed without merging**
