### PR TITLE
Multiplayer: Sync Hellfire Quests

### LINKED ISSUE #4192: MP: Graphics not synced for little girl when completing quest
Triggering the end of the Theo quest only updates the graphics for the player that talks to the little girl.

image

(the same is likely true for the Nut in the Cow Quest)

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #4192

When looking at #4192 I found multiple other syncing issue for hellfire quests (see notes)
This PR fixes most of them and #4192 but there are still likely some edge-cases missing.

## Notes
- Defiler Quest is now synced when the first player enters nest level 1
- Little Girl Quest animation is now synced correctly #4192 
- Little Girl Quest quest reward (Amulet) is now synced (can be seen and taken by other players)
- Jersey's Jersey Quest animation is now synced correctly #4192
- Jersey's Jersey Quest is now correctly activated and complete on remote players quest log
- Grave Matters Quest is now synced when talking to gillian and having the cathedral map
- Na-Krul Quest is now activated for all clients (when reading the story book)
- Na-Krul Quest story books are now loaded correctly (are used/open) when reentering the level
- Na-Krul Quest is now also completed for remote players when operating Na-Krul's room the lever
- Hellfire Quests don't disappear from quest-log when completed (they stay in quest log like diablo quests; see #2609)

### CODE REVIEW

**Comment by AJenbo** [comment]
> Jersey's Jersey Quest is now correctly activated and complete on remote players quest log

I wonder if this quest is actually what caused the dsync issues in hive where players are unable to pick up items. Since it spawns the suits on the level when this quest is enabled. That would also explain why we thought it was fixed but got a report that it isn't (testing with the quest off)

**Comment by AJenbo** [comment]
> Na-Krul Quest story books are now loaded correctly (are used/open) when reentering the level

Nice, I actually noticed this last time I tested but forgot to make a note of it :D

**Comment by AJenbo** [comment]
Nice work, a lot of edge cases I wasn't even aware of :)

**Review by AJenbo — APPROVED** [review]

**Comment by obligaron** [comment]
> > Jersey's Jersey Quest is now correctly activated and complete on remote players quest log
> 
> I wonder if this quest is actually what caused the dsync issues in hive where players are unable to pick up items. Since it spawns the suits on the level when this quest is enabled. That would also explain why we thought it was fixed but got a report that it isn't (testing with the quest off)

I don't think this PR will help with item desyncs. But is this issue with the brown suite in 1.4.1 or master? Cause we merged #5484 that fixed bugs related to it.

**Comment by AJenbo** [comment]
it was only reported for 1.4.1. i think your right, if its caused by what im thinking that pr may well have solved it

**Pull request merged**
