### PR TITLE
Update libfmt

### PR DESCRIPTION
**Pull request by glebm**
/cc @azihassan

### CODE REVIEW

**Comment by azihassan** [comment]
Thanks I did something similar in https://github.com/azihassan/devilutionX/pull/9, I'll update the commit hash and clean up the PR to make it easier to bring the fork up to date

**Comment by glebm** [comment]
A few builds are failing with the latest libfmt #4189 so this isn't ready to be merged yet

**Comment by azihassan** [comment]
Ah yes, I just noticed. It's a long shot but could the railing SDKs be enabling FMT_MODULE? It looks like it's overriding FMT_OS in the latest cmake

**Comment by glebm** [comment]
It wasn't quite that. Should be good to go now!

**Comment by glebm** [comment]
This is where you may want to add Dreamcast:

```cmake
if(TARGET_PLATFORM STREQUAL "rg99")
  target_compile_definitions(fmt PUBLIC FMT_BUILTIN_TYPES=0)
endif()
```

This disables precompilation of formatters for built-in types (such as `double`).

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
