### PR TITLE
Fix OOB in DRLG_L5TransFix

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by glebm** [comment]
@AJenbo Did you mean to merge this instead of closing?

**Comment by AJenbo** [comment]
It's not my fault, you put "fix: diasurgical/devilutionX#399" in the commit message :)

**Comment by glebm** [comment]
Oh I didn't know it worked like that across repositories :)

**Comment by AJenbo** [comment]
It's good that you noticed because I think you decided to close it your self :)

**Pull request merged**
