### PR TITLE
Optimize IsTileSafe

### PR DESCRIPTION
**Pull request by glebm**
Add dungeon flags for Fire/Lightning Wall and use them to check if the monster considers the tile safe.

### CODE REVIEW

**Review by StephenCWills — APPROVED** [review]
This looks good to me. Unless we had any alternative thoughts for how to use the remaining dungeon flags.

**Comment by AJenbo** [comment]
On a side note this appears to remove the only use of `DungeonFlag::Missile` so i think we could remove that :)

**Comment by StephenCWills** [comment]
It's used when placing runes, Town Portal, and Guardian as well.

**Comment by AJenbo** [comment]
But is it ever read/tested? I only saw writes/set.

**Comment by StephenCWills** [comment]
Each of these functions reads the flag to avoid placing them in the same tile as another missile.

`AddRune()`

https://github.com/diasurgical/devilutionX/blob/5fa554c2e638fc8631044af10bfd73ad0ab01233/Source/missiles.cpp#L586-L588

`AddTown()`

https://github.com/diasurgical/devilutionX/blob/5fa554c2e638fc8631044af10bfd73ad0ab01233/Source/missiles.cpp#L1917-L1919

`AddGuardian()`

https://github.com/diasurgical/devilutionX/blob/5fa554c2e638fc8631044af10bfd73ad0ab01233/Source/missiles.cpp#L2031-L2033

**Comment by AJenbo** [comment]
Arh I missed that, thanks :)

**Pull request merged**
