### PR TITLE
compile devilutionx as application/x-executable

### PR DESCRIPTION
**Pull request by pkruczynski**
compile devilutionx as application/x-executable instead application/x-sharedlib

### CODE REVIEW

**Comment by AJenbo** [comment]
Besides changing the line endings of the file it looks what you did here was disable  position independent executable, what problem is this supposed to solve?

**Comment by pkruczynski** [comment]
Binary devilutionx compiled with the -no-pie flag will be able to be launched by clicking on it not just from the command line. Sorry for chaneged line endings

**Comment by AJenbo** [comment]
This appears to be an issue with how your OS is detecting the mime type, not an issue with devilutionX. I'm guessing that it is some form of Linux? You should probably just make a .desktop file

**Comment by pkruczynski** [comment]
Yeah, Caja Linux file manager identifies the executable in this way. As it is now, it assigns the application/x-sharedlib mime type, which can be seen e.g. in the details view. I know that you can do it with a .desktop file but why, if such functionality exists. I'm using Linux Mint, based on Debian and Ubuntu, where Caja is main file manager.

**Comment by glebm** [comment]
This is probably best done by setting the `POSITION_INDEPENDENT_CODE` property on the target.

https://cmake.org/cmake/help/v3.10/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE

**Comment by glebm** [comment]
This could probably be fixed by simply upgrading to https://cmake.org/cmake/help/v3.14/policy/CMP0083.html and using `# CMP0083 NEW`

**Comment by AJenbo** [comment]
While nice, I don't see this as critical and in any case this PR is in no state to be merged and hasn't been updated for a considerable amount of time.
My biggest concern with this is that some linkers might see `--no-pie` as an unknown parameter and throw an error, and this would also need to be tested with the Switch build since it is sensitive to the generated result being PIE or not.

**Pull request closed without merging**
