### PR TITLE
Create .cirrus.yml

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by AJenbo** [comment]
Cirrus never started :(

**Comment by sskras** [comment]
What is Cirrus?

**Comment by AJenbo** [comment]
A continues integration platform like CircleCI and Travis. It supports freebsd so i was hoping to set it up to generate builds and test PRs.

**Comment by kraileth** [comment]
Would something like Jenkins on FreeBSD be of any use for Devilution? If so, I could probably provide build jails for 12.0 and 11.2 (both amd64 and i386). I have no experience with CI tools and how to hook anything into them, though. So I'm just asking (would have to look into it first - but that might be a nice opportunity anyway).

**Comment by AJenbo** [comment]
Yes, I would prefer that we have built serveres that automatically build test every update to the project on every supported platform.
My experience with Jenkins is that the cost of maintenance almost outweighs the benefits, especially when compared to some of the services around. But even if you can set something up that we can periodically check then that would be appreciated.

**Pull request closed without merging**
