### PR TITLE
Fix memory leak with audio stream not been released

### PR DESCRIPTION
**Pull request by marty28**
SFileChunk was not been released.

### CODE REVIEW

**Comment by marty28** [comment]
When porting to a platform with limited memory I found talking to townspeople had a slight leak, this is the patch I used to sort it.

PS: Thanks for this great project.

**Comment by AJenbo** [comment]
Thanks for fixing this. What system are you targeting?

**Comment by AJenbo** [comment]
Looks like you are targeting the original Xbox, I almost bought one at a fair for 20$ to do just that. Glad someone else is handling it :)

I see you are using SDL2, and working on porting that also. In case you where not aware we do support SDL1.2 also in case that works out better with the platform.

**Comment by marty28** [comment]
No worries, you're welcome.

Yeah porting to the original Xbox, it's running nicely :) I did the SDL2 port quite a while back before DevilutionX supported SDL 1.2. I'm currently using 1.2 but hope to get it building with both options eventually.

If you're interested in getting a copy for Xbox I can send you a message when I upload my fork with the Xbox changes.

Cheers

**Comment by AJenbo** [comment]
I would be very interested indeed. Glad to hear it runs well.

**Comment by glebm** [comment]
#1200 should help with RAM usage

**Pull request merged**
