### PR TITLE
Revert "Clang-tidy: readability-static-accessed-through-instance"

### PR DESCRIPTION
**Pull request by AJenbo**
This reverts commit 264193276329abffce247929623e2b0bb493401e.

### CODE REVIEW

**Review by julealgon — APPROVED** [review]

**Comment by AJenbo** [comment]
dang, this wasnt it

**Comment by StephenCWills** [comment]
Based on the error message for linux_x86_64, I would check 790f42d and 17e67d2. For 3DS, it's almost certainly acd74cc.

**Comment by AJenbo** [comment]
Turned out to be https://github.com/diasurgical/devilutionX/commit/8c76d45797271dadf86b5ad07748685a0aabab46 and https://github.com/diasurgical/devilutionX/commit/acd74cc0e3b514769fb70596aa6bae9605d02c1e

**Comment by StephenCWills** [comment]
I wonder how I missed that one. I must have made a mistake when querying `tcp_client` history. Glad you were able to find it.

**Pull request closed without merging**
