### PR TITLE
Pop test runner cache

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Review by StephenCWills — APPROVED** [review]
I assume maybe we're still waiting on results from Codecov, but the change looks fine.

**Comment by glebm** [comment]
Looks like the workaround is to set the token
Bug: https://github.com/codecov/codecov-action/issues/837
Example workaround https://github.com/sensuikan1973/pedax/pull/1033

**Comment by AJenbo** [comment]
Pressed all the hidden "auth" buttons in GH and CC. The repo association looks to be fixed now :)

**Comment by AJenbo** [comment]
Test coverage is now 29.10%, so the new demo increased it by about 2% it looks like.

**Pull request closed without merging**
