### PR TITLE
Preview Frame: Disable for towncast

### LINKED ISSUE #4005: Character rotates towards cursor for a fraction of a second when casting a spell in town
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Compiled master - https://github.com/diasurgical/devilutionX/commit/a19d3ad6a2c67d2a1f1ed9a0e27616503e9dbd29

**Describe**
Check gif

**To Reproduce**
Cast spell in town, watch your character spin towards cursor then back like nothing happened :D

**Expected behavior**
No.

**Screenshots**
quickrotate

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #4005

Alternative fix #1980 (my favorite 😜)

### CODE REVIEW

**Comment by yuripourre** [comment]
@obligaron 
Yeah, the alternative is my favorite too!

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
The release window is to short for me to evaluate the alt

**Comment by yuripourre** [comment]
@AJenbo Yes, I didn't mean to push anyone just wanted to show support to @obligaron on this.

**Comment by AJenbo** [comment]
No worries, I just wanted to make clear that I'm not rejecting the alternative by merging this PR :)

**Pull request merged**
