### PR TITLE
Create ja.po

### PR DESCRIPTION
**Pull request by bubio**
added translation to Japanese!

It still needs to be tweaked, but it's mostly translated.

There may be a problem with the handling of line breaks, but the lines are displayed overlapping each other.

image

### CODE REVIEW

**Comment by AJenbo** [comment]
> https://drive.google.com/file/d/1eCVuDsdoU7K2IvVvu8bndzujE446pSrZ/view?usp=sharing

What is this and why does it want my Google account :o

**Comment by bubio** [comment]
Can I access this?

https://drive.google.com/file/d/1eCVuDsdoU7K2IvVvu8bndzujE446pSrZ/view?usp=drivesdk

**Comment by AJenbo** [comment]
You can just post it directly in the comments instead of using Google drive and links

**Comment by glebm** [comment]
あざっす！Don't worry about line breaks and overlap, I'll work on that.

**Pull request merged**
