### PR TITLE
Adaptive (soft) FPS limit

### PR DESCRIPTION
**Pull request by glebm**
Slightly higher frame-rate but hopefully more fluidity

This may still result in skipping 1 frame when the processing between 2 frames is suddenly slow

Refs #467

### CODE REVIEW

**Comment by glebm** [comment]
If we sleep for the remainder of the frame's time, we'll start the next frame too late, because after sleep we still need to process the game loop and do the actual rendering. Unless what you're proposing is equivalent to using the `times` array size to `1`?

**Comment by rsn8887** [comment]
I think this is a solved problem. Just for reference, here's how this is done in Uae4All2 on Vita:
```
(...)
if (drawfinished)
	{
		drawfinished=0;
		unsigned long start = read_processor_time();
		if(start < next_synctime && next_synctime - start > time_per_frame - 1000)
		SDL_Delay(((next_synctime - start) - 1000) / 1000);
		SDL_Flip(prSDLScreen);
		last_synctime = read_processor_time();
		if(last_synctime - next_synctime > time_per_frame - 5000)
			next_synctime = last_synctime + time_per_frame * (1 + prefs_gfx_framerate);
		else
			next_synctime = next_synctime + time_per_frame * (1 + prefs_gfx_framerate);
	}
(...)
```

**Comment by glebm** [comment]
@rsn8887 This seems to hard-code `1000` (1ms?) for what I call `affordance` here. It's a neat solution when frame times are predictable because the hardware and software are fixed. In our case the target hardware is unknown, and we want to balance avoiding frame drops with reducing CPU utilization.

**Comment by mmaret** [comment]
Shall this be done only if vsync are not supported ?
I don't really know about SDL, but SDL_GetHint(SDL_HINT_RENDER_VSYNC); may help to know it ?

**Comment by glebm** [comment]
@mmaret This is already done only when we're not using renderer. Renderer should have vsync by default

**Comment by AJenbo** [comment]
Ok so here is what I'm suggesting we handle the delay for when there is no render, compared to how it works with V-sync:
image
By measuring the time at the previous frame end, by the time we call SDL_Flip we know how long processing took and thus how long we should delay things before starting the process of the next frame, even if the frame turns out to be significantly longer or shorter it will simply have a shorter sleep/longer sleep. There is a chance that the sleep interval might roll across the v-blank line but since `refreshDelay` is rounded down is should mostly cause a slightly higher FPS then refresh rate (note `SDL_Wait` may take longer than asked for if other tasks are hugging the system).

This might actually be achievable by simply calling `SDL_Delay(SDL_GetTicks() % refreshDelay);` right after `SDL_Flip`/`SDL_UpdateWindowSurface`. The benefit here is that it would always sync up to the fixed interval even if the application unexpectedly skipped a frame (system hang, long render time etc) so it should give a very consistent result.

Because V-sync waits for V-blank the frame next from is rendered just after the current one gets pushed to the screen, only game logic and input handling is going before it. This means that the image is actually fairly old once it gets displayed. This means that the non-v-synced mode might actually have a slightly lower response delay.

**Comment by AJenbo** [comment]
`SDL_Delay(SDL_GetTicks() % refreshDelay);` was definitely an improvement over the previous one I did, and also much simpler, so I went ahead and pushed it to master. Feel free to update this PR if it can be made even better :)

**Comment by glebm** [comment]
Oh I see, so the image is actually 1 frame behind the game state most of the time. Sounds good!

**Pull request closed without merging**
