### PR TITLE
paths.cpp: Remove `AppPath`

### PR DESCRIPTION
**Pull request by glebm**
It was redundant.

### CODE REVIEW

**Review by StephenCWills — APPROVED** [review]

**Comment by glebm** [comment]
@AJenbo looks like "testflow" is stuck

**Comment by AJenbo** [comment]
This breaks the scenario where someone has there MPQs in a non default folder specified by `--data-dir` and do not have `smpq` installed :(

@obligaron will this be an issue for you?

**Comment by glebm** [comment]
@AJenbo It makes that scenario more sensible IMO because `assets/` folder will be looked for in the data directory instead of next to the binary.

**Comment by glebm** [comment]
We could add an explicit `--assets-dir` flag though, if there is a scenario I'm not thinking of.

**Comment by glebm** [comment]
@AJenbo Sorry for merging before getting feedback btw. I saw that it got stuck and put it on auto-merge. But then it got unstuck

**Comment by StephenCWills** [comment]
Oops, I didn't think about the case where `BasePath` is set independently. I remember now why this distinction was needed.

**Comment by AJenbo** [comment]
> @AJenbo Sorry for merging before getting feedback btw. I saw that it got stuck and put it on auto-merge. But then it got unstuck

No worries :)

**Pull request merged**
