### PR TITLE
Update Windows_MinGW_x64.yml

### PR DESCRIPTION
**Pull request by gas4811**

### CODE REVIEW

**Comment by StephenCWills** [comment]
We call it Windows MinGW x64 to differentiate it from Windows MSVC x64.

**Comment by StephenCWills** [comment]
Hm, am I wrong? The GitHub Actions workflow and the badge both say Windows x64...

**Comment by StephenCWills** [comment]
Strangely enough, `README.md` lists `Windows MSVC x64` as `Windows x64` even though the badge doesn't match.

https://github.com/diasurgical/devilutionX/blob/ab601eeb118afd5dcec0d2778bdf997b09436b0d/README.md?plain=1#L55-L57

Best I can figure is that the badge and the workflow name were both updated based on the change in this PR. If so, I find that to be a bit irritating. Maybe someone else knows?

**Comment by StephenCWills** [comment]
> Looks correct when I click the little check badge on master:

I'm looking under the `Actions` tab. Also, the badge is the little graphic on the main page.

image

image

**Comment by DakkJaniels** [comment]
> I'm looking under the `Actions` tab. Also, the badge is the little graphic on the main page.

Yeah I just noticed after I sent that. Weird. So if the readme is updated will the action change? Maybe it should just say MinGW in the badge anyway, since we do that for x86?

**Comment by StephenCWills** [comment]
> Yeah I just noticed after I sent that. Weird. So if the readme is updated will the action change? Maybe it should just say MinGW in the badge anyway, since we do that for x86?

The text in the readme doesn't matter. If you look a bit more carefully, you'll see that the `Windows MSVC x64` workflow is labeled as `Windows x64` in the readme, but the badge doesn't match. Meanwhile, the `Windows MinGW x64` workflow is labeled as itself, but the badge seems to have been updated based on this PR.

That's not to say we shouldn't update the text in the readme to match the badge, but that's not what determines the text in the badge.

**Pull request closed without merging**
