### PR TITLE
Small translation edits at ru.po

### PR DESCRIPTION
**Pull request by SergBrNord**
1. Minor edits to the game text.
2. Small edits to the settings menu.

Is everything okay at this time? =)

P.S. What mean "NW" at 993 string "Another ability (NW)" and what a new string was added (2043)?

### CODE REVIEW

**Comment by AJenbo** [comment]
> P.S. What mean "NW" at 993 string "Another ability (NW)" and what a new string was added (2043)?

993 and 2043 are just the text counter on your screen, we don't know what that refers to :)

`"Another ability (NW)" ` isn't important, it's just for broken items, it should never happen.

**Comment by AJenbo** [comment]
@tsunamistate do you want to review this :)

**Review by tsunamistate — APPROVED** [review]
Translation LGTM
@AJenbo I assume you can untangle this mess?
Lots of unrelated commits

@SergBrNord you really need to learn some git-fu. I personally recommend Atlassian tutorials, they really helped me during my growing pains of learning git. They even have Russian version: https://www.atlassian.com/ru/git/tutorials

**Comment by SergBrNord** [comment]
> @SergBrNord you really need to learn some git-fu. I personally recommend Atlassian tutorials, they really helped me during my growing pains of learning git. They even have Russian version: https://www.atlassian.com/ru/git/tutorials

I'm scared to make the next 3 edits after this...

**Comment by tsunamistate** [comment]
@SergBrNord your mistake is making changes on `master` branch
You should look into making a branch and making changes there: https://www.atlassian.com/ru/git/tutorials/using-branches

**Comment by SergBrNord** [comment]
> @SergBrNord your mistake is making changes on branch You should look into making a branch and making changes there: https://www.atlassian.com/ru/git/tutorials/using-branches`master`

But every time I just follow the instructions and use GitHub Desktop...ヽ(°□° )ノ

**Comment by tsunamistate** [comment]
@SergBrNord in that case, here are the docs how to work with branches in Github Desktop: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches

**Pull request merged**
