### PR TITLE
Don't draw Level Up Icon if quest log opened

### PR DESCRIPTION
**Pull request by de4me**
LevelUpIcon

### CODE REVIEW

**Comment by qndel** [comment]
this commit contains more than the title suggests ;) get rid of it :P

**Comment by de4me** [comment]
> this commit contains more than the title suggests ;) get rid of it :P
> you duplicated your #425,
> switch to a new branch for making PR for new stuff

Hi, this commit from new branch, but old commit i push to main.
Sorry, i am new in git. How i can fix it?

**Comment by AJenbo** [comment]
You need reset your history before creating a branch or specify here in history you want your branch.

**Comment by qndel** [comment]
`git remote add upstream https://github.com/diasurgical/devilutionX.git`
`git fetch --all -p`
`git checkout -b mysupercoolbranchname upstream/master`
will do the trick I think

**Pull request closed without merging**
