### PR TITLE
Do not prefill hero name for on-screen keyboard

### LINKED ISSUE #1414: [Vita] Can't rename characters
Naming characters is impossible on new version. You get the default name but you cannot delete it, the input shows empty while the name of the character "Kharazim" stays, and if you add anymore letters it says "Kharazim" and then w/e you input.
Didn't happen on older versions.

### PR DESCRIPTION
**Pull request by glebm**
Refs #1414

Related: https://github.com/diasurgical/devilutionX/pull/1442

/cc @isage

### CODE REVIEW

**Comment by AJenbo** [comment]
Should we overwrite this on switch as we use it's keyboard directly, or is it better to be more vanilla and expect people to fully enter a name?

**Comment by glebm** [comment]
Good point, we should probably only do this on platforms where we don't have the ability to set the initial text

**Comment by isage** [comment]
The only two platforms that require that are switch and vita, afaik.
That shouldn't be required on vita after #1442
Dunno about switch, does it have same issue?

**Comment by glebm** [comment]
Any SDL2 platform with OSK and no custom keyboard stuff on our side would require this

**Comment by isage** [comment]
Officially, only 4 sdl platforms have OSK: android, ios, winrt and vita. Of those 4, only vita doesn't send keypresses from OSK, and has instead separate text input.

**Comment by glebm** [comment]
This ifdef is not about that, it's about not initializing the value with the prefilled name, because OSK always starts with the empty string (editing not supported)

So if you didn't have this ifdef, the OSK would only be able to append to a pre-generated name. So we can't prefill the name in this case.

**Comment by glebm** [comment]
This PR is incomplete in that we should *not* do this on platforms that do support the starting string for the OSK but I'm waiting for your PR before fixing that

**Comment by glebm** [comment]
Ah, I think I see what you're saying: The other platforms allow sending backspace from the OSK and the actual DiabloUI input field is visible while they do that?

**Comment by isage** [comment]
Yeah

**Comment by glebm** [comment]
OK, closing this then :+1:

**Pull request closed without merging**
