### PR TITLE
Smart pointers for TMegaPkt handling

### PR DESCRIPTION
**Pull request by vlolteanu**
This needs testing! It touches the multiplayer code

### CODE REVIEW

**Comment by AJenbo** [comment]
```
C:\projects\devilutionx\Source\msg.cpp(72,39): error C2070: 'uint8_t [0]': illegal sizeof operand [C:\projects\devilutionx\devilutionx.vcxproj]
C:\projects\devilutionx\Source\msg.cpp(106,53): error C2070: 'uint8_t [0]': illegal sizeof operand [C:\projects\devilutionx\devilutionx.vcxproj]
```

**Review by AJenbo — APPROVED** [review]

**Comment by vlolteanu** [comment]
Thanks for the approval, but this is still untested. Please don't merge it yet.

**Comment by AJenbo** [comment]
ok, make sure to create it as a draft if its not ready to merge

**Comment by AJenbo** [comment]
... ok i guess closing it works too

**Pull request closed without merging**
