### PR TITLE
Add Ubuntu PPA repos to README.md

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by AJenbo** [comment]
Could you grate some one from the Diasurgical team access to the team on Launchpad (i use the same name there as on GitHub)?

**Comment by muzena** [comment]
> Could you grate some one from the Diasurgical team access to the team on Launchpad (i use the same name there as on GitHub)?


Done.

**Comment by AJenbo** [comment]
Thanks, looked a bit a things a have a few issues I would like us to address.
- We are building for 360z and PowerPC64 CPUs but have we tested if this works?
- The builds fail to pick up the git tag and so the version is missing from the build (see the main menu).
- There is no build for Ubuntu 16.04 or 14.04 is this possible?
- It makes the readme a bit more cluttered, though this is somewhat outweighed by this installation method being simpler and adding a proper icon.

**Comment by muzena** [comment]
> We are building for 360z and PowerPC64 CPUs but have we tested if this works

Intention of this PPA is for testing, isn't it?
You can disable/enable architecture/processor building [here](https://code.launchpad.net/~devilutionx/+archive/ubuntu/dev/+edit)

> The builds fail to pick up the git tag and so the version is missing from the build (see the main menu).

I don't understand this. 
devilutionx - 1.0.0+git920-7f699db~ubuntu16.04.1
7f699db is last [commit](https://git.launchpad.net/~devilutionx/+git/devilutionX/commit/)

> There is no build for Ubuntu 16.04 or 14.04 is this possible?

I think it's too many dependencies issue, see this [xenial](https://launchpadlibrarian.net/461955698/buildlog_ubuntu-xenial-amd64.devilutionx_1.0.0+git920-7f699db~ubuntu16.04.1_BUILDING.txt.gz)
[trusty-precise](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-git)  Click on Failed to build -> buildlog to see details, 
They are too old releases and have too many problems with build dependencies

> It makes the readme a bit more cluttered, though this is somewhat outweighed by this installation method being simpler and adding a proper icon.

If this commit cluttered readme, can you add this in README.md or maybe id better to include in wiki sections for building and inastalling?

**Comment by AJenbo** [comment]
> > The builds fail to pick up the git tag and so the version is missing from the build (see the main menu).
> 
> I don't understand this.
> devilutionx - 1.0.0+git920-7f699db~ubuntu16.04.1
> [7f699db](https://github.com/diasurgical/devilutionX/commit/7f699dbad2a7f17728eb3f52743c93955dffe578) is last [commit](https://git.launchpad.net/~devilutionx/+git/devilutionX/commit/)

That's the package, but the application itself is missing the version, see the main menu and or press `v` ingame
billede

billede

This will eventually lead to multiplayer failing when checking for version compatability, so should defautly be fixed before we lable it as official via the readme etc.

**Comment by AJenbo** [comment]
> > We are building for 360z and PowerPC64 CPUs but have we tested if this works
> 
> Intention of this PPA is for testing, isn't it?

On of them is called stable, so that doesn't make me things it's for testing :)

> > There is no build for Ubuntu 16.04 or 14.04 is this possible?
> 
> I think it's too many dependencies issue, see this [xenial](https://launchpadlibrarian.net/461955698/buildlog_ubuntu-xenial-amd64.devilutionx_1.0.0+git920-7f699db~ubuntu16.04.1_BUILDING.txt.gz)
> [trusty-precise](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-git) Click on Failed to build -> buildlog to see details,
> They are too old releases and have too many problems with build dependencies

Updating CMake and libsodium on the build server should be enough to solve that, but we can always look in to that at a later point.

**Comment by muzena** [comment]
I disabled in [stable PPA](https://launchpad.net/~devilutionx/+archive/ubuntu/stable/+edit) PowerPC (powerpc), PowerPC64 Little-Endian (ppc64el), IBM System z (s390x) is that ok?

> That's the package, but the application itself is missing the version, see the main menu and or press v ingame

I don't understand how this works is this visible in build log file, like error or somewhere else I might see how works this versioning mechanism?

> build for Ubuntu 16.04 or 14.04

I will see this on Sunday, I think for Ubuntu 16.04 might be enough to change debhelper version
Ubuntu 14.04 I think there is missing  [libsodium packages](https://packages.ubuntu.com/search?keywords=libsodium-dev).

**Comment by AJenbo** [comment]
You should see an error in the cmake part of the build log about the missing version.

Powerpc will be supported in the next release, but only for 16.04

**Comment by AJenbo** [comment]
Specifically, this is the command that is used to find the current version when building a release:
https://github.com/diasurgical/devilutionX/blob/master/CMake/git.cmake#L3

**Comment by AJenbo** [comment]
PowerPC is now supported on the latest master :D

**Comment by muzena** [comment]
Trusty is too old some package dependencies even don't exsist in trusty. 
I'm trying now xenial build, but this is impossible, it's dependencies hell, I upload one dependency next dependency need a few more dependency ....
I try this before one year for Subtitle Composer, and I give up to much dependencies.
I found this [dependencies xenial PPA](https://launchpad.net/~savoury1/+archive/ubuntu/build-tools) but it only have amd64 and i386 arhitecture. I add this PPA for dependencies but also failed to build 'broken dependencies'.

**Comment by AJenbo** [comment]
Ok thanks for trying, to bad there isn't a backports archive like for Debian stretch (what we use for all other builds)

**Comment by muzena** [comment]
I'm trying to fix version in menu, when I build localy on PC version is showing, but in PPA repo version is missing in menu and in game.
I don't understand that, maybe some dependencies missing?

**Comment by AJenbo** [comment]
It depends on `git` and oviously the .git folder must still be present. Do you know what the build server does when fetching the code? Do you know if the build server has git?

**Comment by muzena** [comment]
Problem is in uploading [code to PPA](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/games/+sourcefiles/devilutionx/1.0.0+git936-3ae1dc3-202001280142~ubuntu18.04.1/devilutionx_1.0.0+git936-3ae1dc3-202001280142~ubuntu18.04.1.tar.xz) for building, I don't get it why .git dir missing.

**Comment by AJenbo** [comment]
We could make a workaround if there is some environment variable or other accessible value (file or CMake parameter) that holds the version being build.

**Comment by muzena** [comment]
I try git cloning add in rules file, even direct git cloning is cloned without .git dir see[ build log](https://launchpadlibrarian.net/462625327/buildlog_ubuntu-bionic-amd64.devilutionx_1.0.0+git936-3ae1dc3-202001291455~ubuntu18.04.1_BUILDING.txt.gz) at the end in lines where is commands:
cd devilutionX
ls -a

I think only way what is left is to implement somehow to extract the version outside of the .git directory.

**Comment by AJenbo** [comment]
Just to clarify we do not use the .git folder our self, we use git commands, but I don't see how git can work with out the .git folder present. If you can run git commands then there shouldn't be a problem. The command to test is: `git describe --abbrev=0 --tags`

**Comment by muzena** [comment]
Yes, that is the problem, I try before configuring and building starts clone devilutionX then from cloned dir copy .git to 'root' folder of building, one folder up, but even that cloning is cloned without .git directory, probably is package building system on that way configured.
I don't know, the only thing left is to ask the [question on launchpad](https://answers.launchpad.net/launchpad/+addquestion)

**Comment by muzena** [comment]
@AJenbo 
I think that is only solution to get version from github api, to make some script or grabber
this terminal command grabs devilutionX version and commit:

`(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/diasurgical/devilutionX/git/refs/tags | jq -r '.[0].ref' | sed 's/^.\{10\}//' ; echo "-" ; curl -s  https://api.github.com/repos/diasurgical/devilutionX/git/refs/heads/master | jshon -e object | jshon -e sha -u | cut -c1-8) | tr -d '\n'`

**Comment by AJenbo** [comment]
oh thats an interesting way to do it, but i'm not totally against it as a workaround for how launchpads build server works.

**Comment by muzena** [comment]
@AJenbo 
I finally found a way to extract version and last git commit from the name of build directory in launchpad.
This extraction from github api work when building locally on PC, but in launchpad dosen't work.
This is build directory path in launchpad:
/--BUILDDIR--/devilutionx-1.0.1+git1144-f66339a
I extract version and commit with command:
pwd | tail -c 22 | cut -c-5        -version
pwd | tail -c 8                         -commit
This is [build log](https://launchpadlibrarian.net/485166941/buildlog_ubuntu-bionic-amd64.devilutionx_1.0.1+git1144-f66339a-202006201937~ubuntu18.04.1_BUILDING.txt.gz)
#753

**Pull request merged**
