### PR TITLE
DoHealOther converted to use GenerateRndSum

### PR DESCRIPTION
**Pull request by ikonomov**
DoHealOther spell function converted to use GenerateRndSum as the other spells

### CODE REVIEW

**Comment by StephenCWills** [comment]
`GenerateRndSum()` is defined in the anonymous namespace in `missiles.cpp`, so it won't be available to `spells.cpp`. I would recommend moving the function to `engine/random.cpp`, then declare it in `engine/random.hpp` so it can be used in both `missiles.cpp` and `spells.cpp`.

**Comment by AJenbo** [comment]
I think he still just edits things on the github website rather then use git locally.

**Comment by ikonomov** [comment]
> I think he still just edits things on the github website rather then use git locally.

I tried using Git in Windows and found it more intimidating :(  I guess I have to be more persistent, will give it another shot.

**Comment by AJenbo** [comment]
Did you try using GitHub Desktop or similar GUI tools?

**Pull request closed without merging**
