### PR TITLE
DiabloUI: Implement UI "widgets" for dialogs

### PR DESCRIPTION
**Pull request by glebm**
* Adds new `UiButton` and `UiText` components needed for the dialog.
* Implements the "OK" dialog and calls it in a couple of places.

Currently the dialog simply accepts a list of items to render as "background" and takes over the event loop.

A lot more work remains:

* Only the OK dialog has been implemented.
* The new dialog is only called in a couple of places.
* `MessageBoxA` still uses the SDL dialog.
* ~~The new `UiText` component doesn't do word-wrapping yet.~~

**Updated screenshots**

Screenshot from 2019-10-02 19-30-56

Screenshot from 2019-10-02 21-30-50

Partially addresses #303

### CODE REVIEW

**Comment by AJenbo** [comment]
If you move the text in the small dialog down by 11px and the button to the left by 1px then this is pixel perfect :tada:

**Comment by AJenbo** [comment]
P. S. I think you can see an example of how you can word wrap ttf fonts in credit.cpp

**Comment by glebm** [comment]
> If you move the text in the small dialog down by 11px and the button to the left by 1px then this is pixel perfect tada

Thanks, done!

> P. S. I think you can see an example of how you can word wrap ttf fonts in credit.cpp

Unfortunately that one is pre-wrapped

**Comment by glebm** [comment]
New screenshots:

Screenshot from 2019-10-02 19-30-56
Screenshot from 2019-10-02 19-36-02

**Comment by glebm** [comment]
Implemented wrapping! It's not pretty!

Based on a mix of SDL_ttf 2.0.12 `TTF_RenderUTF8_Blended_Wrapped` and SDL_ttf master `TTF_RenderUTF8_Solid_Wrapped` implementations.

Text centering within a line not implemented yet.

Screenshot from 2019-10-02 21-08-24

**Comment by glebm** [comment]
Text centering now implemented too:

Screenshot from 2019-10-02 21-20-21

**Comment by AJenbo** [comment]
That was fast :) The only thing I notice is that line spacing is a bit wide, should be about 9 px less

**Comment by glebm** [comment]
Good catch! I think I know how to fix that :)

**Comment by glebm** [comment]
Fixed and screenshot updated in the PR description.
If you want to tweak it a bit more, see https://github.com/diasurgical/devilutionX/pull/312/commits/b868bff7bd74f5e10d4b33e38d8d09284d580589

**Comment by AJenbo** [comment]
Looks excellent

**Pull request merged**
