### PR TITLE
Bump multiplayer to 16 players

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by majek** [comment]
As I mentioned in another place, there is an issue with town portals with many players

**Comment by perchrh** [comment]
This relates to #543.

**Comment by mazeya** [comment]
I am new to github :( I just wanted to say Please Dont, Allow Items to drop on ground upon death multiplayer!

**Comment by qndel** [comment]
@AJenbo any reason for this to still be a draft? looks good to me

**Comment by AJenbo** [comment]
There is an OOB in when chatting as the array for player text color is only 4 long.

**Comment by zamundanet** [comment]
Guys im a new user , how to unlock to 16 players ? I see that files are edited but i dont have those file in the archive of the latest release. Sorry im not a coder.

**Comment by AJenbo** [comment]
You would need to compile it, compiling is the process of turning code in to an exe (assuming you are on Windows)

**Comment by zamundanet** [comment]
Ajenbo , yes i am on windows and i just texted in the main discord chat. Can you guys guide me in how to do it for me and my friends ?

**Comment by AJenbo** [comment]
Yes, we just did so in the Discord chat.

**Pull request closed without merging**
