### PR TITLE
CMake: Use FindPatch

### PR DESCRIPTION
**Pull request by glebm**
CMake's built-in FindPatch will look in the Git installation directory on Windows, eliminating the need for Windows users to modify PATH.

See https://github.com/Kitware/CMake/blob/master/Modules/FindPatch.cmake

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Wonder what GitHub will do since I already applied the formatting fix :thinking:

**Comment by AJenbo** [comment]
Does this replace #5317 ?

**Comment by glebm** [comment]
Yeah, #5317 shouldn't be needed with this

**Comment by tsunamistate** [comment]
Fix confirmed, CMake finds the `patch` utility without modifying PATH on Windows MSVC

**Pull request merged**
