### PR TITLE
Romanian locale update

### PR DESCRIPTION
**Pull request by licaon-kter**
+Android app

### CODE REVIEW

**Comment by AJenbo** [comment]
@licaon-kter have you had time to work any further on the translation? If so it would be good if you can send in any updates as we are preparing for the next release :)

**Comment by licaon-kter** [comment]
I'll try, thanks for the headsup

**Comment by AJenbo** [comment]
There's going to be and update to DevilutionX soon so now would be a good time to update the translation if you have time :)

**Comment by licaon-kter** [comment]
Might take a look after next week, thanks for the heads up.

**Pull request merged**
