### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StephenCWills**
This is kind of an experiment to see if the name of the `Windows MinGW x64` workflow gets fixed.

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
I like experiments, especially if they involve dry ice 'n' stuff.

P.s. CI won't run when only .md files are updated.

**Comment by AJenbo** [comment]
P.p.s. the name in the CI is Windows x64, which probably does not come from the readme: https://github.com/diasurgical/devilutionX/actions/workflows/Windows_MinGW_x64.yml

**Comment by StephenCWills** [comment]
Yeah, and CI didn't run on #6961 either. The name wasn't updated by this change, which leaves a question in the air. Is it sufficient to get CI to run, or do we have to make a change to the yml?

**Comment by AJenbo** [comment]
Even more interesting if you look at the individual run the name is corrected: https://github.com/diasurgical/devilutionX/actions/runs/7880221212

I guess it just keeps which ever name it had originally.

**Comment by DakkJaniels** [comment]
> Even more interesting if you look at the individual run the name is corrected: https://github.com/diasurgical/devilutionX/actions/runs/7880221212
> 
> I guess it just keeps which ever name it had originally.

Not sure that's the case, the x86 is showing up correctly and it was changed when the x64 one was modified:

image

**Pull request merged**
