### PR TITLE
Enable CMP0092

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by julealgon** [comment]
What is this?

**Comment by AJenbo** [comment]
Easy to google: https://cmake.org/cmake/help/git-stage/policy/CMP0092.html

**Comment by julealgon** [comment]
> Easy to google: https://cmake.org/cmake/help/git-stage/policy/CMP0092.html

I obviously didn't google it on purpose. The question was rethorical, since the PR/commit title should provide the detail without needing one to google things.

**Comment by AJenbo** [comment]
That wasn't obvious from your message.

**Pull request merged**
