### PR TITLE
[Android] Fix error when turning on upscaling in the settings menu

### LINKED ISSUE #3708: [android] Multiple renderers when reenabling upscaling
Switch upscalling off, then on:

image

### PR DESCRIPTION
**Pull request by StephenCWills**
This is a hack that manipulates the window data that SDL uses internally to track the renderer associated with the window. It's the only way I could find to make toggling the upscale option work on Android.

**Other things I tried:**
* Simply destroy the internal renderer before creating our renderer. Unfortunately, the SDL internals also keep track of the "window texture" so there's no way to force it to recreate this renderer without a similar (but probably worse) hack.
* Recreate the whole window. This freezes up the display, and I couldn't figure out how to get the display to start updating again after recreating the window.

This resolves #3708

### CODE REVIEW

**Comment by AJenbo** [comment]
I guess the alternative is to not allow switching off upscaling on Android

**Comment by StephenCWills** [comment]
> I guess the alternative is to not allow switching off upscaling on Android

I considered that too. Android may not be the only platform with this issue, but even so.. I guess we can just lump them all together as platforms that can't toggle upscale in-game.

**Comment by glebm** [comment]
Perhaps this should be fixed in SDL?

**Comment by StephenCWills** [comment]
> Perhaps this should be fixed in SDL?

I'm going back and forth on this, however I think it would be best to simply disable/hide the setting on Android. Essentially, I question the value of providing the option to disable upscaling on a system that is just going to use the render API under the covers anyway. It should be possible to simply fiddle with the other settings to get an equivalent result. FYI, the actual effect of `Upscale=0` on my phone is the same as changing the game's resolution to match that of my phone's screen.

**Pull request closed without merging**
