### PR TITLE
experimental xbrz filtering

### PR DESCRIPTION
**Pull request by Chance4us**
So that we no longer see the void in the galaxy this is the follow up to  #696.
It crashes e.g. when upscale = 0 in diablo.ini.
The main menu is now scaled as well.
The cutscenes are now scaled but hardcoded for 16:9 display.
The credits are not displayed correctly.

Images for comparison:
pos1-town-pepin
pos1-xbrz-town-pepin
pos1-town-char-inv-unique
pos1-xbrz-town-char-inv-unique
pos1-town-pepin-inv
pos1-xbrz-town-pepin-inv
butcher
xrbz-butcher
pos2-dungeon
pos2-xbrz-dungeon
pos2-dungeon-inv
pos2-xbrz-dungeon-inv
pos3-caves
pos3-xbrz-caves
warlord
xbrz-warlord

### CODE REVIEW

**Comment by AJenbo** [comment]
Nice with all the comparisons. It does show a noticeable improvement, especially to the new automap and various outlines, but also to the equipment and a few other things. But it appears to not play nicely with the old transparency. But hopefully, that will get replaced before long.

image

**Comment by Chance4us** [comment]
Nice that you all like it.
By the way,  the transparency probably can be improved by additional parameters of xbrz.

**Comment by Chance4us** [comment]
Now I uploaded and modified the code and the parameters a little bit.
The transparency now looks much better.

For comparison before changes:
before

Transparency after the changes:

after

**Comment by Chance4us** [comment]
Now the graphic settings of xbrz and the transparency are almost perfect.

**Comment by AJenbo** [comment]
Looks like it also better maintains brightnes now.

**Comment by cbswe88** [comment]
I can't seem to access this branch in the github desktop client. Is there any way to do this?

**Comment by AJenbo** [comment]
@cbswe88 I have squashed the branch into one called xbrz on the main repo so that you can look at it there: https://github.com/diasurgical/devilutionX/pull/866

**Comment by cbswe88** [comment]
Perfect, thank you!
Will try to see if I can merge master into the xbrz locally to also get the latest changes. Not too many merge conflicts it seems!

**Comment by cbswe88** [comment]
I think this feature is really great. Ideally it could be added as a config. Something activated by editing diablo.ini, or a special launch menu accessible by holding a key while launching.
Got it working even after merging from master and resolving the merge conflicts

**Comment by AJenbo** [comment]
please post a prwith it

**Pull request merged**
