### PR TITLE
CI: Manually build & install SMPQ on Vita CI

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by AJenbo** [comment]
At some point it might be worth spinning this of in to it's own repo where we can do re release build that can then be fetched by the Vita builder, to avoid having to build it multiple times, and maybe to the benefit of others

**Comment by glebm** [comment]
> At some point it might be worth spinning this of in to it's own repo where we can do re release build that can then be fetched by the Vita builder, to avoid having to build it multiple times, and maybe to the benefit of others

That is literally what a package is 😂

**Comment by AJenbo** [comment]
Well i felt it was more polite to write a few more words then that :)

**Comment by AJenbo** [comment]
looks like success :taco:

**Review by AJenbo — APPROVED** [review]
Thank! Now we get to enjoy auto-merges again :)

**Pull request merged**
