### PR TITLE
Chore: update translations template.

### PR DESCRIPTION
**Pull request by nelchael**
Updating the translations template, it's updated to latest source code at `master` branch.

**Note**: there are no translation changes in the `pl_PL.po`, just syncing with the template, so next PRs that actually do update translations are smaller and easier to review.

### CODE REVIEW

**Comment by AJenbo** [comment]
Sorry, I'm going to close this. Since the PO files contain the line numbers any change will quickly cause large portions of this file to become out of date, so it makes more sens to wait until a translator is working on the translation. If they happen to commit it as a single commit it is easy to go back and rebase it using mixed reset.

It's also a bit odd to only update the Polish translation file and none of the other ones.

If your intent was to work on updating the Polish translation then please do so in a single PR using multiple commits.

**Comment by nelchael** [comment]
Sounds good, thank you @AJenbo! I'll open a new PR with just the pl_PL updates.

**Comment by AJenbo** [comment]
Nice! It's always good to see the translations be maintained :)

**Comment by nelchael** [comment]
Couldn't agree more! The updates are in #6814.

**Pull request closed without merging**
