### PR TITLE
macOS x86 build

### PR DESCRIPTION
**Pull request by BennyFranco**
- Adding 3rd parties needed to build the project
- Creating Xcode projects and configurations
- Updating **.travis.yml** file to build a bash script
- Prepare project to build a bundle app for macOS

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
This is great stuff @BennyFranco!

`+2,817,268 −547`

Is the size of the PR mostly caused by adding dependencies source code? Would it be possible to split those somehow? I wasn't even able to look at the PR diff because of how much time it takes to load and render the diff

**Comment by BennyFranco** [comment]
Yes, we're working on that, you can reject this PR if you want and we can open a new one when we finish this change

**Comment by AJenbo** [comment]
We are doing a similar thing for the windows port, once that is done we can share some of it for the Mac port.

**Comment by BennyFranco** [comment]
This isn't need it anymore

**Pull request closed without merging**
