### PR TITLE
Update Polish translations.

### PR DESCRIPTION
**Pull request by nelchael**
👋 Please review the following changes for Polish translations.

Synchronizing the `pl.po` file -- this is the large portion of this pull request:
 * 650f3c6e Sync pl.po to source code.

Different small updates here and there:
 * f572b243 Update store label translations.
 * b82d6c3a Consistent translations for "armor" and "armor class".
 * fa29ba97 Chat log translations.
 * 642c1743 Quick spell translations.
 * f9648a9d Inventory sorting translations.
 * ad9fb102 Debug commands translations.
 * 7adb2529 Player inspection translations.
 * 8ffaf347 Button combo bindings translation.
 * 4cf2505d Change "żywotność" to "witalność" so it flows better in character stats screen.
 * a3af9495 Fix "U.S. Sales" translation.
 * b3fe044d Improve the validate_translations.py script.
 * 78a018ba Shorten Experience translation to avoid overflowing.

This is potentially controversial -- took the liberty of changing how the resists are labeled on the character screen, in my opinion it looks better, but I'm not going to die on this hill as there seems to be no perfect way of doing that 😞
 * 9d511f70 Different take on resists translation on character screen.

Some of the above updates are visible in this screenshot comparison:

**Before:**
before

**After:**
after

### CODE REVIEW

**Comment by qndel** [comment]
looks ok, have you checked that new text doesn't go out of bounds if it's longer than previous one? Also not sure about python script, any reason for moving from python to python3?

**Comment by nelchael** [comment]
Sadly the last letter from "Odp. na błyskawice" leaks to the third line. What's your opinion on using "Odp. na błysk." instead to prevent this?

Regarding the Python changes: `python` was usually used for Python 2 which is long time dead now, hence the change to `python3`.

**Comment by nelchael** [comment]
Here's a version with `Odp. na błysk.` for the lightning resistance so it doesn't overflow.

shorter-lightning-res

**Comment by nelchael** [comment]
Now that you've mentioned it... fixing also the "Experience" translation leaking onto next line (also final "e") in 78a018ba.

exp-short

**Comment by qndel** [comment]
imo anything is better than having a single letter in a new line 😅

**Review by qndel — APPROVED** [review]

**Pull request merged**
