### PR TITLE
Fix OOB in M_CheckEFlag

### PR DESCRIPTION
**Pull request by glebm**
I'm not entirely sure what `_meflag` is but this seems like the right fix. Thoguhts?

### CODE REVIEW

**Comment by glebm** [comment]
Needs further work

**Comment by glebm** [comment]
OK now

**Comment by AJenbo** [comment]
Should it be reopened?

**Comment by glebm** [comment]
I opened #404 instead, can't reopen a closed PR after force-pushing into the branch

**Pull request closed without merging**
