### PR TITLE
♻️ Move 'HeroClass::ClassCount' to external tracking template

### PR DESCRIPTION
**Pull request by julealgon**
This eliminates the problem where the compiler complains we are not handling all enumeration values by moving the "hack" counting member into somewhere else external to the enum.

### CODE REVIEW

**Comment by julealgon** [comment]
Depends on #1469

**Comment by AJenbo** [comment]
would prefer getting the size from hero names as suggested in #1469 so we dont have to do all this casting

**Comment by julealgon** [comment]
@AJenbo check last commit again for the approach were we don't need to define the template specialization for each enum.

It uses a special `LAST` member in the enum.

**Comment by AJenbo** [comment]
Damn, so many enum PRs going on I'm getting super confused what is what here :D

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Merged manually via https://github.com/diasurgical/devilutionX/commit/8cf972e8439d8fffd13141a58d06128a9707f857

**Pull request closed without merging**
