### PR TITLE
prevent quest items to be sold at the smith

### PR DESCRIPTION
**Pull request by pionere**

### CODE REVIEW

**Comment by AJenbo** [comment]
Could you rebase this fix now that HF has been merged :)

**Comment by qndel** [comment]
what quest items could be sold to griswold? ; o

**Comment by pionere** [comment]
> what quest items could be sold to griswold? ; o

and here I thought devx aim is to be a modding base...

**Comment by qndel** [comment]
1. this doesn't even compile, you are comparing ItemStruct with an int
2. this wouldn't let you sell items like leoric's crown / butcher's cleaver etc.

**Pull request closed without merging**
