### PR TITLE
Reduce 12px font space width from 9px to 5px

### LINKED ISSUE #4397: Space too wide for the 12px font
The space is somewhat too wide for the 12px font.

This results in some store items not fitting on a single line.

Example by @ikonomov:

store screenshot

### PR DESCRIPTION
**Pull request by glebm**
This looks better and makes more text fit for things like the character panel and store item descriptions

9 (original), 6, 5 (this), 4 px comparison, courtesy of @ikonomov:

gif

Fixes #4397

Before | After
---|---
image | image

### CODE REVIEW

**Comment by AJenbo** [comment]
going from 9 to 4 seams aggressive, can you show a comparison to the original?

**Comment by glebm** [comment]
The original has fairly wide spaces, here is a screenshot from GOG:

Screenshot from GOG

The original font rendering does not look good to me though!

**Comment by glebm** [comment]
Updated to 5px following the discussion on Discord

**Comment by ephphatha** [comment]
5px looks fine imo as a compromise between Diablos wide spaces and the typical width of a space in a non-monospaced font. This ends up being a bit over half an em (lowercase m is 9px wide in the 12px font unless I'm misreading the bin) when the typical width of a space is < ~.4 em

**Comment by AJenbo** [comment]
em dash is 10px, which is maybe a better measurement of the font size :)

**Pull request merged**
