### PR TITLE
Correct Spanish Translation

### PR DESCRIPTION
**Pull request by hiperiondev**
Correct and complete Spanish Translation

### CODE REVIEW

**Comment by AJenbo** [comment]
Nice work. There are how ever still about 10 lines missing :)

Make sure to go over both forms of the plural translations and the ones marked as fuzzy/needs-work

image

**Comment by hiperiondev** [comment]
What are the missing lines? 
I'm using poedit (in Linux). Can you recommend a better editor?

**Comment by AJenbo** [comment]
What's wrong with Poedit? It's the one I use and where the screen shot was taken. The reason I noticed the issue was because Poedit highlighted it.

**Comment by hiperiondev** [comment]
There is no problem with POEdit, I was asking if there was an option that I did not know.
I only see 2 lines with plural problems. I have already corrected them.

**Comment by AJenbo** [comment]
Hey @hiperiondev I did an update of the translation file to match the latest content. There are some new strings and changes which leaves 44 lines untranslated, would you be willing to update the translation to fill the gap :)

https://github.com/diasurgical/devilutionX/blob/master/Translations/es.po
Note that some of the strings are located in the Android XML files:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-es/strings.xml
Template:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

**Comment by hiperiondev** [comment]
> Hey @hiperiondev I did an update of the translation file to match the latest content. There are some new strings and changes which leaves 44 lines untranslated, would you be willing to update the translation to fill the gap :)

Hi,
I was very busy with work. I made several advances in manual proofreading of the translation.
This weekend I will try to finish it and make the changes that you indicate.

**Pull request merged**
