### PR TITLE
UK TL: Credits

### PR DESCRIPTION
**Pull request by tsunamistate**
Full TL of Credits screen!

Contains punctuation fixes for Help screen
Changed "Скасувати" to "Відміна" since it's shorter

### CODE REVIEW

**Comment by AJenbo** [comment]
@SourceCodeDeleted

**Comment by SourceCodeDeleted** [comment]
hello, This so far looks good. Is the credits screen complete? I only see English in the bottom .

**Comment by tsunamistate** [comment]
@SourceCodeDeleted in Credits, only titles and professions are exposed to translation.
Names are not translatable, and IMO they shouldn't be.

**Comment by SourceCodeDeleted** [comment]
> @SourceCodeDeleted in Credits, only titles and professions are exposed to translation. Names are not translatable, and IMO they shouldn't be.

I agree 100%.

but what are these?

Screenshot from 2021-11-15 21-11-31

**Comment by tsunamistate** [comment]
I updated PO file from code before starting, those are updated code references
I usually make 1 commit with just code update, but forgot to do it this time and didn't want to reset my work

**Comment by SourceCodeDeleted** [comment]
ok well, it is merged now. So we can leave it for now )

**Pull request merged**
