### PR TITLE
fix duplicated dLight saving/loading

### PR DESCRIPTION
**Pull request by qndel**
Resolves https://github.com/diasurgical/devilutionX/issues/2267

### CODE REVIEW

**Comment by ephphatha** [comment]
This exposes an issue with the current save/load code 😂 . Making a save while in town with this fix results in the first file region where the light array was saved being set to the value of the uninitialised byte array backing SaveHelper (note 1). If you then load that save in a version of devilutionx without this fix applied it'll load the values into dlight due to the first load and likely crash depending on whether the value happens to be valid. Making a save in a debug build writes the value 0xCD repeatedly in this region. Old versions will load this value and it is interpreted as -51 when assigning to light_table_index
https://github.com/diasurgical/devilutionX/blob/3f69faaecfa7069c17e51c05e84f6ddc27e56814/Source/scrollrt.cpp#L596
This then causes a buffer underrun in `RenderTile`
https://github.com/diasurgical/devilutionX/blob/3f69faaecfa7069c17e51c05e84f6ddc27e56814/Source/engine/render/dun_render.cpp#L1399

1: https://github.com/diasurgical/devilutionX/commit/f33f7ae7ebb8583a2bb270b4d27b3f39281a9929#diff-eb2db6084d42c0224b56a122152915d07d944c27040e427d6193bc382ca754b3 introduced the potential for this bug, a fix that would avoid having to zero-init the entire array would be to make skip() memset the region it skips over. Given there hasn't been a release since that commit it's only going to be an issue for people running their own builds, a mitigation could be to leave the duplicate save in for a while.

**Comment by qndel** [comment]
Tbh, I'd get rid of saving / loading light at all + https://github.com/diasurgical/devilutionX/pull/2110/

**Review by ephphatha — APPROVED** [review]
I think now that SaveHelp::skip writes 0's this is safe to merge, town expects a light level of zero for older versions so this should be backwards compatible.

**Comment by AJenbo** [comment]
Won't this cause save games to load with no lights in vanilla?

**Comment by ephphatha** [comment]
When loading a save made inside the dungeon dLight gets initialised from the second load (unchanged by this commit):
https://github.com/diasurgical/devilutionX/blob/e1f2fbcb9b87e95d8c283e833610de253f83b4aa/Source/loadsave.cpp#L1225-L1228

When in town the light level doesn't get applied to the tiles as far as I can tell, and even if it does the expected value for dLight values in town is 0, the entire array is memset when the level is loaded from a normal transition:
https://github.com/diasurgical/devilutionX/blob/e1f2fbcb9b87e95d8c283e833610de253f83b4aa/Source/town.cpp#L322

**Pull request closed without merging**
