### PR TITLE
margins and tweaks

### PR DESCRIPTION
**Pull request by qndel**
old vs new
oldnewhighlight
+pixel perfect label targetting
+fixes labels appearing red for no reason

### CODE REVIEW

**Comment by Chance4us** [comment]
By the way, the item label color in dungeon is always red, but it doesn't seem to be a highlight related issue.
It seems to be more related to the getTextColor function.

**Comment by qndel** [comment]
rofl, looks like item stat flag is false till you pick the item up, that's why items in town are mostly while, because there are no monsters to drop them there, while any loot dropped by monster will be red in dungeon>.>

**Comment by Chance4us** [comment]
> rofl, looks like item stat flag is false till you pick the item up, that's why items in town are mostly while, because there are no monsters to drop them there, while any loot dropped by monster will be red in dungeon>.>

Yes, stat flag behaves erratically. I have workarounded the problem by the following code.

			int txt_color = UIS_SILVER;
			if (itm._iMagical == ITEM_QUALITY_MAGIC) txt_color = UIS_BLUE;
			if (itm._iMagical == ITEM_QUALITY_UNIQUE) txt_color = UIS_GOLD;
			if (itm._iStatFlag == false && ((itm._iMagical == ITEM_QUALITY_MAGIC) || (itm._iMagical == ITEM_QUALITY_UNIQUE))) txt_color = UIS_RED;
DrawString(out, label.text.c_str(), { label.pos.x, label.pos.y, label.width, height }, txt_color);

**Comment by Chance4us** [comment]
Now is is perfect.

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
And it even has nice commits

**Pull request merged**
