### PR TITLE
Updated debian packaging files

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by muzena** [comment]
@AJenbo

**Comment by AJenbo** [comment]
> @AJenbo
> What is purpose of https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/devilutionx.mpq file, and how it used it?

better widescreen support, but it next to diabdat.mpq

**Comment by M0Rf30** [comment]
@muzena why not use something like this?
```
override_dh_auto_install:
    DESTDIR=$$(pwd)/debian/tmp cmake --install .
```
and avoid lines from 21 to 33 ?
In this way you can drastically simplify `rules` file and leavereage on DevilutionX official CMakeLists

**Comment by AJenbo** [comment]
im wondering how relevant this even is with cmake now setup to generate deb packages?

**Comment by muzena** [comment]
> @muzena why not use something like this?
> 
> ```
> override_dh_auto_install:
>     DESTDIR=$$(pwd)/debian/tmp cmake --install .
> ```
> 
> and avoid lines from 21 to 33 ?
> In this way you can drastically simplify `rules` file and leverage on DevilutionX official CMakeLists

@AJenbo @M0Rf30 
Is now ok?

**Comment by AJenbo** [comment]
@muzena could you check that config.h gets generated with the proper values for `PROJECT_VERSION_MAJOR`, `PROJECT_VERSION_MINOR`, and `PROJECT_VERSION_PATCH`. Since this must now match for network games to connect.

**Comment by M0Rf30** [comment]
> > @muzena why not use something like this?
> > ```
> > override_dh_auto_install:
> >     DESTDIR=$$(pwd)/debian/tmp cmake --install .
> > ```
> > 
> > 
> > and avoid lines from 21 to 33 ?
> > In this way you can drastically simplify `rules` file and leverage on DevilutionX official CMakeLists
> 
> @AJenbo @M0Rf30
> Is now ok?

Do you test it? doesn't work for me in a clean container
```
root@7d38d499f95a:/media/Packaging# debuild -us -uc
 dpkg-buildpackage -rfakeroot -us -uc -ui
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package devilutionx
dpkg-buildpackage: info: source version 1.0.1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Goran Vidovic (gogo) <trebelnik2@gmail.com>
 dpkg-source --before-build Packaging
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --buildsystem=cmake --builddirectory=obj-x86_64-linux-gnu
   dh_auto_clean -O--buildsystem=cmake -O--builddirectory=obj-x86_64-linux-gnu
   dh_clean -O--buildsystem=cmake -O--builddirectory=obj-x86_64-linux-gnu
 dpkg-source -b Packaging
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building devilutionx in devilutionx_1.0.1.tar.xz
dpkg-source: info: building devilutionx in devilutionx_1.0.1.dsc
 debian/rules build
dh build --buildsystem=cmake --builddirectory=obj-x86_64-linux-gnu
   dh_update_autotools_config -O--buildsystem=cmake -O--builddirectory=obj-x86_64-linux-gnu
   dh_autoreconf -O--buildsystem=cmake -O--builddirectory=obj-x86_64-linux-gnu
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/media/Packaging'
dh_auto_configure -- \
	-DNIGHTLY_BUILD=ON \
	-DVERSION_NUM=/medi \
	-DVERSION_SUFFIX=-ckaging
	cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DNIGHTLY_BUILD=ON -DVERSION_NUM=/medi -DVERSION_SUFFIX=-ckaging
CMake Error: The source directory "/media/Packaging" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
dh_auto_configure: cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DNIGHTLY_BUILD=ON -DVERSION_NUM=/medi -DVERSION_SUFFIX=-ckaging returned exit code 1
debian/rules:18: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory '/media/Packaging'
debian/rules:15: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
```

**Comment by muzena** [comment]
> @muzena could you check that config.h gets generated with the proper values for `PROJECT_VERSION_MAJOR`, `PROJECT_VERSION_MINOR`, and `PROJECT_VERSION_PATCH`. Since this must now match for network games to connect.

@AJenbo 
Is version ok?
devilutionx3

**Pull request merged**
