### PR TITLE
Refactor M_StartHit to receive a Monster reference

### PR DESCRIPTION
**Pull request by canassa**

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Review by AJenbo — APPROVED** [review]

**Comment by canassa** [comment]
@AJenbo I think that the auto-merge is stuck for some reason here

**Comment by StephenCWills** [comment]
It looks like the CircleCI builds are not running on your PRs. Did you somehow deny CircleCI access to your fork?

**Comment by canassa** [comment]
> It looks like the CircleCI builds are not running on your PRs. Did you somehow deny CircleCI access to your fork?

Hmm, I don't think so. It's a regular fork AFAIK

**Comment by AJenbo** [comment]
Please login to circleci and see if that helps

**Comment by canassa** [comment]
It's logged in now:

image

**Comment by canassa** [comment]
I forced the pipeline to rerun on #4894, it indeed triggered a job in my CircleCI

https://app.circleci.com/pipelines/github/canassa/devilutionX

But the testflow status is still "Expected — Waiting for status to be reported"

**Comment by StephenCWills** [comment]
> I forced the pipeline to rerun on #4894, it indeed triggered a job in my CircleCI
> 
> https://app.circleci.com/pipelines/github/canassa/devilutionX
> 
> But the testflow status is still "Expected — Waiting for status to be reported"

It sounds like you've done exactly what I did when this happened to my fork. It should allow CircleCI to run jobs against your fork, but testflow will never phone home correctly in any PRs that you submit. You'll probably need to unfollow the project in your fork to fix it properly. Now that you've logged into CircleCI, it should have permission to trigger jobs against your PRs so you shouldn't need to have it followed except maybe if you're explicitly testing those builds in your fork (like modifying the CircleCI config).

**Review by StephenCWills — APPROVED** [review]
Looks like CircleCI is working properly. 😄

**Comment by canassa** [comment]
> Looks like CircleCI is working properly. 😄

Yes, the unfollow did the trick 🥳

**Comment by AJenbo** [comment]
Confusing, but glad you got it sorted :)

**Pull request merged**
