### PR TITLE
Avoid static non-PODs

### PR DESCRIPTION
**Pull request by BardurArantsson**

### CODE REVIEW

**Comment by BardurArantsson** [comment]
Obviously not an *ideal* solution (which would be avoiding the global altogether), but at least this doesn't fall foul of the Static Order Initialization Fiasco :)

**Comment by AJenbo** [comment]
Hmm maybe the crash is dependant on the resolution, what do you run the game as?

**Comment by BardurArantsson** [comment]
Oh, this has nothing to do with the crash. It's just about avoiding non-POD statics.

**Comment by AJenbo** [comment]
Ik, but was curious about that part also.

**Comment by BardurArantsson** [comment]
Oh! I am running at 800x600 as it happens :). Upscaled, of course.

**Comment by julealgon** [comment]
What is a "POD"?

**Comment by AJenbo** [comment]
Plain Old Data

**Comment by AJenbo** [comment]
The crash on missing graphics should now also be handled

**Pull request merged**
