### PR TITLE
Reduce demo message size

### PR DESCRIPTION
**Pull request by glebm**
We now use a single `uint8_t` to indicate both the demo message type and the event type.
`DemoMsg` struct (type + progress to next tick) and per-event data are now kept in separate dequeues.

RAM usage for the timedemo messages: -85% (1.8 MiB -> 261 KiB)

Demo (`.dmo`) file size: -57% (590,790 bytes -> 253,410 bytes)

### CODE REVIEW

**Comment by AJenbo** [comment]
nice, that will also limit the repo growth

**Comment by glebm** [comment]
Updated! The new version is even smaller

**Comment by glebm** [comment]
This makes the demo run at full speed on RG-99!

We can improve this even further by mmaping the demo file and parsing it on the go but this is good enough for now.

**Comment by glebm** [comment]
Actually a simple way to improve memory usage without mmap is to put event data into a separate struct.
I'll implement that

**Review by AJenbo — COMMENTED** [review]
That's pretty amazing, especially considering where things started :)

**Comment by glebm** [comment]
This is now good to go! :rocket:

**Review by AJenbo — APPROVED** [review]
Nice that it's still compatible with older versions :)
Not that I expect many ones out there.

**Pull request merged**
