### PR TITLE
msg: add documentation of cmd_id enum

### PR DESCRIPTION
**Pull request by mewmew**
document all the things

### CODE REVIEW

**Comment by mewmew** [comment]
Note, Hellfire related `cmd` enums are not documented.

Also, there were two enums present in Diablo v1.09b which seem to be missing from `msg.h`? Namely these:

```c
	// Cast spell from speedbook.
	//
	// body (TCmdParam1):
	//    int16_t spell_id
	CMD_SBSPELL,

	// Remove mana shield of player (invoked at end of timer; 48 ticks per clvl).
	//
	// body (TCmd)
	CMD_ENDSHIELD,
```

**Comment by galaxyhaxz** [comment]
I think just about all of it is spot on. Two things to note:
`CMD_SBSPELL` is unused, the code for casting spells from the speedbook was removed after the demo but the network command and function still remain.
`CMD_REQUESTAGITEM` any command with `A` in front of the item means "auto" as in use the auto-place function for placing in the inventory, rather than cursor. :)

**Comment by mewmew** [comment]
> CMD_REQUESTAGITEM any command with A in front of the item means "auto" as in use the auto-place function for placing in the inventory, rather than cursor. :)

Yeah :) I choose to use "loot" for looting an item to (and auto-placing in) inventory, and "lift" to lift an item to hand (the `HoldItem` cursor).

**Comment by AJenbo** [comment]
Nice :)

**Pull request merged**
