### PR TITLE
Improvements to macOS CMake target

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
Create proper macOS application bundle with CMake
Enable HiDPI support and disable automatic graphics switching

### CODE REVIEW

**Comment by AJenbo** [comment]
Thanks, this is grate timing as we are aiming to do a 64bit release next 😊

**Comment by alexey-lysiuk** [comment]
It will be cool if CMake based build system will replace hand-crafted one. Maintaining both just for macOS is a bit overkill.

**Comment by AJenbo** [comment]
Hmm am I missing some steps here?

image

**Comment by AJenbo** [comment]
Making use of CPack should allow us to drop the old 32bit build system.
https://cmake.org/cmake/help/v3.6/module/CPackDMG.html

This would be a huge step for the project since the 32bit mac build is always a bit of a pain, not to mention the next macOS release drops 32bit support.

**Comment by alexey-lysiuk** [comment]
> Hmm am I missing some steps here?
> 
> image

What was CMake generator?

**Comment by AJenbo** [comment]
are you asking the version?
cmake version 3.13.4

**Comment by alexey-lysiuk** [comment]
No, I was asking about generator, i.e. Xcode, Ninja, UNIX makefiles, etc.

**Comment by AJenbo** [comment]
make file, like the instructions in the readme.

**Comment by alexey-lysiuk** [comment]
I guess it's a problem with .plist processing as I only tested with Xcode. Fixing this may require a different .plist file.

**Comment by AJenbo** [comment]
Yeah, already figured something out by using the cmake template as a base. Working on the CPack part now. Just need it to actually include the bundle at this point :P

**Comment by alexey-lysiuk** [comment]
Your changes at diasurgical/devilutionX@e569df6b00fd65d0bfcc439f79ab1e3b774931e4 (`mac` branch) works just fine with Xcode. There is no point to keep this PR open.

**Comment by AJenbo** [comment]
ok good to know, I still have a few adjustments to make before it's ready to merge, but thanks for the hint and testing.

**Comment by AJenbo** [comment]
Merged via https://github.com/diasurgical/devilutionX/commit/d6a457791b5bd0a47186dfa2c9971d0839ff4c66

Feel free to test things :)

**Pull request closed without merging**
