### PR TITLE
Revamp ini options and sync in multiplayer

### LINKED ISSUE #52: Diablo Hellfire support
Current known issues.
- [x] Barrels and other objects are missing from the hive and crypt.
- [x] Na-Krul doesn't spawn.
- [x] Store menus aren't correct
- [x] Some instability
- [x] Town doesn't update when opening crypt and hive
- [x] Runes have no effect
- [x] Corner Stone of The World doesn't work
- [x] Not compatible with Hellfire save games
- [x] The support screen is missing.
- [x] Clicking ESC goes to the support screen instead of Quit Hellfire
- [x] Description for Loopback is that of UDP
- [x] Griswold will buy random belt items.
- [x] Items morph (multiplayer, new single-player, slain hero issues are all caused by this) #981
- [x] Multiplayer hero save/load (currently only Diablo saves are supported for multiplayer)

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #52

Check that the host is running the same version and game when joining.

Sync Jog in Town, TheQues, and CowQuest in multiplayer.

New Diablo.ini layout:
```ini
[Game]
Speed=50
Fast Walk=1
Grab Input=0
Theo Quest=0
Cow Quest=0

[Audio]
Sound Volume=0
Music Volume=0
Walking Sound=1

[Graphics]
Fullscreen=1
Fit to Screen=1
Scaling Quality=2
Integer Scaling=0
Vertical Sync=1
Blended Transparency=1
Gamma Correction=100
Color Cycling=1

[Diablo]
Intro=0

[Hellfire]
Intro=0
SItem=

[Phone Book]
Entry1=127.0.0.1

[Network]
Bind Address=0.0.0.0

[NetMsg]
F12=Now you DIE!
F11=Here's something for you.
F10=Follow me.
F9=I need help! Come Here!
```

Also, the variables are now documented in the code:
```cpp
	Sint32 nSoundVolume; // Movie and SFX volume
	Sint32 nMusicVolume; // Music volume
	bool bWalkingSound;  // Player emits sound when walking

	Sint32 nWidth;             // Render width
	Sint32 nHeight;            // Render height
	bool bFullscreen;          // Run in fullscreen or windowed mode
	bool bUpscale;             // Scale the image after renderin
	bool bFitToScreen;         // Expand the aspect ratio to match the screen
	char szScaleQuality[2];    // See SDL_HINT_RENDER_SCALE_QUALITY
	bool bIntegerScaling;      // Only scale by values devisable by the width and height
	bool bVSync;               // Enable vsync on the output
	bool bBlendedTransparancy; // Use blended transparency rather than stippled
	Sint32 nGammaCorrection;   // Gamma correction level
	bool bColorCycling;        // Enable colour cycling animations

	Sint32 nTickRate; // Game play ticks per secound
	bool bJogInTown;  // Enable double walk speed when in town
	bool bGrabInput;  // Do not let the mouse leave the application window
	bool bTheoQuest;  // Enable the Theo quest
	bool bCowQuest;   // Enable the cow quest

	char szBindAddress[129]; // Optionally bind to a specific network interface
```

### CODE REVIEW

**Comment by AJenbo** [comment]
@isage could you look into what is causing `config.h` to not be properly updated on the vita builds?
```

ninja: job failed: /home/user/vitasdk/bin/arm-vita-eabi-g++ -DNONET -DVITA -D_POSIX_C_SOURCE=200809L -D__FILE__=\"Source/multi.cpp\" -I../Source -I../SourceS -I. -isystem /home/user/vitasdk/arm-vita-eabi/include/SDL2 -Wl,-q -DDEFAULT_WIDTH=960 -DDEFAULT_HEIGHT=544 -Wno-builtin-macro-redefined -O2 -g -DNDEBUG -flto -fno-fat-lto-objects -Wno-multichar -Wno-int-to-pointer-cast -fsigned-char -std=c++11 -MD -MT CMakeFiles/devilution.dir/Source/multi.cpp.obj -MF CMakeFiles/devilution.dir/Source/multi.cpp.obj.d -o CMakeFiles/devilution.dir/Source/multi.cpp.obj -c ../Source/multi.cpp
../Source/multi.cpp: In function 'dvl::BOOL dvl::NetInit(dvl::BOOL, dvl::BOOL*)':
../Source/multi.cpp:742:54: error: expected primary-expression before ';' token
  742 |   sgGameInitInfo.versionMajor = PROJECT_VERSION_MAJOR;
      |                                                      ^
../Source/multi.cpp:743:54: error: expected primary-expression before ';' token
  743 |   sgGameInitInfo.versionMinor = PROJECT_VERSION_MINOR;
      |                                                      ^
../Source/multi.cpp:744:54: error: expected primary-expression before ';' token
  744 |   sgGameInitInfo.versionPatch = PROJECT_VERSION_PATCH;
```

**Comment by isage** [comment]
Sure

**Comment by isage** [comment]
That seems to be related to 
```
CMake Warning at CMakeLists.txt:56 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.
```
Although locally (with cmake 3.17.4) it works fine. Investigating.

**Comment by AJenbo** [comment]
It relies on git for fetching the version from the most recent tag, maybe the contains is just missing git.

**Comment by isage** [comment]
Riiight. That seems to be it. I completely forgot that vitasdk image includes absolutely nothing by default, sorry.

**Comment by AJenbo** [comment]
No worries, thanks for helping in figuring out the issue :)

**Pull request merged**
