### PR TITLE
Fix OOB in DrawSpell

### PR DESCRIPTION
**Pull request by glebm**
The OOB here was in `_pSplLvl[spl]`.

The value of `SPL_INVALID` is defined as `0xFFFFFFFF`, which is `-1` if you're lucky with the `sizeof(int)`.

The fix is 2-fold:
1. Change the type of `spl` to `int` to avoid depending on `sizeof(int)`.
2. Do not access the array when `spl == SPL_INVALID`.

By the way, perhaps `SPL_INVALID` was defined as `-1` in the original game?

### CODE REVIEW

**Comment by AJenbo** [comment]
Yeah I think setting it to -1 upstream might be a better solution.

**Comment by glebm** [comment]
@AJenbo This fix will still be needed, though we'd be able to change `char` to `signed char` instead of `int`.

**Comment by glebm** [comment]
Sent https://github.com/diasurgical/devilution/pull/1829 changing the `_INVALID` enum values.

**Comment by glebm** [comment]
Might as well use `int` for `spl` since this is devilutionX only and avoid the implicit 128-spell limit (may be useful for mods in the future and this is the only `char spl` I could find -- everywhere else it's an `int`)

**Comment by glebm** [comment]
Force-pushed with updated commit message and a change from `char` to `int` for `spl`.

**Pull request merged**
