### PR TITLE
Refactor OpenDingux build scripts

### PR DESCRIPTION
**Pull request by guillaume-roche**
Created a common `build.sh` script that takes the target architecture as a command line argument.
Updated existing build scripts for opendingux and retrofw. Now they call `build.sh` with the corresponding target.

This avoids code duplication and should help maintaining the build script.

Another change that I made is that I split the buildroot prepare and build steps. This way, if the buildroot compilation fails, it will be run again the next time the script is called. This was not the case
before, as the buildroot step was skipped when the buildroot folder existed.

This contribution is sponsored by my company, [Genymobile](https://github.com/Genymobile), for #hacktoberfest.

### CODE REVIEW

**Comment by glebm** [comment]
Hi! Thanks, this is nice but incorrect, unfortunately.
The buildroots and package formats are different for RetroFW and OpenDingux (I didn't know this when I was starting out).

There is an outstanding PR to fix these build scripts.
https://github.com/diasurgical/devilutionX/pull/363

Perhaps you can give this another try once #363 has been merged :)

There is also a branch I've been releasing from, https://github.com/glebm/devilutionX/, it has a few updates on top of #363 as well (releases: https://github.com/glebm/devilutionX/releases)

**Comment by guillaume-roche** [comment]
Hi, thanks for your feedback. Yup, I saw your PR https://github.com/diasurgical/devilutionX/pull/363 after opening this one. I will rebase when it's merged, no worries.

**Comment by AJenbo** [comment]
@guillaume-roche the other branch is now merged so this should be ready for rebaseing

**Comment by guillaume-roche** [comment]
Please don't merge yet, this is still a work in progress.

**Comment by guillaume-roche** [comment]
OK, it should be good now. However, I get a build error for the `rg350` target.
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
```
I don't think this is a regression from my patches, since I get the same error when building master branch (commit #56f953b0).

**Comment by glebm** [comment]
@guillaume-roche The rg350 defconfig needs an additional line. This is fixed on my branch but not on master:
https://github.com/glebm/devilutionX/commit/64516b00acb4d89bf12f7a33622cebe10b6d2c3e

**Comment by guillaume-roche** [comment]
I can cherry-pick your commit in this branch, so it gets fixed here also.

**Comment by guillaume-roche** [comment]
OK, it builds now :+1:

**Comment by AJenbo** [comment]
@glebm when you decide to merge this please use rebase or squash so that we have a clean commit history :)
(this looks like a squash to me since commit #2 & #3 just correct things from #1)

**Pull request merged**
