### PR TITLE
libfmt: Bump version

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by AJenbo** [comment]
GCC 6 strikes again

**Comment by glebm** [comment]
Filed https://github.com/fmtlib/fmt/issues/2703

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Anything exciting in the new version?

**Comment by glebm** [comment]
There is a ton of stuff: https://github.com/fmtlib/fmt/releases

Highlights for me:
1. Compile-time format string checking is enabled by default
2. Compile-time formatting
3. Lots of optimizations

**Comment by AJenbo** [comment]
> Compile-time formatting

Will that work even with our translation macros?

**Comment by glebm** [comment]
> Will that work even with our translation macros?

I doubt that

**Pull request merged**
