### PR TITLE
Update Japanese Translations and Option Menu Fixed

### PR DESCRIPTION
**Pull request by bubio**
- Translation of the added options menu.
- Fixed an issue where Japanese strings would become too long, causing the options menu to crash.
- Fixed incorrect description of Show FPS and FPS Limiter option.

スクリーンショット 2021-11-27 17 19 54

/cc @obligaron

### CODE REVIEW

**Review by obligaron — APPROVED** [review]
lgtm.
Thanks 🙂

**Review by AJenbo — APPROVED** [review]

**Comment by glebm** [comment]
The list of commits here is very confusing. Can you please start using feature branches?
Basically your master branch would always be the same as the upstream master branch, and each PR should come from a separate branch.

**Comment by bubio** [comment]
I don't know what went wrong.
 Is it wrong that I PR translation and other changes together(settingsmenu.cpp, options.cpp)?

**Comment by AJenbo** [comment]
> I don't know what went wrong.

Since we use rebase and squash to merge pull requests, the commits gets assingned new hashes. When you then merge upstream in to your branch you get duplicate commits and new PRs you create will appear to contain all previous changes done by you (why there are 19 commits in this PR). Eventually this will lead to a conflict.

So instead of merging you should either reset your master branch between each PR, or create new branches from master and periodically update master.

**Comment by bubio** [comment]
@AJenbo 
Thank you very much.
I now know what's wrong.

**Comment by AJenbo** [comment]
> I don't know what I should do.

Join on Discord and we can better help explain how to handle it in the future :)

**Comment by AJenbo** [comment]
Merged via https://github.com/diasurgical/devilutionX/commit/204c947ef4c0e6ce4af303798f7fb739121d0f62, https://github.com/diasurgical/devilutionX/commit/6a087ce350022729d45d046d038d556e29db65ca and https://github.com/diasurgical/devilutionX/commit/52203cece486539220a30e4ce49996a758679cea

**Pull request closed without merging**
