### PR TITLE
[Android] Enable side-by-side installation of debug builds

### PR DESCRIPTION
**Pull request by StephenCWills**
`applicationIdSuffix` results in an application ID of `org.disasurgical.devilutionx.dev`. This PR applies the suffix specifically for debug builds, which is also what we use for CI. Naturally, release builds would be used for releases, so they can be installed side-by-side.

The `app_name` string is also modified specifically for debug builds as well to help differentiate the dev version. I wish it could fit more characters in, but this is probably good enough to tell them apart. Maybe altering the icon would be even better, but it's not really my area of expertise. If someone wants to design one, I believe we just need to override the files under `main/res/mipmap*` by adding new ones to the `debug/res` folder, like we did with the `app_name` string.

... Or maybe we can just change the background color? Thoughts?

Here is the app icon for `org.diasurgical.devilutionx` alongside `org.diasurgical.devilutionx.dev`.
image

And here is the App Info page for `org.diasurgical.devilutionx.dev`.
image

### CODE REVIEW

**Comment by AJenbo** [comment]
ic_launcher-playstore-dev

**Comment by StephenCWills** [comment]
It works, thanks @AJenbo!

image

image

**Comment by StephenCWills** [comment]
I just installed from CI, and it appears to have the updated icon, name, and application ID. So everything looks good to me.

**Comment by AJenbo** [comment]
Thank you for looking in to this :)

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
