### PR TITLE
update arenas

### PR DESCRIPTION
**Pull request by ikonomov**
Removed the murky pools, simplified the areas and made them accessible without teleport.

### CODE REVIEW

**Comment by D1-Constantine** [comment]
Approved by me

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Before/after shots would have made it a bit easier to review, other then that it looks good :+1:

**Comment by AJenbo** [comment]
P.s. hope you have a chance to update the tutorial :)

**Comment by ikonomov** [comment]
https://github.com/diasurgical/modding-tools/pull/12
I've added a few extra tips for using Tiled to hopefully make it easier to get started.

**Comment by kphoenix137** [comment]
Can we still get some screenshots?

**Pull request merged**
