### PR TITLE
Fix Attack Speed Modifiers

### PR DESCRIPTION
**Pull request by kphoenix137**
Fixes: https://github.com/diasurgical/devilutionX/issues/839

Melee:
Quick = 0 + (Rnd 0 to 1)
Fast = 1
Faster = 1 + (Rnd 0 to 1)
Fastest = 2

Bow:
Quick = 0 + (Rnd 0 to 1)
Fast = 1

### CODE REVIEW

**Comment by julealgon** [comment]
While I obviously appreciate this change (you might wanna link to the issue even if it is currently closed @kphoenix137 ), it would be nice if this could be done in a "less hardcoded" way.

However, I'm personally fine with moving forward as-is for now considering the original implementation was also incredibly hardcoded as well.

**Comment by kphoenix137** [comment]
> While I obviously appreciate this change (you might wanna link to the issue even if it is currently closed @kphoenix137 ), it would be nice if this could be done in a "less hardcoded" way.
> 
> However, I'm personally fine with moving forward as-is for now considering the original implementation was also incredibly hardcoded as well.

Can you elaborate? I'm not sure how something like this could be unhardcoded.

**Comment by julealgon** [comment]
> Can you elaborate? I'm not sure how something like this could be unhardcoded.

Yeah. I meant in a way that we wouldn't need to point to specific frames in the animation and skip them with `if` statements. Instead, imagine you just specified either a percentage or fixed delta and the engine would automatically pick which frames to skip based on the total number of frames in the animation. Imagine something that could be completely parameterized, for instance, by a modder: the current way this is done makes that completely impossible. Any changes to, let's say, add a new speed suffix (either to increase or decrease the speed), or even adjusting the current affixes, would need dedicated code changes in this area of the code.

Again, something more dynamic would be a lot more involved than the current implementation which is why I mentioned this feels ok to me, for now. I really dislike it as a final solution however, for the reasons above.

**Comment by kphoenix137** [comment]
> 

Isn't that how DevilutionX works? In Devilution, in this function the specific frames to skip are set. In DevilutionX, we just provide how many skipped frames we want.

**Comment by DakkJaniels** [comment]
> Yeah. I meant in a way that we wouldn't need to point to specific frames in the animation and skip them with `if` statements. 

You don't need to point to specific frames, you just pass in a number and it figures it out...

**Comment by DakkJaniels** [comment]
How does this feel to play? I feel like it would feels kind of janky to have your attack speed change randomly.

**Comment by FitzRoyX** [comment]
How about an alternate PR for 1,2,3,4? I'd like to try both before forming an opinion. It does seem like inconsistent attack speeds would be janky. They are already kind of janky with standstill attacks taking longer than other attacks.

**Comment by DakkJaniels** [comment]
Would prefer 1,2,3,4 over this. I guess it's a bug and should be fixed regardless of gameplay implications 🤷🏽‍♂️

**Comment by kphoenix137** [comment]
> Would prefer 1,2,3,4 over this. I guess it's a bug and should be fixed regardless of gameplay implications 🤷🏽‍♂️ 

Well there are gameplay implications and I think they would be well received. Such a change would actually put warrior on par with rogue and sorcerer with endgame items

**Comment by kphoenix137** [comment]
I'm going to close this on the grounds that I think even though it's an improvement, it's not a solution, or at least not the solution I'd like to see.

**Comment by julealgon** [comment]
@kphoenix137 
> > 
> 
> Isn't that how DevilutionX works? In Devilution, in this function the specific frames to skip are set. In DevilutionX, we just provide how many skipped frames we want. I've also been a big advocate for percentage based frame reduction, however that does pose a huge balance change

@DakkJaniels 
> You don't need to point to specific frames, you just pass in a number and it figures it out...
>
> Granted, there is a limit to that number, which you would need to know, and I don't think it would be possible to have negative skipped frames to increase the length of the animation. I think the latter would be a lot more work.

You guys are absolutely correct. I made a dumb assumption when making that comment: I thought the logic was still the original one where there were `if` statements against specific animation frames in the logic. Should've checked the code before commenting... I had no idea that was changed 😅 my bad.

---

@DakkJaniels 
> How does this feel to play? I feel like it would feel kind of janky to have your attack speed change randomly.

@FitzRoyX 
> It does seem like inconsistent attack speeds would be janky.

It will definitely feel very _weird_, let me put it this way, because this is not really a common approach to this problem in other games I'm pretty sure. I personally am ok with how it feels but I'd totally understand someone being put off by the inconsistent behavior.

Interestingly enough, the pre-release demo had something _similar_ to this, but it was tied to "when" the attacks would trigger and not to the attack animation speed itself: if you constantly clicked a target "at maximum speed", there would be a (variable) delay between each attack, resulting in overall variable attack speed. You could circumvent that by precise-clicking for each attack with proper timing, but I remember that being nontrivial, actually. I'm not sure why that was the case, but I assume it was caused by poor input handling/input buffering code and not really by design. I could be wrong though.

Having said the above, I'm partial to timing clicks as a mechanic, but I don't think it fits the rest of the overal design of Diablo 1: the game promotes too much spam for such a mechanic to be enjoyable IMHO.

---

@DakkJaniels 
> Would prefer 1,2,3,4 over this. I guess it's a bug and should be fixed regardless of gameplay implications 🤷🏽‍♂️

I'd also prefer that (it was the original solution proposal) but it was shot down due to balance concerns, which is why the approach in this PR was even being considered.

**Pull request closed without merging**
