### PR TITLE
Lua integration for Hellfire and modding

### PR DESCRIPTION
**Pull request by kphoenix137**
This PR moves all Hellfire logic to lua scripts, and allows for lua mods to be loaded from an external filepath.

**Modders are able to utilize the following:**
Pre-hook: Allows running Lua code before the C++ code.
Post-hook: Allows running Lua code after the C++ code.
Override: Completely overwrites the function with a provided Lua function.

Hellfire scripts are located in `Source/lua/hellfire`, and there is a script for each cpp file that contains Hellfire specific logic.

### CODE REVIEW

**Comment by kphoenix137** [comment]
@staphen https://github.com/diasurgical/devilutionX/pull/7397/files#diff-d3f2f653697b88b01c5f94e7a52c2a16db00e2a26d5d9ab504ea75feef090311R191

**Comment by StephenCWills** [comment]
> When running the `hellfire/player.lua` script, I encounter a crash because of the handling here. My assumption is that if this function only had setters and getters along with the existing member functions, this would work correctly.

According to the code examples I've seen, member variables should work fine. There's probably some other reason. Maybe something to do with the build check failure.

```
  Error: D:\a\devilutionX\devilutionX\Source\lua\lua.cpp(194): error C2672: 'sol::state_view::new_usertype': no matching overloaded function found
  D:\a\devilutionX\devilutionX\build-ninja-vcpkg-relwithdebinfo\_deps\sol2-src\include\sol/state_view.hpp(784): note: could be 'sol::basic_usertype<T,sol::reference> sol::state_view::new_usertype(Args ...)'
  D:\a\devilutionX\devilutionX\Source\lua\lua.cpp(194): note: 'sol::basic_usertype<T,sol::reference> sol::state_view::new_usertype(Args ...)': could not deduce template argument for 'Args &&' from 'overloaded-function'
```

My recommendation is don't throw every single thing in there all at once. Make it work with a subset of the members and add more gradually.

**Comment by kphoenix137** [comment]
> > When running the `hellfire/player.lua` script, I encounter a crash because of the handling here. My assumption is that if this function only had setters and getters along with the existing member functions, this would work correctly.
> 
> According to the code examples I've seen, member variables should work fine. There's probably some other reason. Maybe something to do with the build check failure.
> 
> ```
>   Error: D:\a\devilutionX\devilutionX\Source\lua\lua.cpp(194): error C2672: 'sol::state_view::new_usertype': no matching overloaded function found
>   D:\a\devilutionX\devilutionX\build-ninja-vcpkg-relwithdebinfo\_deps\sol2-src\include\sol/state_view.hpp(784): note: could be 'sol::basic_usertype<T,sol::reference> sol::state_view::new_usertype(Args ...)'
>   D:\a\devilutionX\devilutionX\Source\lua\lua.cpp(194): note: 'sol::basic_usertype<T,sol::reference> sol::state_view::new_usertype(Args ...)': could not deduce template argument for 'Args &&' from 'overloaded-function'
> ```
> 
> My recommendation is don't throw every single thing in there all at once. Make it work with a subset of the members and add more gradually.

I found the problem. It was registering a template function.

**Comment by kphoenix137** [comment]
Unfortunately, my changes are causing issues that make the compiler run out of heap space. I'm just not entirely sure what I'm doing, so I'm closing this to leave the door open for someone more experienced to take a crack at it.

**Pull request closed without merging**
