### PR TITLE
Rename sync_word_6AA708 to sgnMonsterPriority in Source/sync.cpp for clarity

### PR DESCRIPTION
**Pull request by Semperfis96**
To improve (a little bit) the code & begin to work on DevilutionX, I remove a strange hexa thing. Not a big deal, compile & test on multiplayer game, still work correctly.
 
PS: Sorry for bad english, it's not my native language.

### CODE REVIEW

**Comment by julealgon** [comment]
Please try to be a bit more specific with PR/commit titles when possible.

Looks like you are renaming a very specific field here, so you might want to mention that in the message.

For example, "Rename X in Y module to Z" is a lot more descriptive than "Clean variable name".

Additionally, what did that suffix mean? I'd only approve this when i know what it means. Since i don't know I'll leave this to others to review.

**Comment by AJenbo** [comment]
Thanks, but this doesn't actually help since it removes the context from the variable.

`Word` in this context is a reference to the data type located at `0x6AA708` in the original game, so one doesn't make sense without the other. 

In short, what you have done here is rename it from "Sync Value 5" to "Sync Value". Instead we need to figure out what "Value 5" (`word 0x6AA708`) represents.

From its usage, I think this is used for figuring out what monsters should be synced, by seeing ordering them by the distance to the player.

`sgnMonsterPriority` might be a reasonable name for it.

For x86 word is a 16bit unsigned integer:
https://en.wikipedia.org/wiki/Word_(computer_architecture).

**Comment by galaxyhaxz** [comment]
> Sorry for the first title & the unclear PR, i'm quite new to github & i really want to be useful in Devilution

We all had to start somewhere :)

**Comment by AJenbo** [comment]
Thanks for applying the name :)

**Comment by Semperfis96** [comment]
Thank you for merging my small changes !
This is so good to participate to the code of a such mythical game !

**Comment by julealgon** [comment]
> Sorry for the first title & the unclear PR, i'm quite new to github & i really want to be useful in Devilution

No need for apologies ;) Looking forward to your help, we don't have a lot of people maintaining the codebase.

**Pull request merged**
