### PR TITLE
Update Japanese Translation

### PR DESCRIPTION
**Pull request by bubio**
- Minor translation adjustments
- segment_ja.py already applied

----
Some of the translations don't seem to be reflected.
スクリーンショット 2021-11-19 0 59 38
スクリーンショット 2021-11-19 0 59 49

### CODE REVIEW

**Comment by AJenbo** [comment]
> Some of the translations don't seem to be reflected.

You need to update your translation file, either form the pot or from source.

**Comment by bubio** [comment]
> > Some of the translations don't seem to be reflected.
> 
> You need to update your translation file, either form the pot or from source.

As usual, I put the mo file in the same folder as the ini file and tested it.

スクリーンショット 2021-11-19 1 42 58


Elsewhere, the changes will be reflected.

**Comment by bubio** [comment]
I'd like to say it's still in English...

It's not reflected in other languages either.
スクリーンショット 2021-11-19 1 58 46

スクリーンショット 2021-11-19 2 00 15

**Comment by AJenbo** [comment]
image

**Comment by bubio** [comment]
In my environment, it just won't translate.
I also tried to update it with Poedit.
After that, I tried to build it again, but there was no change.

**Comment by AJenbo** [comment]
No worries, I'm sure it will sort it self out one way or another.

**Comment by AJenbo** [comment]
Ok, the issue is that the string was changed so Poedit has marked the line as needing a human review:
image

Strings marked as Needs Work (Fuzzy) will not be included in the translation. To fix this simply update the lines to match the new english line and remove the Needs Work marking.

**Comment by bubio** [comment]
@AJenbo 

Oh, it's true.
Before I knew it, it became "Fuzzy".
I'll fix it later.

**Comment by bubio** [comment]
Certainly, this is a concern.
From a Japanese point of view, it is not unreadable, but it is perceived as not being a "Japanese character".

**Pull request merged**
