### PR TITLE
MP: Send delta message for lachdanans death

### LINKED ISSUE #5858: MP: Lachdanan reviving after coming back from town
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

After completing the quest tied to him, TPing out of the level and coming back, Lachdanan will be displayed as if you had never completed the quest and will give you the very same item he was supposed to drop (not the veil of steel, the other one), this can be reproduced indefinitely.
For reference, I have randomized quests turned off and of course quests in multiplayer turned on.

### To Reproduce

1. Complete Lachdanan's quest in MP
2. TP out to town
3. Go back
4. Witness Lachdanan being there again
5. Talk to him, he'll give you the dialogue right before he dies
6. It drops the very same magical item he gave you before

### Expected Behavior

Lachdanan should have stayed dead after completing the quest

### Additional context

All encountered on commit [a629aa9](https://github.com/diasurgical/devilutionX/commit/a629aa91535483f12280f599b8134229d53a6336)

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #5858

Let Lachdanan rest in peace🙏

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
Makes sens, kinda interesting though :)

**Comment by obligaron** [comment]
Initially I thought `MonsterDeath` would do the job... but I was wrong. 😛

**Comment by glebm** [comment]
Perhaps it should? It's kinda odd that it sends messages for loot spawning etc but not for the death itself

**Comment by obligaron** [comment]
A refactoring would be good. 👍 
But it's a rabit hole. You start by one function and come to the next.
So I think this is outside of this issue. Perhaps we can should open a issue for it?

**Comment by glebm** [comment]
Yeah, it's out of scope for the fix, a separate issue would make sense

**Comment by AJenbo** [comment]
Yeah it's a bit of an issue since it's also what is called when receiving `CMD_MONSTDEATH` so that has to be taken in to account to avoid an infinit loop :)

It might actually make sens to find a general way to solve this for all network vs local events.

**Comment by glebm** [comment]
> so that has to be taken in to account to avoid an infinit loop :)

That's why it already has a `sendmsg` argument from what I can tell.

**Pull request merged**
