### PR TITLE
scrollrt: Optimize `dRendered` size (-10 KiB)

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by AJenbo** [comment]
Coudn't we use std::bitset for this?

**Comment by glebm** [comment]
Yes, we probably should! And `std::bitset` is also a good idea for this.

**Review by AJenbo — CHANGES_REQUESTED** [review]
Waiting for std:bitset :)

**Comment by glebm** [comment]
Done! Migrated a few arrays to an `std::bitset`-based implementation.

**Review by AJenbo — APPROVED** [review]

**Comment by qndel** [comment]
Just 1 thing - if we got `set`, it would be logical to have `get` instead of test :D

**Comment by glebm** [comment]
The API mimics std::bitset

**Pull request merged**
