### PR TITLE
Add CMake option to use system SDL_image

### LINKED ISSUE #3384: CMake: Option to use system SDL_Image
Writing a package definition for DevilutionX (for RetroLX) and discovered there's no way to tell it to use the system SDL_image.

### PR DESCRIPTION
**Pull request by StephenCWills**
* Adds `DEVILUTIONX_SYSTEM_SDL_IMAGE` to specify whether to search for a system library
* Adds `sdl2-image` dependency to vcpkg for Windows builds
* Adds `FindSDL2_image.cmake` to utilize `PkgConfig` for locating libSDL2_image on Linux

Works for Linux SDL1/SDL2, Windows SDL2, and possibly a few other platforms.

This resolves #3384

### CODE REVIEW

**Review by glebm — APPROVED** [review]

**Comment by glebm** [comment]
Thank you!

**Comment by aanderse** [comment]
Any chance we can do the same with `asio`, `libzt`, etc...?

**Comment by glebm** [comment]
@aanderse I don't know if DevilutionX actually works with the upstream versions of asio and libzt

**Comment by aanderse** [comment]
Oh... I guess my comment should be ignored then :smile: Thanks for letting me know!

**Pull request merged**
