### PR TITLE
Add a basic Quake-style console

### PR DESCRIPTION
**Pull request by glebm**
console

Enabled only in Debug mode.

Runs Lua similar to the `lua` CLI.
Supports multiline input with Shift+Enter.

Missing features:
1. Scrollback.
2. Input history on up/down.

Open with backtick, close with Esc.

### CODE REVIEW

**Comment by AJenbo** [comment]
He, an issue with Quake ports that didn't affect the original game is that ` is not a key on many non-US keyboards, for me that button is ½, so the console breaks when ports add proper KB support ... which we have.

**Comment by glebm** [comment]
There is a distinction between physical and virtual keyboard codes in SDL, so this should be possible to map correctly

**Comment by AJenbo** [comment]
For me ` is done by two presses on shift + `'` (one press to start the accent modifier, and then the next to modify nothing). Take a guess how fun code blocks in MD files are to type by hand (14 key presses).

**Comment by glebm** [comment]
@AJenbo I've made it work on all keyboard layouts using `SDL_SCANCODE_GRAVE` instead of the keymapper.

**Comment by AJenbo** [comment]
Nice, thanks for that :)

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
