### PR TITLE
Enable ADL for Monster walking and decouple positioning while walking from game logic

### PR DESCRIPTION
**Pull request by obligaron**
Beware! The monsters are getting faster! 👹 

Contributes to #838

<details><summary>Example Video</summary>

### Master

https://user-images.githubusercontent.com/25415264/123510936-8de8ce00-d67e-11eb-8397-fe39538104d1.mp4

### PR

https://user-images.githubusercontent.com/25415264/123510939-950fdc00-d67e-11eb-9854-fbb0638937b8.mp4

</details>

Notes:

- No behavior changes
- Similar to #1939 this introduces a minor breaking change (one animation)

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
At this point this almost seamed to easy :D

**Comment by Chance4us** [comment]
A great enhancement. Thanks a lot.
I have already tested a bit and noticed the death animation of the "Gold Viper" as slowed down.
I wanted to let you know so that all animations work properly.
You can see it the attached video and continue testing with the attached savegame.
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6720246/output.mkv.zip)
[gold_viper.zip](https://github.com/diasurgical/devilutionX/files/6720247/gold_viper.zip)

**Comment by Chance4us** [comment]
I can also create an issue if you wish.

**Comment by obligaron** [comment]
> 
> 
> At this point this almost seamed to easy :D

I thought the same 🙂 
It was nice that the original designed ADL can be taken as-is.

**Comment by obligaron** [comment]
> 
> 
> A great enhancement. Thanks a lot.
> I have already tested a bit and noticed the death animation of the "Gold Viper" as slowed down.
> I wanted to let you know so that all animations work properly.
> You can see it in attached video and continue testing with the attached savegame.
> [output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6720246/output.mkv.zip)
> [gold_viper.zip](https://github.com/diasurgical/devilutionX/files/6720247/gold_viper.zip)

Thanks for highlighting, testing and the nice save game. 👍 
This make it life a lot easier. 🙂

**Comment by Chance4us** [comment]
Your are welcome. Thanks for new nice features.

**Comment by Chance4us** [comment]
@obligaron @AJenbo For some reason I have the impression that the "flesh thing" is not moving very smoothly.
I'm using the latest master build commit 0755bcc6dec707c0fe7395a8e3fcc06438297fa0.
I don't know if it's just a feeling because this monster is moving slowly.
Unfortunately, it is not so easy to see on the video, but you can use the attached savegame to check it.
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6729197/output.mkv.zip)
[flesh_thing.zip](https://github.com/diasurgical/devilutionX/files/6729201/flesh_thing.zip)

**Comment by AJenbo** [comment]
Looks to me like they it's just because they look very different from different angles so it makes a bit of a jump when they turn. Is that what you are referring to?

**Comment by Chance4us** [comment]
> Looks to me like they it's just because they look very different from different angles so it makes a bit of a jump when they turn. Is that what you are referring to?

I noticed that too and they seem as if they are shaking a bit when walking straight ahead also.
But maybe I'm just a little over-sensitive as with many things.

**Comment by julealgon** [comment]
You should find a way to embed video in comments as @obligaron does @Chance4us . The zip thing is a pain.

**Comment by GcjvvbbbbkGcjvvbbbbk** [comment]
فيديوهات

**Comment by julealgon** [comment]
...the spambots are taking over this repo, WTF. @AJenbo ⬆️

**Comment by GcjvvbbbbkGcjvvbbbbk** [comment]
for (auto direction in enum_values<Direction>())
    ...

**Comment by AJenbo** [comment]
two in two days is not so much considering the amount of traffic we have been getting

image

**Comment by obligaron** [comment]
> 
> 
> > Looks to me like they it's just because they look very different from different angles so it makes a bit of a jump when they turn. Is that what you are referring to?
> 
> I noticed that too and they seem as if they are shaking a bit when walking straight ahead also.
> But maybe I'm just a little over-sensitive as with many things.

I looked at it with GameSpeed=2 (10%) and it seems correct.
Only the animation frames don't fit so well in the per-frame positioning.

**Pull request merged**
