### PR TITLE
DiabloUI: Refactor UI_Item to tagged unions

### PR DESCRIPTION
**Pull request by glebm**
Makes the code easier to understand.
Also makes building lists easier.

Also fixes focus indicator in SELLOAD_DIALOG (this type of bug is impossible with the new structs).

### CODE REVIEW

**Comment by glebm** [comment]
Rebased on latest master

**Comment by AJenbo** [comment]
Looks like this has caused some rendering issues in the description area:
image

**Comment by AJenbo** [comment]
The correct appearance:
image

**Comment by glebm** [comment]
Sent https://github.com/diasurgical/devilutionX/pull/304

**Pull request merged**
