### PR TITLE
Convert ZT gamename to lower case

### PR DESCRIPTION
**Pull request by DakkJaniels**

### CODE REVIEW

**Comment by StephenCWills** [comment]
@glebm I'm reading that `std::tolower()` is locale-dependent. Is this another function we should be avoiding?

**Comment by DakkJaniels** [comment]
>  I'm reading that std::tolower() is locale-dependent. Is this another function we should be avoiding?

I can just swap it to 
```cpp
selgame_Ip[i] = (selgame_Ip[i] >= 'A' && selgame_Ip[i] <= 'Z') ? selgame_Ip[i] + 'a' - 'A' : selgame_Ip[i];
```
if that's preferable

**Comment by AJenbo** [comment]
This depend on us figuring out where the names are generated :)

**Comment by StephenCWills** [comment]
https://github.com/diasurgical/devilutionX/blob/b21ebffaf2d20b40a25afe393a02713da0b81987/Source/dvlnet/protocol_zt.cpp#L315-L325

**Comment by DakkJaniels** [comment]
was just going to post that lol

**Comment by AJenbo** [comment]
Ok, well that confirms that they are all lowercase an limited to a-z :)

**Comment by DakkJaniels** [comment]
could also swap to `std::tolower(selgame_Ip, std::locale("C"))` - I think that will force the conversion to "classic"

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
