### PR TITLE
Update zh_CN.po

### PR DESCRIPTION
**Pull request by tytannial**

### CODE REVIEW

**Comment by AJenbo** [comment]
@Jmgr @M0Rf30 would you give this a quick look just to see if it's a general improvement?

**Comment by Jmgr** [comment]
@AJenbo my partner is the one who can read Mandarin, and I haven't been able to convince her to have a look at so much localized text. I won't be able to help with this I'm afraid.

**Comment by Jmgr** [comment]
Oh I just saw your edit :)

**Comment by muziling** [comment]
> @muziling would you give this a quick look just to see if it's a general improvement?

A big improvement,  add many missed translation item

**Comment by AJenbo** [comment]
Thanks for giving it a look 😊

And thanks both for all the work translating things 👍

**Comment by AJenbo** [comment]
Hey @tytannial and @muziling I updated the Chinese translation file with the latest template, the translation is 96% done at this point just 79 string left.

https://github.com/diasurgical/devilutionX/blob/master/Translations/zh_CN.po
Note that some of the strings are located in the Android XML files:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-zh-rCN/strings.xml
Template:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

**Comment by muziling** [comment]
[zh_CN.zip](https://github.com/diasurgical/devilutionX/files/6951024/zh_CN.zip)
fix some wrong translated items and update un-translate item

**Comment by AJenbo** [comment]
Updated: https://github.com/diasurgical/devilutionX/commit/3e57f73932c92f54c811bf728d20563feef5dd65

**Comment by AJenbo** [comment]
@tytannial @muziling hey, it's now possible to test the translation in-game using the latest test build and this mpq: [devilutionx-font.zip](https://github.com/diasurgical/devilutionX/files/7229029/devilutionx-font.zip)

image

There is still some work being done to improve the look of the font (which is why it currently isn't included by default), so things may still change.

If you have time to update the translation that would be really appreciated as we are planing to do a release next month :)

**Comment by muziling** [comment]
[zh_CN.zip](https://github.com/diasurgical/devilutionX/files/7231449/zh_CN.zip)

Revert losts of translation .
Translation text from https://d.163.com/article/143251.html and little modify.

**Comment by tytannial** [comment]
> [zh_CN.zip](https://github.com/diasurgical/devilutionX/files/7231449/zh_CN.zip)
> 
> I did a look tytannial's translation , maybe he translation with google and not review it, So i revert losts of translation .
> Translation text from https://d.163.com/article/143251.html and small modify.
> 
> Still lots of translation need to correct, hope someone can do this.

Yes, use machine translation fill the empty and replace some of item names with d3 cn edition and d2r.  I only review small part of it. Hellfire does not release in CN, it need to be translated. 😟

**Comment by tytannial** [comment]
Some of monster names are extracted from diablo 3 cn and d2r too, so this part of translation is correct.

**Comment by tytannial** [comment]
> I try to contact yahooboby, hope he can do this. He's translated hellfire topic: https://bbs.3dmgame.com/thread-6108433-1-1.html

我看了下内容，文本量比我想象的要少，这段时间我准备在之前基础上重新翻译整个游戏了，国庆节能搞定大部分内容。他翻译的内容更多基于TH MOD，我这边会尽快处理整个游戏的文本。

**Comment by yahooboby** [comment]
中文：
仅合适diablo1.09+Hellfire1.0x(包括GOG)
English:
Diablo 1.0x+ HellFire 1.0x(including GOG)
[EnTozh_CH.TXT](https://github.com/diasurgical/devilutionX/files/7248965/EnTozh_CH.TXT)

**Comment by tytannial** [comment]
> 中文： 仅合适diablo1.09+Hellfire1.0x(包括GOG) English: Diablo 1.0x+ HellFire 1.0x(including GOG) [EnTozh_CH.TXT](https://github.com/diasurgical/devilutionX/files/7248965/EnTozh_CH.TXT)

我会尽快合并汉化，感谢提供支持。

**Comment by yahooboby** [comment]
谁能提供来自的https://github.com/diasurgical/modding-tools/blob/master/Tiled/README.md这几张图片：
Who can offer from https://github.com/diasurgical/modding-tools/blob/master/Tiled/README.md this picture:

Tiled/tilesets/catacombs_mega_special.png
Tiled/tilesets/cathedral_mega_special.png
Tiled/tilesets/caves_mega.png
Tiled/tilesets/hell_mega.png
Tiled/tilesets/monsters.png
Tiled/tilesets/objects.png
Tiled/tilesets/tristram_mega_special.png

谢谢!
thanks!

**Comment by AJenbo** [comment]
@yahooboby use https://github.com/savagesteel/d1-graphics-tool to generate them (you need to first extract the level .cel from diabdat.mpq)

**Comment by muziling** [comment]
> > 中文： 仅合适diablo1.09+Hellfire1.0x(包括GOG) English: Diablo 1.0x+ HellFire 1.0x(including GOG) [EnTozh_CH.TXT](https://github.com/diasurgical/devilutionX/files/7248965/EnTozh_CH.TXT)
> 
> 我会尽快合并汉化，感谢提供支持。

I have a tool to update current po file using yahooboby's txt,  if you need , use it
1. convert yahooboby's text to po file format,  using any notepad tool find and replace.
2. download po file I upload 3 days ago
3. Then at command line, run:
```
Gettext.exe  yahooboby's-po-file i-uploaded-po-file  new.po
```

[Gettext.zip](https://github.com/diasurgical/devilutionX/files/7250224/Gettext.zip)

**Comment by tytannial** [comment]
> > > 中文： 仅合适diablo1.09+Hellfire1.0x(包括GOG) English: Diablo 1.0x+ HellFire 1.0x(including GOG) [EnTozh_CH.TXT](https://github.com/diasurgical/devilutionX/files/7248965/EnTozh_CH.TXT)
> > 
> > 
> > 我会尽快合并汉化，感谢提供支持。
> 
> I have a tool to update current po file using yahooboby's txt, if you need , use it
> 
> 1. convert yahooboby's text to po file format,  using any notepad tool find and replace.
> 2. download po file I upload 3 days ago
> 3. Then at command line, run:
> 
> ```
> Gettext.exe  yahooboby's-po-file i-uploaded-po-file  new.po
> ```
> 
> [Gettext.zip](https://github.com/diasurgical/devilutionX/files/7250224/Gettext.zip)

Thanks.

**Comment by yahooboby** [comment]
@AJenbo（  https://github.com/diasurgical/devilutionX/pull/2460#issuecomment-929882667）
thanks.

 BUG:
1：
bug1
2：
bug2

A sentence in Chinese text can be displayed at most two lines.

**Comment by yahooboby** [comment]
@AJenbo:
I almost forgot to mention,Can you change the + sign to make it a little bit more obvious,
This + in the game do not seriously look at what is not clear(google translation)

中文：
差点忘记说了，
能不能修改 + 这个符号明显点，
这个 + 在游戏不认真看根本看不清楚是什么

**Comment by AJenbo** [comment]
What + sign?

> BUG
> A sentence in Chinese text can be displayed at most two lines.

Is that a rule in Chinese, or are you saying that the line should be automatically split in to more lines? Since I can't read Chinese I can't tell if the text looks good or bad.

The text rendering only split lines where there are regular spaces, so you would have to add some, or add manual line breaks.

**Comment by tytannial** [comment]
> What + sign?
> 
> > BUG
> > A sentence in Chinese text can be displayed at most two lines.
> 
> Is that a rule in Chinese, or are you saying that the line should be automatically split in to more lines? Since I can't read Chinese I can't tell if the text looks good or bad.
> 
> The text rendering only split lines where there are regular spaces, so you would have to add some, or add manual line breaks.

In Chinese ,Like "We are do-
om."
The line break happen at an unexpected position and there is enough room for words.

**Comment by AJenbo** [comment]
The game text render has no linguistic understanding, it will simply break the line at the nearest space. If no spaces are found it will result in one of 3 things, depending on the place the test is being shown:
1. The text is rendered past the edge
2. The text is not rendered
3. The text is immediately pushed to the next line

It is up to the translator to inject line breaks where needed in cases where the text dos not fit. Note that now is not a good time to do so for the NPC conversation text since we currently only have the smallest font for Chinese (temporarily we use it everywhere). Once the other font sizes are done it would change the length of the lines in this dialog.

Preview of the font that will be used for conversation text:
image

Since I cannot read/write Chinese I cannot look up the text based on an image, so I cannot be more specific then that. If you can give me the text then I can say more about what is happening and why.

**Comment by glebm** [comment]
I think a simple improvement to that could be breaking on the nearest punctuation. `,.?!、 。？！`
We're certainly not bringing in a CJK segmenter at runtime 笑

**Comment by AJenbo** [comment]
The problem here is that our WordWrapper function works by replacing spaces with line breaks. Injecting symbols would require rewriting the code to producing a new string and swapping them.

> @AJenbo Note that there are no spaces around punctuation in CJK.

Afaik there actually is in Korean :)

**Comment by yahooboby** [comment]
@AJenbo:
1、 A piece of Chinese is showing two lines, but there is no translation after it is not added '\n'；
not a BUG. 



No additional '\n ' like in:

bug4

**Comment by yahooboby** [comment]
@AJenbo:
2、+ and I(i) and 1
Original game :



now game:



If you don’t look at that'+' seriously, you don’t know what it is?
1 (one) of this game looks like I
And I is like 1 (one) 
You create a new character and give the character a name 1i1i1i1i to see the difference

**Comment by AJenbo** [comment]
1: Could you add a new issue for this, then I can look in to it at a later point.

2: The translator will probably have to insert a line break somewhere in this line:
image
(wait til the large font is ready)

**Comment by yahooboby** [comment]
@AJenbo:
2、+ and I(i) and 1
Original game :



now game:



If you don’t look at that'+' seriously, you don’t know what it is?
1 (one) of this game looks like I
And I is like 1 (one) 
You create a new character and give the character a name 1i1i1i1i to see the difference

**Comment by AJenbo** [comment]
> @AJenbo: 2、+ and now game:
> 

It looks like you don't have the latest font when viewing this, this is how it currently looks.

image

>  You create a new character and give the character a name 1i1i1i1i to see the difference

That is true for the original as well:
image

**Comment by yahooboby** [comment]
@AJenbo
I just told you that this is not a source code problem, we have to solve the problem,
Increase by yourself to determine how many Chinese characters are displayed on a line, and then automatically wrap after exceeding. .
The translator will know if you translate. No need to post. 

只是跟你说这个不是源码问题，非要解决问题，
由自己增加判断一行显示多少汉字，超过然后自动换行。。
翻译的话翻译员会知道的。不需要开贴。

**Comment by yahooboby** [comment]
Let me update

**Comment by AJenbo** [comment]
> @AJenbo I just told you that this is not a source code problem, we have to solve the problem, Increase by yourself to determine how many Chinese characters are displayed on a line, and then automatically wrap after exceeding. . The translator will know if you translate. No need to post.

Ok, I though you said that it was missing the last line as well:
image

**Comment by yahooboby** [comment]
only two:


show all:
Add'\n' to every new line of translation

**Comment by tytannial** [comment]
> only two: 
> 
> show all: Add'\n' to every new line of translation 

我不知道我理解对了没，是不是这三行因为没有手动换行导致缺失了。如果有这种问题我这边开一个ISSUE标记下。

**Comment by yahooboby** [comment]
@tytannial 是这样的。。最好还是每行加'\n'好。
要不游戏里面的剧情没有这么大框框,显示两行。你不加'\n'说不定小框洭只显示一行，第二行后面都不显示。。

**Comment by AJenbo** [comment]
Again, do not do this now for dialogs, the font for dialogs is not done yet, you will have to redo it very soon and it will cause it to look like it's randomly borken.

**Comment by yahooboby** [comment]
@AJenbo:
You are too streamlined. devilutionx.mpq turned out to be 10MB
now devilutionx.mpq is only 1.7M
Open the game display will make an error. . .

**Comment by AJenbo** [comment]
> @AJenbo: You are too streamlined.

I don't know what that is suppose to mean?

> @AJenbo: 

As I have mentioned a few times, the Chinese font is not done yet and so is not part of the normal builds. If you want to see the latest font you have to switch to English only. Or manually combine the fonts.

**Comment by yahooboby** [comment]
@AJenbo
OK, wait it...

**Comment by tytannial** [comment]
I will start a issue for locale. 

> @AJenbo OK, wait it...

#2990, for discuss.

**Comment by AJenbo** [comment]
We have had some times to continue the work on the CJK portion of the font:

image

image

**Comment by tytannial** [comment]
it looks the font size is a little bigger. but it is so cool and so close to the original game's font.🙂

characters are stacked. 

By the way, new text pr will be ready at this weekend, more quest dialog fix.

**Comment by muziling** [comment]
@tytannial  Above picture translation text is not well,  灵巧，活力  translation not same as Diablo II

**Comment by muziling** [comment]
@tytannial 魔法抵抗  to  魔法抗性

**Comment by tytannial** [comment]
How to change game language to zh_CN. I have put all files to game dir.

In diablo.ini
[Language]
Code=zh_CN

But game language doesn't change.

**Comment by muziling** [comment]
> I could have been using an old translation when taking the screen shot, since I don't read Chinese I can't really tell as the just appears as confusing squigily symbols to me.
> 
> Please try it out for your self and see if there are any issues when doing so.

May be  char unicode map  in pcx font  has some error.    How to view and correct pcx file ?

**Comment by AJenbo** [comment]
If you can join us on Discord chat I think it would make it easier to solve the issues :)
https://discord.gg/YQKCAYQ

I think your right that there are some wrong symbols in there, could you help identify what symbols these are?

image

**Comment by tytannial** [comment]
> > How to change game language to zh_CN. I have put all files to game dir.
> > In diablo.ini [Language] Code=zh_CN
> > But game language doesn't change.
> 
> https://github.com/diasurgical/devilutionX/wiki/Translation-Guide

More fix will be done.

**Comment by tytannial** [comment]
> If you can join us on Discord chat I think it would make it easier to solve the issues :) https://discord.gg/YQKCAYQ
> 
> I think your right that there are some wrong symbols in there, could you help identify what symbols these are?
> 
> image

栀 栁 栂 栃

**Comment by AJenbo** [comment]
> > I think your right that there are some wrong symbols in there, could you help identify what symbols these are?
> 
> 栀 栁 栂 栃

Thanks that is the symbols that should be on row 68
image

30-68.pcx looks identical so it looks like we just used the wrong row for 67, so hopefully things line up from then and there are no more mistakes like that. But it would be helpful if you can go over them and check the first symbol from each row (from 30-4e.pcx to 30-99.pcx is the Chinese symbols)

**Comment by AJenbo** [comment]
For now I have reverted that row to use the small Unifont symbols, since Chinese is mono-spaced it won't affect preview much. I expect that we can have it correctly rendered by the start of the week.

image

**Comment by AJenbo** [comment]
> Understand, I will fix the format to use `{suffix}{{prefix}{name}}`. PR will be ready soon. In zhCN, It should be {suffix}{prefix}{name}, it's achievable. I have muddled the two names, sorry. 😵

Oh good that was what I understood it to be the first time you mentioned it 🙂

**Pull request merged**
