### PR TITLE
Optimize GetPlayerGraphicForSpell

### PR DESCRIPTION
**Pull request by kphoenix137**
Improves performance and maintainability by using a lookup table instead of switch-case conditions.

### CODE REVIEW

**Comment by StephenCWills** [comment]
I'm not sure that `unordered_map` is really going to perform better than the switch-case with just three options.

**Comment by kphoenix137** [comment]
> I'm not sure that `unordered_map` is really going to perform better than the switch-case with just three options.

I'm sure the difference is negligible in this case. Which one is more user friendly for modification?

**Comment by StephenCWills** [comment]
> Which one is more user friendly for modification?

Neither. The code is all here in this one tiny method, and modification can be mostly a copy/paste job either way.

**Comment by kphoenix137** [comment]
> > Which one is more user friendly for modification?
> 
> Neither. The code is all here in this one tiny method, and modification can be mostly a copy/paste job either way.

Sounds good, I will close.

**Pull request closed without merging**
