### PR TITLE
🚚 engine.h: Extract some code to separate files

### PR DESCRIPTION
**Pull request by glebm**
`engine.h` is getting quite bloated. Moves this code to their own files.

### CODE REVIEW

**Comment by julealgon** [comment]
I'm a bit confused by this proposal. Didn't you say it is common in C++ to have multiple classes/structs/etc in the same file since they are in the same "translation unit" or something? 

Now we are using "it's too bloated" criteria for splitting?

Can you elaborate on this a little bit please? I actually added some of the types myself to `engine.h` on purpose with that assumption in mind, instead of creating new files as it would be much more standard for me coming from C#.

**Comment by glebm** [comment]
Suggested reading about translation units: https://www.toptal.com/c-plus-plus/c-plus-plus-understanding-compilation

What you basically want is functions defined in `cpp` files (for `hpp` it doesn't matter) to be able to inline into each other where it makes sense. There is nothing like that here.

**Comment by vlolteanu** [comment]
It's also worth getting rid of these from monsters.{hpp,cpp} and turning them into constexpr functions in direction.hpp:

`extern Direction left[8];
extern Direction right[8];
extern Direction opposite[8];`

**Comment by glebm** [comment]
> It's also worth getting rid of these from monsters.{hpp,cpp} and turning them into constexpr functions in direction.hpp:

Sounds like these should just be `constexpr` in the direction header. Out of scope for this PR though.

**Comment by glebm** [comment]
@AJenbo Now there are conflicts :(

**Comment by AJenbo** [comment]
Sorry, my mom visited this weekend...

**Review by AJenbo — APPROVED** [review]

**Review by AJenbo — APPROVED** [review]

**Review by AJenbo — DISMISSED** [review]

**Comment by AJenbo** [comment]
@glebm easy enough to resolve, feel free to merge when build passes if you agree with the rebase

**Comment by glebm** [comment]
This needed another rebase, should be good to merge now

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
