### PR TITLE
Add cutttw widescreen load screen

### PR DESCRIPTION
**Pull request by AJenbo**

### CODE REVIEW

**Comment by AJenbo** [comment]
> It opens in d1g so it should be okay.

All the broken ones were made using d1g :D

**Comment by StephenCWills** [comment]
> All the broken ones were made using d1g :D

Yeah, but they also wouldn't load in d1g, so I still trust it for this.

**Comment by AJenbo** [comment]
Odd I seam to remember they did load in the version i was using

**Comment by StephenCWills** [comment]
I'm using a version from December.

**Pull request merged**
