### PR TITLE
Upgrade source-download SDL to 2.28.5

### PR DESCRIPTION
**Pull request by tsunamistate**
Looks like this is all that was needed for Android to build, let's see how other platforms will react

**WARNING:** I play tested the build on my Google Pixel 2 with Android 11, but I would recommend to play test the CI build on couple more devices before this is merged

P.S. I don't know why Android Studio had to change the **_whole file_** when I committed 2 lines, so look at [SDLActivity.java](https://github.com/diasurgical/devilutionX/compare/master...tsunamistate:devilutionX:SDL-update?expand=1#diff-c171a1bdd421190fd5b4effb33cf09c5e17062fa6cbbabbe8e3ddb1702cf0a5b) changes with "Hide whitespace" ON

### CODE REVIEW

**Comment by tsunamistate** [comment]
`error: static assertion failed due to requirement '27 == 28': SDL_MINOR_VERSION == SDL_BUILD_MINOR_VERSION`
`error: static assertion failed due to requirement '0 == 5': SDL_PATCHLEVEL == SDL_BUILD_MICRO_VERSION`

The errors are due to cached SDL version in the runners
Can we rerun the jobs with busted cache?

**Comment by AJenbo** [comment]
Rather then patching the SDL Java files could you please copy them from the same release of SDL as is used on the C side of things: https://github.com/libsdl-org/SDL/tree/release-2.28.5/android-project

**Comment by tsunamistate** [comment]
Sure, no problem
The main changes are in `SDLActivity.java` (changes to InputDevice.SOURCE_MOUSE) and `HIDDeviceManager.java` (adding new controller device IDs) the rest are just comments for magic numbers

**Comment by AJenbo** [comment]
Thanks that was really helpful :)

**Pull request merged**
