### PR TITLE
Remove spurious "I can't cast that here"

### PR DESCRIPTION
**Pull request by vlolteanu**

### CODE REVIEW

**Comment by AJenbo** [comment]
Isn't this going to prevent users from casting identify/repair/recharge when pointing to the desired item?

**Comment by vlolteanu** [comment]
You're right.

Fixed.

**Comment by AJenbo** [comment]
Could you explain what condition this now changes :sweat_smile:

**Comment by vlolteanu** [comment]
If you've readied some spell that needs targeting, such as Fireball, and you're in the dungeon, right-clicking on anything that is not the playing field (character sheet, inventory etc) won't do anything. However, if you're in town, the character says "I can't cast that here".

**Pull request merged**
