### PR TITLE
Debian package files

### PR DESCRIPTION
**Pull request by Vitexus**
Hallo here is my debian package: 
[devilutionx_0.4.0_amd64.deb.gz](https://github.com/diasurgical/devilutionX/files/3415319/devilutionx_0.4.0_amd64.deb.gz)

It may be inspiration for you.

### CODE REVIEW

**Comment by ms217** [comment]
Hi,
Would you mind moving the Debian packaging files/folder into the "Packaging" folder?

**Comment by Vitexus** [comment]
Hallo @ms217 , 
Be sure Yes. I understand you want have source clean a possible, but there is no way ( --source switch etc. ) how to build  debian package with control files in non-standart location.

https://wiki.debian.org/BuildingTutorial :

>When you check the contents of this directory (typing ls again), you'll see quite a number of files of different sorts, and a debian directory.
> Every Debian (or Debian derivative) package includes a debian directory, where all the information related to the Debian package is stored. Anything that's outside of that directory, is the upstream code, i.e. the original code released by whoever programmed the software.

But - Ok. I try to do as you want. Symlink and Readme update might be helpfull :)

**Comment by AJenbo** [comment]
Thanks this has now been merged, except for the readme part as I felt it was a bit out of place/incomplete.

**Comment by Vitexus** [comment]
Cool! I'm happy to help.

**Comment by AJenbo** [comment]
Do i need to run anything after running  dpkg-buildpackage, and where is the debs saved to?

**Comment by Vitexus** [comment]
First at all you need **./debian** directory in right place or make symlink: `ln -s Packaging/debian .`
I use **debuild** command from package  `devscripts`. it build packages in .. of repository root.  (../../debian) 
and then `debuild -us -uc`

you have to finally get :

> dpkg-deb: creating package „devilutionx“ in „../devilutionx_0.4.0_amd64.deb“.

The newer command /usr/bin/**debuild-pbuilder** from package **pbuilder**: also works well.

**Pull request merged**
