### PR TITLE
set select correctly

### PR DESCRIPTION
**Pull request by Trihedraf**
Fixes #5497 accidentally set start and select both as start.

### CODE REVIEW

**Review by glebm — DISMISSED** [review]

**Comment by glebm** [comment]
No idea why the "testflow" check is stuck

**Comment by Trihedraf** [comment]
I don't know but it always is stuck on my PRs

**Comment by glebm** [comment]
no idea if that'll help but can you try logging into CircleCI?

**Comment by StephenCWills** [comment]
> No idea why the "testflow" check is stuck

I think it happens when someone explicitly follows their fork. @Trihedraf, you might consider unfollowing if you're not using the CircleCI builds on your fork.

**Comment by Trihedraf** [comment]
Unfollowed, but I am assuming it won't fix it for this one.

**Comment by StephenCWills** [comment]
Right, but I think you can make it trigger the builds again with...

```
git checkout miyooselect
git commit --amend --no-edit
git push --force
```

**Review by StephenCWills — APPROVED** [review]

**Pull request merged**
