### PR TITLE
Add Ukrainian translation (Main Menu)

### PR DESCRIPTION
**Pull request by tsunamistate**
This adds Ukrainian TL to CMake and Translations folder.
TL'd Main Menu to start with.
Reviews very welcome!

Conscious choices (which I may regret):
* Rouge as "Пройдисвіт". Maybe it should be genderized ("Пройдисвітка")?
* Multiplayer as "Гра з Друзями". Transliterating "Multiplayer" really irks me, I only did it in Russian TL because I couldn't think of an alternative. Maybe "Мережева Гра" is better, but I don't know what is the precedent in Ukrainian localizations.
* Omitting "Singleplayer" TL altogether except in Main Menu. This word has no precedent except for transliterating it, AFAIK, so "New Single Player Hero" becomes just "Новий Герой".
* "Hero" and "Character" are TL'd as "Герой" in both cases.
* "Delete" as "Стерти". Any other meaning was too long in UI.

For reviewers, start from second commit, to isolate newly added strings.

### CODE REVIEW

**Comment by SourceCodeDeleted** [comment]
So does this mean there is a Ukrainian version @tsunamistate ?

**Comment by AJenbo** [comment]
Yes, it's 5% complete

**Comment by tsunamistate** [comment]
@SourceCodeDeleted there's no existing Ukrainian TL, if that's what you're asking. This is a new initiative by me. Hopefully I'll make it to 1.4.0.
More games need to be in Ukrainian, since you can count official localizations on one hand!

**Comment by SourceCodeDeleted** [comment]
More games need to be in Ukrainian, since you can count official localizations on one hand!

I agree ) 

I started on the russian one , but didn't.do anything with it when I didn't think we would have genders correct for words. However this is no longer the case so I think we can make this quickly.

**Pull request merged**
