### PR TITLE
Fix Flamedart

### PR DESCRIPTION
**Pull request by kphoenix137**
I've made a fix PR for this unique before, however that PR did 2 different things. Let's start smaller and just fix what's blatantly wrong with this unique first, which is that it has a melee item power when it's a ranged weapon.

### CODE REVIEW

**Comment by ikonomov** [comment]
I remember we had a discussion with Stephen about this.  The melee fire affix makes breaking barrels show with the fire effect.  An alternative fix would be to make all elemental bows show that effect when breaking barrels.  Either way, this is just a visual change.  Keeping this bow unique, making it like the others or making all elemental bows show the effect.

**Comment by FitzRoyX** [comment]
I agree that it's a mistake. And it results in a super confusing item description with two fire ranges and no mention of barrels.

The only alternative is that it's a cheap hack for unique fire bows. But you would encounter 30 regular fire bows before you ever found this unique, so how would you playtest and not notice this as a general problem needing a general fix? Either all fire bows should do fire damage to wooden barrels or none of them.

**Comment by StephenCWills** [comment]
> Either all fire bows should do fire damage to wooden barrels or none of them.

Yeah, I think they all should.

**Comment by ikonomov** [comment]
I agree with FitzRoyx and Stephen.  I think it makes sense for all bows to have this effect and remove the duplicate description.

**Comment by AJenbo** [comment]
> I've made a fix PR for this unique before, however that PR did 2 different things. Let's start smaller and just fix what's blatantly wrong with this unique first, which is that it has a melee item power when it's a ranged weapon.

I don't quite understand, it was melee fire damage 1-6, how is the logical fix fire resistance 20%?

**Comment by kphoenix137** [comment]
> > I've made a fix PR for this unique before, however that PR did 2 different things. Let's start smaller and just fix what's blatantly wrong with this unique first, which is that it has a melee item power when it's a ranged weapon.
> 
> I don't quite understand, it was melee fire damage 1-6, how is the logical fix fire resistance 20%?

What?

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
