### PR TITLE
Possible Delete Hero Implementation (redo)

### PR DESCRIPTION
**Pull request by danellos**
This is a redo of an earlier pull request: a possible implementation for the Delete Hero feature, currently lacking as described in #61. 

As before, the goal here was to avoid modifying Devilution's base code and focus this solution on DevilutionX. I want to avoid causing unnecessary merge conflicts until we're sure the game is on par with Retail.

On my previous pull request, a Travis build for macOS failed for i386. I am not sure why, but I was able to compile and run this on macOS Mojave 64-bit. If this fails again, I am happy to take another look to figure out why.

As before, two important notes:
- In the base reference Diablo v 1.09 client, "Yes" is selected by default. In this solution, "No" is selected by default to avoid accidents. If you'd prefer to remain 100% consistent with the retail game, I can remove the code that does this.
-  The DeleteFileA() function was UNIMPLEMENTED(). I am not sure if you had a specific plan for how this would be implemented, but for now, I did it using the standard C approach. One difference from my previous pull request is I realized macOS can't resolve the file path, so I fixed that using the TranslateFileName() function helpfully provided already.

### CODE REVIEW

**Comment by danellos** [comment]
Fixed the macOS i386 build. Apparently the file needed to referenced in the Xcode project. Not sure why that wouldn't have failed the 64-bit build, but here we are :)

**Comment by AJenbo** [comment]
64bit builds use cmake like other platforms, 32bit mac uses a pre-written xcode project.

**Comment by danellos** [comment]
Noticed some minor inconsistencies with the Retail game, and fixed those. Let me know if you'd like me to remove the default "No" behavior.

**Comment by AJenbo** [comment]
Nice work, I made a couple of adjustments to get the font to align correctly and also enable keyboard navigation (a little bit of a hack though).

I also ended up defaulting to Yes for now, but I do think it's a really good improvement for 1.1.0, so good thinking.

**Comment by danellos** [comment]
Awesome, happy to have made a contribution! 

By the way, I re-tested building on both Windows (win32) and macOS Mojave (64-bit). The build processes were fine on both, so I am not sure what was happening there.

**Comment by AJenbo** [comment]
Not sure what you are referring to but I did break builds on master for a little bit today because of a bad merge with upstream. It's all fixed now.

**Comment by danellos** [comment]
Ohhh gotcha, that might have been what I was looking at :) Thank you for all the work here! This project is very exciting.

**Pull request merged**
