### PR TITLE
Improved modifier hints

### PR DESCRIPTION
**Pull request by fwannmacher**
Icons based on https://opengameart.org/content/700-rpg-icons

Removed text from modifier hints and replaced them by new icons. Also the UI was improved by spacing the icons and adding borders.

Screenshot from 2022-01-25 21-00-21
Screenshot from 2022-01-25 21-00-08

### CODE REVIEW

**Comment by julealgon** [comment]
These look really cool.

**Review by AJenbo — APPROVED** [review]
Nice work :)

**Review by glebm — DISMISSED** [review]

**Comment by AJenbo** [comment]
@fwannmacher again sorry I haven't had a lot of time to give to the project over the past few weeks. This PR is on my top 4 of things to get done :)

**Comment by fwannmacher** [comment]
> @fwannmacher again sorry I haven't had a lot of time to give to the project over the past few weeks. This PR is on my top 4 of things to get done :)

No problem ;) take your time

**Review by AJenbo — APPROVED** [review]
Again sorry for the long delay on getting to this :)

**Pull request merged**
