### PR TITLE
Test Hell quest sets using dummies

### PR DESCRIPTION
**Pull request by AJenbo**
This should cover all the quest maps. There are still some edge cases in the map generation that is not covered

image
image

### CODE REVIEW

**Comment by glebm** [comment]
> make[2]: *** No rule to make target '../test/fixtures/hellfire/2-1180526547.dun', needed by 'test/fixtures/hellfire/2-1180526547.dun'.  Stop.

**Review by glebm — DISMISSED** [review]

**Comment by AJenbo** [comment]
Thanks, I totally missed that when looking at the log earlier :D

**Comment by AJenbo** [comment]
> > make[2]: *** No rule to make target '../test/fixtures/hellfire/2-1180526547.dun', needed by 'test/fixtures/hellfire/2-1180526547.dun'.  Stop.

Actually that must be from an old build log, that test currently passes :/

**Comment by AJenbo** [comment]
Alright figured it out, bad quest state again... but only triggered when run under `ctest`, not if run directly via `drlg_l4_test`. So I was unable to reproduce it for a while :/

**Pull request merged**
