### PR TITLE
Highlight items hack

### PR DESCRIPTION
**Pull request by Chance4us**
@qndel 's Highlight items hack

Default behavior:
1. Highlight items ini setting - ON
2. In town - highlight OFF, can be toggled between "always on" an "always off" with the ALT key
3. In dungeon - highlight ON, can be toggled between "always on" an "always off" with the ALT key

Highlight in town or dungeon can be toggled independently.

### CODE REVIEW

**Comment by AJenbo** [comment]
This doesn't appear to do the centering that was in the original PR. We implemented `MeasureSolidHorizontalBounds()` to facilitate this part of the PR with out the hack to the cel rendering.

**Comment by Chance4us** [comment]
> This doesn't appear to do the centering that was in the original PR. We implemented `MeasureSolidHorizontalBounds()` to facilitate this part of the PR with out the hack to the cel rendering.

It's an older version which probably doesn't work with cel rendering.
I somehow managed to make it work without really understanding the code.
So I'm not sure if I can install the centering.

**Comment by julealgon** [comment]
> I somehow managed to make it work without really understanding the code.

Are you proposing a PR for something that you don't understand? Why would you do that?

**Comment by Chance4us** [comment]
> > I somehow managed to make it work without really understanding the code.
> 
> Are you proposing a PR for something that you don't understand? Why would you do that?

Because maybe someone else understands and can improve.

**Comment by qndel** [comment]
This looks like it's based on a super old version of my highlighting, nothing to salvage here 😅

**Comment by Chance4us** [comment]
> This looks like it's based on a super old version of my highlighting, nothing to salvage here sweat_smile

Yes, but your previous doctoral work was still nice.
I can try to modify your newer version also.
You are welcome to contribute ;-)

**Comment by AJenbo** [comment]
@Chance4us if you can migrate the latest version (https://github.com/diasurgical/devilutionX/pull/1345) to use `MeasureSolidHorizontalBounds()` then it would be ready for merging.

**Comment by Chance4us** [comment]
I suggest that we first adjust this PR so that it works with latest build and then apply MeasureSolidHorizontalBounds.

**Comment by AJenbo** [comment]
> I suggest that we first adjust this PR so that it works with latest build

As fare as I can see you already did that, are there any issues?

**Comment by Chance4us** [comment]
As @qndel already noted, this PR is based on an old version for highlighting. So far I have not been able to port the last PR from @qndel. I will try and I already know pretty well that when I am working I will run into difficulties anyway. I will still publish a new PR as soon as possible. The function that caused most of the porting problems is the following.
>> CelClippedDrawTo(out, out.pitch() / 2 - 16, 351, itemanims[i], ItemAnimLs[i], 96);

**Comment by qndel** [comment]
I've created a new PR with it https://github.com/diasurgical/devilutionX/pull/2060

**Comment by Chance4us** [comment]
> I've created a new PR with it #2060

Thanks a lot. I'll ask a couple of questions in the new PR if it's okay.

**Pull request closed without merging**
