### PR TITLE
 Level 15 generation dirty fix for issue #2340 ROFL

### LINKED ISSUE #2340: Broken level generation (catacombs and hell)
While testing a clean up I noticed that we appear to have broken some level generation in a subtle way

Using this save from the original Hellfire:
https://github.com/diasurgical/devilutionX/files/5373942/hsv.zip

Hell level 15:
It would have been impossible for the hero to get to this point with out seeing the area south west of where he is standing in this screen shot.
image

Catacombs level 7:
A free floating closed and open door plus two candle sticks just hanging out in the middle of a room.
image

If someone could help bisect it it would be appreciated :)

### PR DESCRIPTION
**Pull request by Chance4us**
Fixes #2340 lol.

I've been thinking for a long time why IsAnyOf doesn't work properly here. I'm afraid I'll have to leave it to a professional.
Somehow I lost confidence in these types of C ++ functions. We should use this type of programming with great caution. I very much hope that it doesn't negatively affect any more things.

### CODE REVIEW

**Comment by Chance4us** [comment]
For practical testing, the savegame is attached again.
You only need to enter level 15.

[go_up_to_l15.zip](https://github.com/diasurgical/devilutionX/files/6819176/go_up_to_l15.zip)

**Comment by StephenCWills** [comment]
I'd guess it's because the `HorizontalWall()` and `VerticalWall()` functions can update `dungeon[i][j]`. When it's broken out into multiple conditionals, it's not necessarily running the logic in the body of those conditionals just once.

**Comment by Chance4us** [comment]
> I'd guess it's because the `HorizontalWall()` and `VerticalWall()` functions can update `dungeon[i][j]`. When it's broken out into multiple conditionals, it's not necessarily running the logic in the body of those conditionals just once.

It is quite likely. I just hope that, where we have replaced functions in this way, we have not produced new bugs.

**Comment by AJenbo** [comment]
A loop sounds like the right way to clean it up then.

**Comment by qndel** [comment]
my god XD means we have to convert all these fixes into loops xD

**Comment by Chance4us** [comment]
All occurrences of IsAnyOf to check/compare game logic:
[IsAnyOf.txt](https://github.com/diasurgical/devilutionX/files/6820821/IsAnyOf.txt)

All occurrences of IsNoneOf  to check/compare game logic:
[IsNoneOf.txt](https://github.com/diasurgical/devilutionX/files/6820828/IsNoneOf.txt)

IsAnyOf occurences as comment:
./Source/monster.cpp:833:	return IsAnyOf(monster._mAi, AI_SKELBOW, AI_GOATBOW, AI_SUCC, AI_LAZHELP);
--
./Source/monster.cpp:2112:		isdoor = IsAnyOf(Objects[oi]._otype, OBJ_L1LDOOR, OBJ_L1RDOOR, OBJ_L2LDOOR, OBJ_L2RDOOR, OBJ_L3LDOOR, OBJ_L3RDOOR);
--
./Source/monster.cpp:4124:	return IsAnyOf(monster._mAi, AI_LAZARUS, AI_WARLORD, AI_GARBUD, AI_ZHAR, AI_SNOTSPIL, AI_LACHDAN, AI_LAZHELP);
--
./Source/drlg_l3.cpp:1790:		if (IsAnyOf(dungeon[i][y], 7, 10, 126, 129, 134, 136)) {
--
./Source/drlg_l3.cpp:1802:		if (IsAnyOf(dungeon[i][y], 2, 7, 134, 136)) {
--
./Source/drlg_l3.cpp:1814:		if (IsAnyOf(dungeon[x][j], 7, 9, 121, 124, 135, 137)) {
--
./Source/drlg_l3.cpp:1826:		if (IsAnyOf(dungeon[x][j], 4, 7, 135, 137)) {
--
./Source/drlg_l3.cpp:2504:				} else if (IsAnyOf(dPiece[i][j], 150, 152)) {
--
./Source/drlg_l3.cpp:2569:			} else if (IsAnyOf(dPiece[i][j], 150, 152)) {
--
./Source/objects.cpp:3549:		if (IsAnyOf(Objects[v1]._otype, OBJ_CHEST1, OBJ_CHEST2, OBJ_CHEST3, OBJ_TCHEST1, OBJ_TCHEST2, OBJ_TCHEST3) && Objects[v1]._oSelFlag == 0) {
--
./Source/drlg_l2.cpp:1802:			if (IsAnyOf(dPiece[i][j], 541, 178, 551)) {
--
./Source/drlg_l2.cpp:1804:			} else if (IsAnyOf(dPiece[i][j], 542, 553)) {
--
./Source/drlg_l2.cpp:1902:	if (IsAnyOf(predungeon[nX][nY], 65, 66, 67, 69)) {
--
./Source/drlg_l2.cpp:2730:			if (IsAnyOf(predungeon[i][j], 65, 66, 67, 69)) {
--
./Source/drlg_l1.cpp:739:				if (IsAnyOf(dungeon[x][y], 29, 32, 35, 37, 38, 39)) {
--
./Source/drlg_l1.cpp:746:				if (IsAnyOf(dungeon[x][y], 29, 32, 35, 37, 38, 39)) {
--
./Source/drlg_l1.cpp:753:				if (IsAnyOf(dungeon[x][y], 29, 32, 35, 37, 38, 39)) {
--
./Source/drlg_l1.cpp:970:			if (IsAnyOf(dPiece[i][j], 12, 71, 321, 211, 341, 418)) {
--
./Source/drlg_l1.cpp:972:			} else if (IsAnyOf(dPiece[i][j], 11, 249, 325, 344, 331, 421)) {
--
./Source/drlg_l4.cpp:522:	if (IsAnyOf(dungeon[i + x][j], 10, 12, 13, 15, 16, 21, 22) && x > 3)
--
./Source/drlg_l4.cpp:543:	if (IsAnyOf(dungeon[i][j + y], 8, 9, 11, 14, 15, 16, 21, 23) && y > 3)
--
./Source/drlg_l4.cpp:643:			if (IsAnyOf(dungeon[i][j], 10, 12, 13, 15, 16, 21, 22)) {
--
./Source/drlg_l4.cpp:650:			if (IsAnyOf(dungeon[i][j], 8, 9, 11, 14, 15, 16, 21, 23)) {
--
./Source/engine.h:48:bool IsAnyOf(const V &v, X x)
--
./Source/engine.h:54:bool IsAnyOf(const V &v, X x, Xs... xs)
--
./Source/engine.h:56:	return IsAnyOf(v, x) || IsAnyOf(v, xs...);

IsNoneOf occurences as comment:
./Source/drlg_l3.cpp:1868:				if (IsNoneOf(dungeon[i + 1][j], 130, 132, 133, 134, 136, 138, 140) && IsNoneOf(dungeon[i - 1][j], 130, 132, 133, 134, 136, 138, 140)) {
--
./Source/drlg_l3.cpp:1881:				if (IsNoneOf(dungeon[i][j + 1], 131, 132, 133, 135, 137, 138, 139) && IsNoneOf(dungeon[i][j - 1], 131, 132, 133, 135, 137, 138, 139)) {
--
./Source/objects.cpp:5013:		if (IsNoneOf(testObject._otype, OBJ_CRUX1, OBJ_CRUX2, OBJ_CRUX3))
--
./Source/drlg_l4.cpp:158:			if (IsNoneOf(dungeon[x][y], 3, 4, 8, 15)) {
--
./Source/engine.h:60:bool IsNoneOf(const V &v, X x)
--
./Source/engine.h:66:bool IsNoneOf(const V &v, X x, Xs... xs)
--
./Source/engine.h:68:	return IsNoneOf(v, x) && IsNoneOf(v, xs...);

**Comment by Chance4us** [comment]
Any idea why the text has enlarged on its own?

**Comment by obligaron** [comment]
> 
> 
> Any idea why the text has enlarged on its own?

In markdown you can define headings if you add `#` before the text

# Heading 1 `#`

## Heading 2 `##`

### Heading 3 `###`

**Comment by Chance4us** [comment]
I want to keep the text small.

**Comment by qndel** [comment]
check if https://github.com/diasurgical/devilutionX/pull/2381 fixes it

**Comment by Chance4us** [comment]
> check if #2381 fixes it

@qndel I can confirm it fixes the issue.
Do you agree that we should definitely investigate all other occurrences of IsAnyOf and IsNoneOf for unchanged game logic?

**Comment by qndel** [comment]
I already did, this was the only one with possible side effect

**Pull request closed without merging**
