### PR TITLE
Rename Korean/Romanian translation files so they are used in fallback…

### LINKED ISSUE #3641: Find best matching language
Currently if a user's system language is set to `fr_CA` it will automatically match the `fr` translation after failing to locate a Canadian specific dialect. But for `pt_PT` it will fall back to `en_US` instead of matching `pt_BR`, which would be a better solution in most cases.

Since scanning for files isn't to portable and we already need a curated list, it might be good to change `HasTranslation()` to simply use the list from https://github.com/diasurgical/devilutionX/blob/master/Source/options.cpp#L758

This way we can simply match the string lengths (first 5, then 2) when looking for matches.

### PR DESCRIPTION
**Pull request by ephphatha**
… resolution

fixes #3641

### CODE REVIEW

**Comment by ephphatha** [comment]
The po files have one changed line each, `"Language: ko_KR\n"` > `"Language: ko\n"` (and ro_RO > ro)

**Comment by AJenbo** [comment]
> The po files have one changed line each, `"Language: ko_KR\n"` > `"Language: ko\n"` (and ro_RO > ro)

Sure, if you ignore that all the line endings where changed from LF to CRLF :D

**Review by AJenbo — APPROVED** [review]

**Comment by ephphatha** [comment]
Thanks for that pickup, I think I've got tortoisediff assuming native style line endings while visual studio is set up to use source line endings so if I edit the diff directly I need to remember to set the line ending explicitly -_-

**Comment by AJenbo** [comment]
Thanks for making the change :)

**Pull request merged**
