### PR TITLE
Update Discord SDK

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by glebm** [comment]
@heinermann Any idea what's up with the build errors?

**Comment by glebm** [comment]
I think we should simply disable DISCORD_INTEGRATION for mingw builds since it's not supported there anyway

**Comment by heinermann** [comment]
What are the build errors?

**Review by AJenbo — APPROVED** [review]
Sounds like we should maybe consider not using MinGW for the next release :(

**Pull request merged**
