### PR TITLE
Get rid of SCREEN_X / SCREEN_Y

### PR DESCRIPTION
**Pull request by glebm**
GlobalOutputBuffer() now returns a clipped subregion

### CODE REVIEW

**Comment by AJenbo** [comment]
Did you test the screenshot function this time :)

**Comment by glebm** [comment]
I did not, give me a moment :sweat_smile:

**Comment by glebm** [comment]
Screenshot works :+1:

**Comment by AJenbo** [comment]
Nice to have things more logical in the majority of files rather than having to constantly take the unseen into account.

**Pull request merged**
