### PR TITLE
CMake: Split out platform libraries

### PR DESCRIPTION
**Pull request by glebm**
Most of the platform-specific stuff apart from packaging is now defined in the platform CMake files.

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Things are slow starting to look managable :)

**Comment by glebm** [comment]
Rebased after the merge of #3819, needs re-approval

**Comment by glebm** [comment]
Actually, found another thing to clean up

**Review by AJenbo — DISMISSED** [review]

**Comment by glebm** [comment]
Done

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
