### PR TITLE
New Iconset for AmigaOS

### PR DESCRIPTION
**Pull request by samo79**
I have created an iconset for DevilutionX, both folder and game icon are included. 
Fell free to commit it in repository

Link:
http://s000.tinyupload.com/index.php?file_id=03435418993704798118

### CODE REVIEW

**Comment by AJenbo** [comment]
@samo79 Thanks for the suggestion, we definitely want to merge the Amiga and BE support, but this PR is not ready yet for a few reasons:

- It's too big for a single PR, it needs to be broken up in smaller changes.
- It has code that is obviously not ready to be merged yet.
- Your not the author of the code, I expect that a PR will be created by the original authors once they feel it's ready.
- It's failing all build tests.

Maybe what you want to do instead is send a suggestion with the new icon as a separate PR for the AmigaPorts repo, or create an issue referring to the icon you created and have others help you integrate it.

**Comment by samo79** [comment]
Mmm, the file i sent it's just an archive with an iconset in Amiga format style, there is no code at all,  just plain files ..
I tried to open a pull request in the amiga repository of the project, but.. apparently it was posted here instead.. into the main repo :-)

Aniway, as i said the archive only contain an iconset, so eventually you may include it without any problem, consider that once done everything about the amiga fork n development could be merged

**Comment by AJenbo** [comment]
Be aware that to create a PR you have to first create a fork and commit the files via git (or GitHub web interface. What you have created here is a request to merge the amiga for into devilutionx. The alternative as mentioned is to create an issue with a link to the icons that someone else can then commit to the repo.

**Comment by samo79** [comment]
All right, i will open a new issue instead..
Btw, it seems i can't attach archives in lha format, github is unable to accept them

**Pull request closed without merging**
