### PR TITLE
Improve .desktop files and add Hellfire flavor to CMake build system

### PR DESCRIPTION
**Pull request by M0Rf30**
This add Hellfire related desktop resources within CMakeLists file, in order to simplify the packaging. Successfully tested on Arch Linux with these instructions:
```
  cmake .. \
  -DCMAKE_INSTALL_PREFIX="/usr" \
  -DBINARY_RELEASE=ON \
  -DVERSION_NUM=1.1.0

  cmake --build .

  DESTDIR=target cmake --install .
```

### CODE REVIEW

**Comment by AJenbo** [comment]
`-DHELLFIRE=ON` no longer does anything, the code has been unified. Instead, you can use a runtime argument to force Diablo mode even when Hellfire (MPQs) is instealled.

**Comment by M0Rf30** [comment]
> `-DHELLFIRE=ON` no longer does anything, the code has been unified. Instead, you can use a runtime argument to force Diablo mode even when Hellfire (MPQs) is instealled.

Ok, `-DHELLFIRE` parameter removed and yet it works like a charm :smile:

**Comment by M0Rf30** [comment]
Can you give me some details about devilutionx.mpq in this repo? Is it supposed to work also under `/usr/share/diasurgical` path?

**Comment by AJenbo** [comment]
> Can you give me some details about devilutionx.mpq in this repo? Is it supposed to work also under `/usr/share/diasurgical` path?

It should reside in the same folder as the other MPQ files.

**Review by AJenbo — APPROVED** [review]

**Review by Josegto1 — APPROVED** [review]

**Comment by AJenbo** [comment]
Looks like you changed the line endings in the CMake file :face_with_head_bandage:

**Comment by AJenbo** [comment]
This is your branch/PR go crazy with force push, plz. Nothing worse than having to rebase someone else's 75 merge commits.

**Comment by AJenbo** [comment]
Thanks for adding the MPQ to the packages that a load off my shoulders :)

**Comment by M0Rf30** [comment]
> Thanks for adding the MPQ to the packages that a load off my shoulders :)

Now DevilutionX shines on my desktop
image

But I'm just thinking about devilutionx.mpq. Its more appropriate path (POSIX compliant) should be something like `/usr/share/diasurgical/devilutionx.mpq`, mimicing the `~/.local/share/diasurgical` user-owned path

Actually it's place under `/usr/bin` :pensive:

**Comment by Trihedraf** [comment]
I put the mpq there because it it was with the executable and I didn’t know if DevilutionX read anywhere else for the mpqs because the readme says that mpqs have to be in the same directory as the executable. I’ll look into it tonight.

**Comment by AJenbo** [comment]
It will search for diabdat.mpq/spawn.mpq in `./`, `~/.local/share/diasurgical` or a folder you specify with `--data-dir`. Once found it will look for all other MPQ files in that same folder. So you can't have them spread out over multiple locations.

**Comment by Trihedraf** [comment]
So will having it packaged like it is be a good idea? Or should it not be in the Linux package and we put it in the readme to download it separately and so that it goes with the diabdat.mpq

**Comment by M0Rf30** [comment]
IMHO, should be a required resource and a mandatory packaged one. But, because it's devilution custom resource I would suggest to bind to a fixed/different path from diabdat.mpq one. I would like to only choose on diabdat.mpq path, not on a "mandatory" resource path. I don't know if my motivation it's clear. Let's take for example a software like scummvm.
It has its resources under `/usr/share/scummvm` and after you can decide the custom location to load the game from.

**Comment by AJenbo** [comment]
> So will have it packaged like it is be a good idea? Or should it not be in the Linux package and we put it in the readme to download it separately and so that it goes with the diabdat.mpq

Put it in the archive next to the deb/rpm installers and let people drop it next to the other MPQs that they have to provide. Tbh the Unix way of splitting applications up is a headache for maintainers. Personally I just drop all my MPQ files in `~/.local/share/diasurgical` there is only one user account on my machine for playing Diablo anyway.

If it's not in the main download and just mentioned in the readme less than 1% of users will probably ever know it exists.

**Comment by AJenbo** [comment]
image

**Comment by Trihedraf** [comment]
Ok. I’ll set that up. Should we change the Linux readme to mention it as well?

**Comment by AJenbo** [comment]
I would probably wait with that until I have added the rest of the content to it.

**Comment by M0Rf30** [comment]
Papirus icon request for hellfire triggered here after the devilutionx one successfully merged:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2587

Regards guys
And thanks for this amazing project as always. See you soon

**Pull request merged**
