### PR TITLE
German translation by Baracudus

### PR DESCRIPTION
**Pull request by ChaosMarc**
I opened this PR so that all people who want to help with the German translation can pitch in. I've just added 3 translations of my own for now, but will add more every now and then when I find the time. For submissions please create PRs to my branch and I will merge them asap.

As all who had contact with the German language know, it's a bit complicated when it comes to genders and the endings of adjectives. This is most noticeable with item prefixes, e.g. if there was a prefix "Small" there would be more than one German translation depending on the item's gender (female: "Kleine", male: "Kleiner", neutral: "Kleines"). At the moment gendered translations are not supported so I'm proposing to use the base form of the adjectives (e.g. "Klein" which is almost always wrong) and marking the translation with "Needs work / Fuzzy" (optionally the different adjectives can be added as a comment like I did with "Bent" but I'm not sure if it's worth it). For the handling of the "of" in suffixes see [Translations/glossary.md](https://github.com/diasurgical/devilutionX/blob/master/Translations/glossary.md).

### CODE REVIEW

**Comment by AJenbo** [comment]
Note that any translation marked as fuzzy will not appear in game.

**Comment by joewis** [comment]
Translation to German while preserving the tone will be a challenge.

"Runter" sounds a bit funny to my German ears (rhymes with "kunter" and that's more associated with Pipi Longstocking).
Perhaps "Hinab in die Hölle" and "Hinab zu Diablo" sounds better, as well as "Hinauf in die Stadt" instead of "Rauf".

Also "Gillian die Barfrau" may be more fitting than Kellnerin.

**Comment by ChaosMarc** [comment]
I was thinking the exact same things but those are the "official" translations used in the PSX Version. Not sure if we want to use them at all or go or own way. Some of the PSX translations are horribile. "Bent" was translated with "Pfuschen" instead of "Verbogen" 😂

**Comment by AJenbo** [comment]
We don't maintin other bugs either

**Comment by joewis** [comment]
> I was thinking the exact same things but those are the "official" translations used in the PSX Version. Not sure if we want to use them at all or go or own way. Some of the PSX translations are horribile. "Bent" was translated with "Pfuschen" instead of "Verbogen" 😂

Sounds like that translation was verpfuscht...

**Comment by Baracudus** [comment]
Update in the Main thread!

**Comment by ChaosMarc** [comment]
I have pushed the unmodified translation provided by @Baracudus from [here](https://github.com/diasurgical/devilutionX/issues/905#issuecomment-886198499) overwriting my previous changes. so we can start fresh with his nearly complete version

**Pull request merged**
