### PR TITLE
aarch64-linux-gnu cross-compilation

### PR DESCRIPTION
**Pull request by glebm**
Allows one to easily cross-compile for aarch64 on a Debian/Ubuntu host.
Also adds a GitHub Actions build with automated upload on release.

### CODE REVIEW

**Comment by Trihedraf** [comment]
Looks way better than mine 👍 🤦
I don't know if the appimage works for arm, it gives me a `cannot execute binary file: Exec format error`.
And the regular executable is missing libfmt8 as only libfmt7 is in default raspbian repos. I don't know if that's changeable when building or just needs to be upgraded on the pi manually.

**Comment by glebm** [comment]
I've updated it to not use the system libfmt, so it should work now.
As for AppImage, turns out it produces an x86_64 binary so I've disabled it for now.

**Comment by AJenbo** [comment]
Not finding libfmt was a common complaint from Pi users.

**Comment by AJenbo** [comment]
nice that you also fixed the appimage script

**Review by Trihedraf — APPROVED** [review]

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
