### PR TITLE
Use the dungeon_type enum where possible

### PR DESCRIPTION
**Pull request by joankaradimov**
This replaces some numbers with `dungeon_type` enum values.

### CODE REVIEW

**Comment by AJenbo** [comment]
Thanks for the clean up, but since this is for the base engine please make the PR against https://github.com/diasurgical/devilution, the change will then be synced to DevilutionX at a later point.

**Comment by joankaradimov** [comment]
Sorry, I thought that the [devilution](https://github.com/diasurgical/devilution) repo is merely for reference and no development happens in it.

I've applied the patches there and made the [pull request](https://github.com/diasurgical/devilution/pull/1282). But two questions bother me, though:
1. If you are developing the base engine actively, why not have them both in the same repo? Maybe as separate branches. It would be easier to apply patches that way.
2. Do you allow for refactoring in the base engine repo? Blizzard North did a great job with the game, but the source code is quite horrible. I can't imagine working with that code base without some major changes in the original `Source` directory.

**Comment by AJenbo** [comment]
No worries. The goal of Devilution is to recreate the original source, the goal of DevilutionX is to modernize the code, the different goals is why they are split up in to separate projects/repos.

For now we try to keep to the auxiliary code when working on DevillutionX since Devilution is still seeing a lot of changes and we want to avoid merge conflicts. However I expect that this will change soon since the main milestone has nearly been reached: https://github.com/diasurgical/devilution/milestone/3
This means that all logic is correct and so we have a decent base for doing refactoring even if more code clean up is done upstream. There may still be some changes that are beneficial like operating on the wrong data and fixing compiler warnings as well as some code clean ups that doen't affect the logic, so we will have to way the situation for the moment.

Additionally DevilutionX will also work on fixing the original bugs (we know of 28 simple issues from looking at the code), adding QOL improvements and mod support (Hellfire would probalby be the first goal here).

Hope this gives some clarity of the different goals :)

**Comment by joankaradimov** [comment]
> adding QOL improvements and mod support (Hellfire would probalby be the first goal here).

Accidentally I've been working on getting the Monk to work. I got the game to load the town and dungeons. But the graphics are broken, there are no SFX, and he doesn't have his search skill. But it's a start. And it was fairly simple to do :)

> This means that all logic is correct and so we have a decent base for doing refactoring even if more code clean up is done upstream

So pull requests with code refactoring and/or major changes in the `Source` directory are not welcome until milestone 3 is reached?

**Comment by AJenbo** [comment]
I pretty much consider Milstone 3 complete, so some refactoring could start, but I do think we should be conservative and maybe wait for memory layout and warnings to also be solved before doing big changes. But probably it's bet to evaluate on a case by case basis.

At the moment I'm working on refactoring the rendering code, it's still in an early and pretty rough state, but I hope to end up with something that is both more portable and sane:
https://github.com/diasurgical/devilutionX/compare/render

**Pull request closed without merging**
