### PR TITLE
Greek translation - final draft

### PR DESCRIPTION
**Pull request by xGnoSiSx**
Hiya,

This is the final version with all the strings translated.

Strings for the credits, error messages and contributions are marked fuzzy, but the texts are translated ok. This is due the problematic font.

I'll provide an update in 15-30 days once I get back the feedback from proofing, QA and testing - for corrections. Hopefully by then we'll have the 1.4 and the stash!!

### CODE REVIEW

**Comment by AJenbo** [comment]
@xGnoSiSx if you have time to update the translation now would be a good time to make it for the next release :)

There are about 120 lines that needs an update.

**Comment by AJenbo** [comment]
There's going to be and update to DevilutionX soon so now would be a good time to update the translation if you have time :)

**Comment by xGnoSiSx** [comment]
Yes, I'll have a look this weekend. When are you releasing the update?

**Comment by AJenbo** [comment]
Start of Juli I expect

**Comment by xGnoSiSx** [comment]
I should make it! Did you guys manage to fix some of the unicode limitations/bugs from the issues backlog?

**Comment by AJenbo** [comment]
I think we solved most of them, but there are still some issues on the Credits screen and no gendered language support yet

**Comment by xGnoSiSx** [comment]
Nice! I'll give it a spin. Was the string lenght expanded for unicode in magic item descriptions?

**Comment by AJenbo** [comment]
Yes all such limits should have been solved.

**Pull request merged**
