### PR TITLE
amiga.cmake: Remove `find_package(ZLIB)`

### PR DESCRIPTION
**Pull request by glebm**
We're not using the system zlib on Amiga

### CODE REVIEW

**Comment by AJenbo** [comment]
Then why did the build fail :thinking:

**Comment by StephenCWills** [comment]
libpng is looking for it. We may need to make use of the `PNG_BUILD_ZLIB` option.

https://github.com/glennrp/libpng/blob/0a158f3506502dfa23edfc42790dfaed82efba17/CMakeLists.txt#L45-L52

**Comment by AJenbo** [comment]
The way things are currently PNG is only used for SDL2 targets so if it's not disabled there it probably should be.

**Comment by glebm** [comment]
We should stub out the package finder when we build zlib from source.

**Comment by glebm** [comment]
Filed #5504 for the separate issue of avoiding SDL_image and png when targeting SDL1.

**Review by arczi84 — DISMISSED** [review]
Works fine.

**Comment by glebm** [comment]
Thanks @StephenCWills! I won't have access to a PC until tomorrow night, please squash the commits when merging!

**Comment by StephenCWills** [comment]
@glebm Should we add `find_package(zlib REQUIRED)` to `Dependencies.cmake`? All the other `DEVILUTIONX_SYSTEM_*` dependencies have it. Like, if you compare it to bzip in the following snippet.

https://github.com/diasurgical/devilutionX/blob/77ded34137f8937e0133572518c22f8e40459ad9/CMake/Dependencies.cmake#L6-L20

**Review by AJenbo — APPROVED** [review]

**Review by StephenCWills — APPROVED** [review]

**Comment by glebm** [comment]
@StephenCWills Actually we should probably remove the `find_package(BZip2 REQUIRED)` call. It is not used by DevilutionX directly -- it's a dependency of libmpq, which also calls `find_package(BZip2 REQUIRED)`.

**Pull request merged**
