### PR TITLE
Stream music instead of loading it all at once

### PR DESCRIPTION
**Pull request by glebm**
RAM usage (my beefy desktop):

* Town: 176 MiB -> 121 MiB
* Cathedral: 191 MiB -> 138 MiB

Performance: 1170 FPS -> 1150 FPS

### CODE REVIEW

**Comment by joewis** [comment]
Is this small FPS penalty consistently there or just a random fluctuation? Asking for less beefy hardware...

**Comment by glebm** [comment]
@joewis It's not very consistent so hard to say. Either way 1150/1170 is <2%.

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
wold this approach also work for the videos and dialogs?

**Comment by malvarenga123** [comment]
Should this be enabled for PC? I can see the advantage for consoles/handhelds that have very limited RAM. A peak hard drive usage on PC would glitch the stream now, wouldn't it?

**Comment by galaxyhaxz** [comment]
It is enabled for everything. The original game streamed the same way, I don't think having to read the MPQ more often should be an issue.

**Comment by AJenbo** [comment]
This is also going to improve load time on PC. If your PC is unable to pull 75kb/s for the in-focus task it's probably hitting some other limits already. You can turn the music off if you think this is too much for your PC. Besides, modern systems will pull active content into RAM so for PC the only difference is probably going to be a slightly faster load time.

**Comment by galaxyhaxz** [comment]
Even computers in 1996 could stream xD

**Comment by malvarenga123** [comment]
> This is also going to improve load time on PC. If your PC is unable to pull 75kb/s for the in-focus task it's probably hitting some other limits already. You can turn the music off if you think this is too much for your PC. Besides, modern systems will pull active content into RAM so for PC the only difference is probably going to be a slightly faster load time.

I do have some trouble with other games (like Diablo 3) that require to be accessing the disk all the time, but I don't think Diablo 1 would have any problems. In fact, I always wondered why couldn't the whole diablo.mpq be loaded into memory, considering it's only ~600 MB.

**Comment by glebm** [comment]
> wold this approach also work for the videos and dialogs?

Videos are probably streamed already.

It should be easy to migrate dialogs to use `SFileRw_FromStormHandle` but I haven't looked into it.

**Comment by AJenbo** [comment]
> > wold this approach also work for the videos and dialogs?
> 
> Videos are probably streamed already.

I was thinking in terms of simplify the code and use sdl mixer instead of raw sdl

**Pull request merged**
