### PR TITLE
Multiplayer: Enable Magic Rock Quest

### PR DESCRIPTION
**Pull request by obligaron**
Contributes to #926

With the already done changes for multiplayer sync this one was pretty easy. 😄

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
Can't wait to play test this in the weekend :)

**Comment by glebm** [comment]
> just need to figure out how to compile the updated

You can grab them from the pre-relase here: https://github.com/diasurgical/devilutionx-assets/releases

**Comment by qndel** [comment]
> > just need to figure out how to compile the updated
> 
> You can grab them from the pre-relase here: https://github.com/diasurgical/devilutionx-assets/releases

or https://github.com/artifacts-storage/devilutionx-artifacts/blob/master/data/devilutionx.mpq

**Comment by yuripourre** [comment]
Thanks @glebm and @qndel 
The pre-release one worked like a charm.

**Pull request merged**
