### PR TITLE
Switch next

### PR DESCRIPTION
**Pull request by AJenbo**
This is just for testing that things build before replacing #181

### CODE REVIEW

**Comment by AJenbo** [comment]
@glebm would you be willing to help out with sorting out the SDL1 implementation for this branch? It looks to be mostly just SDL_GameControler related things at this point. For now they can just be `#ifndef SDL1` so that it passes the build test, then we can work on some kind of alternate implementation in a PR that focuses on the game controller code alone.

**Comment by glebm** [comment]
@AJenbo Sure, on it. Is there a developer discord for devilutionX btw?

**Comment by AJenbo** [comment]
@glebm the discord link is in top of the ReadMe, I'm surprised how many miss it :)

**Comment by rsn8887** [comment]
Concerning 3. already implemented ages ago (opens virtual keyboard for name entry)

Concerning 2. I think this should be skipped as it already is. There's no system function on Switch to open a dialog box of any kind. Unless you want to implement a message box yourself, drawing it yourself, handle input yourself etc.

**Comment by AJenbo** [comment]
Actually I might have a solution for 2, my Mac is apparently also affected so I can test it there. What happens if we call the dialog code at all?

**Comment by rsn8887** [comment]
If you are thinking SDL would provide a dialog box, no. Not on Switch.

**Comment by AJenbo** [comment]
Yeah I understand, we where already using SDL2. It's the same on my 2002 Mac. Do you get an error in the terminal (can't remember if you have access to it) when trying to create the dialog? I get something like "no messaging system available"

**Pull request closed without merging**
