### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Durgesh4993**

### CODE REVIEW

**Comment by qndel** [comment]
stop

**Comment by Durgesh4993** [comment]
@qndel What happen

**Comment by qndel** [comment]
why would you close previous PR and open a new one for no reason? ...

**Comment by Durgesh4993** [comment]
@qndel In last PR the link is was not doing properly work, thats why

**Comment by julealgon** [comment]
> why would you close previous PR and open a new one for no reason? ...

Probably unfamiliar with how git works... I've seen too many people do this by now because they don't know how to change their branch or fix some issues in a PR 😅

**Comment by AJenbo** [comment]
The Readme is so short I don't think there really is a point to this, and to have it proper it shoulf come after the splash image not before.

**Comment by AJenbo** [comment]
... also github does this automatically for all md files :D

image

**Pull request closed without merging**
