### PR TITLE
Adding offset to enable items being able to be equipped on lower resolutions

### PR DESCRIPTION
**Pull request by stefanmielke**
Fixes problem found by @glebm in https://github.com/diasurgical/devilutionX/issues/1885#issuecomment-840274498.

_Did not fix the underlying cause. Opened https://github.com/diasurgical/devilutionX/issues/1962 to fix that._

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
fixing the underlying issue would be better, but since it is in the controller code I can accept this for now.

**Comment by stefanmielke** [comment]
> fixing the underlying issue would be better, but since it is in the controller code I can accept this for now.

I did try to find the code that was causing the issue, but was unable to find where it is :(

**Comment by glebm** [comment]
By the way, debugging this project with VS Code is very easy (no configuration required).
In VS Code, press Ctrl + Shift + P, then "CMake: Debug" to launch a debugger session

**Comment by stefanmielke** [comment]
> By the way, debugging this project with VS Code is very easy (no configuration required).
> In VS Code, press Ctrl + Shift + P (which brings up the action menu), then "CMake: Debug" to launch a debugger session

I'm using CLion for Linux/Windows and VSCode only for PSP (CLion doesn't have a way for me to use psp-make instead). The problem was more that I tried to find a method with a name that would do it, but no breakpoint hit there (mostly tried on inv.cpp, but I'm not sure if that's the correct place).

**Comment by glebm** [comment]
You could trace it down all the way from the mouse click handler

**Pull request closed without merging**
