### PR TITLE
Update 3rdParty/asio

### PR DESCRIPTION
**Pull request by glebm**
Updates ASIO to the current master, https://github.com/chriskohlhoff/asio/tree/57577c6db46a4e2de5351af2b185bf52696699a9

The only DevilutionX patch was Haiku support which has been upstreamed since.

### CODE REVIEW

**Comment by qndel** [comment]
Doesn't solve the double error messages issue : P

**Comment by AJenbo** [comment]
@qndel can you send your fix to https://github.com/chriskohlhoff/asio as a pr there :)

**Comment by AJenbo** [comment]
@glebm how about pulling this in via CMake, it isn't even needed for all targets.

**Comment by glebm** [comment]
@AJenbo I don't have time right now, someone else is welcome to

**Pull request closed without merging**
