### PR TITLE
Initial commit for Traditional Chines translation

### PR DESCRIPTION
**Pull request by 4aron5un**
Initial commit, I will make further improvements.

### CODE REVIEW

**Comment by AJenbo** [comment]
Nice

**Comment by AJenbo** [comment]
P.s. if you have time it would be good if you could also translate the Android App install instructions:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

**Comment by 4aron5un** [comment]
Sure, no problem. 😄

**Comment by AJenbo** [comment]
@4aron5un the test version of the CJK font should be ready this weekend:

image

image

I hope this looks correct to you :sweat_smile:

**Pull request merged**
