### PR TITLE
Allow shift+click moving to belt

### PR DESCRIPTION
**Pull request by julealgon**
This introduces a new feature to allow easily moving consumable items from the inventory to the belt by shift+clicking the item.

It partially implements #844

### CODE REVIEW

**Comment by julealgon** [comment]
Since this depends on https://github.com/diasurgical/devilutionX/pull/849 and lacks automated tests, marking as `draft`.

**Comment by AJenbo** [comment]
inv.cpp is now 1% tested if that makes you feel any better :D

**Comment by galaxyhaxz** [comment]
take one down, pass it around....

99% of code left to test...

**Comment by julealgon** [comment]
Rebased and adjusted for new changes.

**Comment by AJenbo** [comment]
Ready for another rebase

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
