### PR TITLE
Text inputs: Selection, copy, cut

### PR DESCRIPTION
**Pull request by glebm**
Adds shift selection, Ctrl+C and Ctrl+X handling, and Ctrl/Alt word navigation.

image

Also fixes left-right movement for non-ASCII characters.

### CODE REVIEW

**Comment by AJenbo** [comment]
Diablo: Office

**Comment by glebm** [comment]
Maybe not so important for chat but will be great for the quake-style console :)

**Comment by AJenbo** [comment]
Not going to disagree, but I don't even think Quake console has copy paste or selecting text... Of cause I don't think it lets you write QuakeC ingame either

**Comment by kphoenix137** [comment]
Finally!

**Review by AJenbo — APPROVED** [review]
A very feature complete implementation :eyes:

**Pull request merged**
