### PR TITLE
Implement unused Stormshield graphic

### PR DESCRIPTION
**Pull request by kphoenix137**
screen68
Note: This may not update the graphic for character files already used in DevilutionX

### CODE REVIEW

**Comment by kphoenix137** [comment]
Note: This may not update the graphic for character files already used in DevilutionX

**Comment by qndel** [comment]
think it could be a good moment to replace all these magic numbers with enums

**Comment by kphoenix137** [comment]
> think it could be a good moment to replace all these magic numbers with enums

It would make the table look extremely messy since INVCURS doesn't always fall in the same column

**Comment by qndel** [comment]
> > think it could be a good moment to replace all these magic numbers with enums
> 
> It would make the table look extremely messy since INVCURS doesn't always fall in the same column

so adjust it with spaces? :D

**Review by ephphatha — APPROVED** [review]
image
Same with the war bow, old versions use the graphic assigned when the item was dropped so this doesn't break anything (this screenshot was taken on devX master).

**Comment by FitzRoyX** [comment]
The odd thing about this graphic is how it appears to be from a 3d render while the others are hand drawn. It's also at a different angle. So it may have gone unused for consistency reasons.

**Comment by ikonomov** [comment]
> The odd thing about this graphic is how it appears to be from a 3d render while the others are hand drawn. It's also at a different angle. So it may have gone unused for consistency reasons.

I agree.  The reason they chose not to use this graphic seems to be a valid one.

**Comment by AJenbo** [comment]
Closing based on feedback and my own feelings.

**Pull request closed without merging**
