### PR TITLE
Update SDL_audiolib to fix mono->stereo conversion

### PR DESCRIPTION
**Pull request by glebm**
https://github.com/realnc/SDL_audiolib/commit/0fa26cf4e48ed21e696e60ffc88a586ced9fd6fe

### CODE REVIEW

**Comment by AJenbo** [comment]
odd i just got dome angry liker errors when trying the same thing, maybe i should have cleared my cache

**Comment by glebm** [comment]
The cache shouldn't need to be clear manually; perhaps you didn't set `URL_HASH MD5` correctly?

**Comment by AJenbo** [comment]
Most likely i partially deleted the cached content, but not all of it.

**Comment by glebm** [comment]
@AJenbo ah, yeah, looks like it cached the old build

**Pull request merged**
