### PR TITLE
Fix 0 charge staff in speed spell

### PR DESCRIPTION
**Pull request by kphoenix137**
Fixes https://github.com/diasurgical/devilutionX/issues/6149

### CODE REVIEW

**Comment by FitzRoyX** [comment]
I don't understand the inconsistency. A staff can be recharged, a scroll can't. 0 charges is equivalent to a lvl 0 spell that you've learned but you just can't cast anymore.

**Comment by StephenCWills** [comment]
Qndel described it pretty succinctly in the issue. The spell icon shows up after Save/Load. It doesn't show up if you don't Save/Load.

**Comment by kphoenix137** [comment]
> I don't understand the inconsistency. A staff can be recharged, a scroll can't. 0 charges is equivalent to a lvl 0 spell that you've learned but you just can't cast anymore.

https://github.com/diasurgical/devilutionX/assets/68359262/c4066024-ed65-473b-b778-97ffd16ee995

**Review by qndel — APPROVED** [review]

**Comment by AJenbo** [comment]
<3

**Pull request merged**
