### PR TITLE
Update bg.po

### PR DESCRIPTION
**Pull request by NikoVP**
Update to latest master, for real this time...

### CODE REVIEW

**Comment by AJenbo** [comment]
Nice and clean :)

**Comment by AJenbo** [comment]
@NikoVP there's going to be and update to DevilutionX soon so now would be a good time to update the translation if you have time :)

**Comment by NikoVP** [comment]
Hi! @AJenbo Will do, but I am currently away on work trip and won't be able to get access to my Pc until the weekend. Hopefully I'll make it before the deadline...

**Comment by AJenbo** [comment]
Cool, hope you are having a good time :)

**Pull request merged**
