### PR TITLE
General Android upgrades

### PR DESCRIPTION
**Pull request by tsunamistate**
* SDL2 to 2.30.2 bugfix
* Gradle to 8.7
* Android Gradle plugin to 8.3.2

Playtested to my Google Pixel 2, Android 11

@AJenbo worth cherry-picking into 1.5.3?

### CODE REVIEW

**Comment by AJenbo** [comment]
Are there relevant bugfixes?

**Comment by tsunamistate** [comment]
2.30.1 has `Fixed the keyboard automatically popping up when resuming an application on Android`
But it's mostly Linux and controller fixes
https://github.com/libsdl-org/SDL/releases/tag/release-2.30.1
https://github.com/libsdl-org/SDL/releases/tag/release-2.30.2

**Comment by AJenbo** [comment]
Hm yeah I think that would be good to have, but we need to solve the issue with building for Mac and iPhone. It might be random though since it's saying the compiler is missing as fare as I can tell..

**Comment by StephenCWills** [comment]
The MacOS version used by `macos-latest` has jumped from `12.7.4` to `14.4.1`. We can upgrade the cache version like I did in https://github.com/diasurgical/devilutionX/pull/7104/commits/a6c7d8e6982bbce5318cb19b1800eff79e4dc4bf, but it seems the build architecture has changed to arm64 so the Discord library cannot be linked.

According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, we can continue to use `macos-12`, although they are on the cusp of removing support for `macos-11` so we may have to revisit this eventually.

**Comment by AJenbo** [comment]
Lets use macos-11 for 1.5.3, then we can consider what we do for 1.6.0 after that.

**Comment by StephenCWills** [comment]
Assuming you truly meant `macos-11` and not `macos-12`, looks like it's working.

**Pull request merged**
