### PR TITLE
[3DS] Increase buffer size for libmpq file pointers

### PR DESCRIPTION
**Pull request by StephenCWills**
This change significantly improves load times for MPQ assets on my o3DS console.

### CODE REVIEW

**Comment by glebm** [comment]
Great work! :tada: 

Note that on (most?) other platforms this is not necessary because the default buffer size is already equal to the partition block size. It appears that the 3ds uses a non-conformant libc that defaults to unbuffered I/O for files.

**Review by glebm — APPROVED** [review]

**Comment by AJenbo** [comment]
> This change significantly improves load times for MPQ assets on my o3DS console.

Do you have numbers :)

**Comment by StephenCWills** [comment]
> Do you have numbers :)

The difference is so staggeringly significant that I didn't really bother taking any hard before/after measurements. All I know is that before this change, loading time for the intro video was a whopping 60 seconds. After this change, it's maybe around 2-3 seconds.

But it's not just the intro video. All loading screens are noticeably faster with this change.

**Comment by AJenbo** [comment]
cool i was just wondering if it was 60 vs 45, or some thing more appropriate :)

**Pull request merged**
