### PR TITLE
Add a Quick Save and a Quick Load actions to the Keymapper

### PR DESCRIPTION
**Pull request by Jmgr**
This just adds two quick save and quick load actions that are bound to F2 and F3 by default. F3 was used previously to show debug info, so it has been moved to 'N'. Quest debugging has also been moved to 'E' for consistency. This also frees F4 for some future action.

Note that this is based on #1368, so the changes showed here are those from that PR except the ones from last commit. This will be fixed once #1368 is merged.

### CODE REVIEW

**Review by julealgon — CHANGES_REQUESTED** [review]
> Quest debugging has also been moved to 'E' for consistency.

This will conflict with this: 
- https://github.com/diasurgical/devilutionX/pull/952

**Comment by AJenbo** [comment]
im wondering if we should get rid of most of the debug keys, i find them of little use if any and the complicate changes like key mapping.

**Comment by Jmgr** [comment]
> im wondering if we should get rid of most of the debug keys, i find them of little use if any and the complicate changes like key mapping.

My suggestion here would be to add actions that can be unbound by default to the Keymapper. That way developers could decide what debug feature they want to bind to a key. I would also add non-debug actions like `QuitGame` that would not be bound by default. In the config and unbound key would just not have a value, like `QuitGame=`. WDYT?

**Comment by Jmgr** [comment]
> > Quest debugging has also been moved to 'E' for consistency.
> 
> This will conflict with this:
> 
>     * #952

Oops. I'll remove that binding.

**Comment by AJenbo** [comment]
Sounds good, now you just need to get i building and rebase :)

**Comment by Jmgr** [comment]
> Sounds good, now you just need to get i building and rebase :)

I think I'll wait until #1368 is merged. Maintaining PRs based on other non-merged PRs from a fork a bit painful as you can's set the target branch to be the one from the original PR.

**Comment by julealgon** [comment]
> I think I'll wait until #1368 is merged

Consider marking this PR as "draft" until then @Jmgr .

**Comment by AJenbo** [comment]
Oh, wasn't aware that they where linked. Don't worry about it until the other on is merged, but yeah mark this as a draft.

**Comment by Jmgr** [comment]
> > im wondering if we should get rid of most of the debug keys, i find them of little use if any and the complicate changes like key mapping.
> 
> My suggestion here would be to add to the Keymapper actions that can be unbound by default. That way developers could decide what debug feature they want to bind to a key. I would also add non-debug actions like `QuitGame` that would not be bound by default. In the config and unbound key would just not have a value, like `QuitGame=`. WDYT?

Done.

**Comment by Jmgr** [comment]
I have already added this PR's content in https://github.com/diasurgical/devilutionX/pull/1368, so closing this one.

**Comment by AJenbo** [comment]
Works for me

**Pull request closed without merging**
