### PR TITLE
Flatpak fixes

### PR DESCRIPTION
**Pull request by tsunamistate**
Finally decided to return to flatpak support
First, some basic fixes I found during smoke testing

* Base flatpak on 1.4.1 tarball download
* Fix ipc permission

More flatpak progress soon

### CODE REVIEW

**Comment by tsunamistate** [comment]
Well, I'm stumped why MacOS CI failed, I didn't change anything there o_O

**Comment by glebm** [comment]
SDL2 just got updated on homebrew and it has a bug https://github.com/libsdl-org/SDL/issues/6119 (already fixed in SDL2 main)

**Comment by glebm** [comment]
This is now fixed on master, just needs a rebase

**Review by glebm — APPROVED** [review]

**Comment by tsunamistate** [comment]
Rebased

**Review by glebm — APPROVED** [review]

**Comment by AJenbo** [comment]
Hopefully they will fix this soon :D
https://github.com/libsdl-org/SDL/issues/6143

**Pull request merged**
