### PR TITLE
Use _talker_id when initialising towners to match use when gossiping.

### LINKED ISSUE #6132: some gossips got mixed up
If you click on the npcs and want to gossip, the conversations of other npcs are often played back. For example. Ogden speaks as Cain, Cain speaks as Farnham. Not all npcs and no causing commit tested.

### PR DESCRIPTION
**Pull request by ephphatha**
fixes #6132

### CODE REVIEW

**Comment by ephphatha** [comment]
This does introduce potential for broken behaviour. If someone saves a game while they're in the process of walking towards a town NPC to talk to them in a previous version then loads the game in this version `player.destParam1` will be off-by-one and they'll get the menu/dialog for a different NPC. Quitting the menu and talking to the NPC again will show the expected dialog options.

The previous broken behaviour was seeding the global RNG with unintialised memory.

**Comment by AJenbo** [comment]
By this version are you refering to the curent development (mater) builds? If so they are not supported as stable releases.

**Comment by ephphatha** [comment]
any build after this is merged. Pepin and Griswold are always assigned ID 1 and 2 in `dMonster`, in 1.09 and every devX release all other towners get shifted back one if deadguy isn't available (Cain can be ID 4 or 5 for example). Opened #6136 as a backwards compatible approach, I think there was some code which used to do that approach but doesn't appear it was ever used for gossip?

**Comment by AJenbo** [comment]
yeah there is something like that in other places, but i forgot for what :)

**Pull request closed without merging**
