### PR TITLE
Show current time during gameplay.

### PR DESCRIPTION
**Pull request by nelchael**
Adding an option to display current time just under the FPS counter.

### CODE REVIEW

**Comment by qndel** [comment]
You can check current time in chat log by pressing L

**Comment by nelchael** [comment]
> You can check current time in chat log by pressing L

Yes, but it can't be displayed all the time.

**Comment by StephenCWills** [comment]
We have added Lua to the codebase. It would be better to implement these kinds of customizations there.

**Comment by nelchael** [comment]
> We have added Lua to the codebase. It would be better to implement these kinds of customizations there.

I was able to figure out how to implement this in C++, I'm afraid I'm not that good with Lua.

**Comment by AJenbo** [comment]
You know a game is intended for a mature audience when it has an option to display the real life clock :)

**Comment by AJenbo** [comment]
You know a game is intended for a mature audience when it has an option to display the real life clock :)

**Comment by AJenbo** [comment]
You know a game is intended for a mature audience when it has an option to display the real life clock :)

**Comment by AJenbo** [comment]
@nelchael if you can either create an issue for it or maybe get on the chat we can help you create a Lua implementation.

**Comment by AJenbo** [comment]
Ok, here we go:
image

```lua
local render = require('devilutionx.render')

local function ShowTime()
	render.string(os.date('%H:%M:%S), 85, 8)
end

Events.OnGameDrawComplete.Add(ShowTime)
```

For US people you can get your odd format with: %I:%M:%S %p

There is a slight catch though, `os` is currently not exposed so you would have to add it to the lib list around line 165 in lua.cpp.

**Comment by nelchael** [comment]
Ok, so that's more like a DYI solution, bundling this script with a release build would force the clock display for everyone (I don't think settings are exposed to Lua either).

**Comment by StephenCWills** [comment]
Right, the point is to make these types of things more DIY.

Like, you want a clock? Go download the Lua script that implements it.

**Comment by nelchael** [comment]
> Right, the point is to make these types of things more DIY.
> 
> Like, you want a clock? Go download the Lua script that implements it.

Got it, I'd prefer to just have an option in the release build, but it's just me :)

**Comment by AJenbo** [comment]
We may well include some default mods that can be enabled form a menu in settings, same with any additional ones you make or download.

**Pull request closed without merging**
