### PR TITLE
Fix monster sync on kill

### PR DESCRIPTION
**Pull request by vlolteanu**
Fixes https://github.com/diasurgical/devilutionX/issues/2412

### CODE REVIEW

**Comment by obligaron** [comment]
The bug was introduced with #2234
Should we check for `<= 0`?

**Comment by glebm** [comment]
Interestingly, elsewhere in the code there is a check like this `monster._mhitpoints >> 6 <= 0`

**Comment by obligaron** [comment]
> 
> 
> Interestingly, elsewhere in the code there is a check like this `_mhitpoints >> 6 <= 0`

Not everywhere:

- [msg.cpp](https://github.com/diasurgical/devilutionX/blob/0889780923262ee8fecfe2d07c33272c58ab5bc1/Source/msg.cpp#L393)
- [msg.cpp](https://github.com/diasurgical/devilutionX/blob/0889780923262ee8fecfe2d07c33272c58ab5bc1/Source/msg.cpp#L1329)
- [missiles.cpp](https://github.com/diasurgical/devilutionX/blob/0889780923262ee8fecfe2d07c33272c58ab5bc1/Source/missiles.cpp#L4246)
- [objects.cpp](https://github.com/diasurgical/devilutionX/blob/0889780923262ee8fecfe2d07c33272c58ab5bc1/Source/objects.cpp#L4433)

But don't ask me if this is correct or not. At least it's confusing.
Anyway I think it would be good if we add a helper method to clarify this.

**Comment by ephphatha** [comment]
Adding a fixed point wrapper for these values would be great. That'd allow clarifying how HP/Mana values (6 bit fractional part) are handled and would also be useful for tile offsets (15 or 16 bit fractional parts depending on the use...).

As for the hitpoints > 0 checks, most of the time this check looks only at the integer portion so a monster with .077 hp is considered dead. I think it should use the form glebm pointed out for now.

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
When the monster is will it's HP is specifically set to 0, going to merge this for now and then we can clean it up later when adding a helper and do some some testing

**Pull request merged**
