### PR TITLE
warp to custom dungeons

### PR DESCRIPTION
**Pull request by qndel**
would be cool if someone can figure out how to load custom hell tileset duns ;)
#added support for loading hell maps, needs testing how the walls behave there compared to standard hell
#Fixed LoadL3Dungeon to use function arguments instead of hardcoded junk (I'm looking at you poisoned water supply)

### CODE REVIEW

**Comment by Chance4us** [comment]
@qndel If i press the keys 1,2,3,4 only a message appears but nothing happens.
Should the difference be visible?

**Comment by qndel** [comment]
nah, you need custom palettes and dun files to warp into them, 1234 are just settings for the warp

**Comment by Chance4us** [comment]
I see. Sorry.
lol

**Comment by qndel** [comment]
image
;)

**Comment by Chance4us** [comment]
it looks a little bit weird

**Comment by qndel** [comment]
no, it looks perfect

**Comment by Chance4us** [comment]
well. perfectly weird

**Comment by Chance4us** [comment]
you seem to be bored too.

**Pull request closed without merging**
