### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by sheng-luwei**

### CODE REVIEW

**Comment by AJenbo** [comment]
Thanks would you also be willing to translate the app portion: 
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-de/strings.xml

**Comment by AJenbo** [comment]
@sheng-luwei @ChaosMarc all planned features affecting the German translation should now be done and all translated text should show correctly in game. We plan to release in October so now would be an excellent time to work on the renaming parts of the translation :)

**Comment by ChaosMarc** [comment]
@AJenbo I don't think I can find the time at the moment 😔

**Comment by AJenbo** [comment]
Ok, thanks for letting me know, hope you can still drop by and keep up with the project 🙂

**Comment by ChaosMarc** [comment]
That I do :) I actually have the whole repo subscribed and read almost all of the topics' discussions 👼 I'm really looking forward to all to cool new ideas and features you guys are implementing :)

**Comment by AJenbo** [comment]
@sheng-luwei @ChaosMarc if either of you have time to update the translation now would be a good time to make it for the next release :)

There are about 220 lines that needs an update.

**Comment by ChaosMarc** [comment]
I will look into it :)

**Pull request merged**
