### PR TITLE
Golem fixes

### PR DESCRIPTION
**Pull request by kphoenix137**
* Makes other players' Golems selectable if you have Player Attack enabled
* Guardians will attack other players' Golems if the source player has Player Attack enabled
* Apocalypse will hit other player's Golems if the source player has Player Attack enabled
* Highlighting other player's Golems will show the name of the owner in the Info Panel
* Golems are no longer affected by `TripleDemonDamage` (Golems are classified as Demons in the Monster table)
* The Type for Golems is manually set to show "Golem" instead of "Demon"
* Hit Points for Golems will not display in the Info Panel, even if you have killed 30 of them or more, since Hit Points are derived from the Monster table, and Golems use a formula based on the stats of the player who summoned it

### CODE REVIEW

**Comment by julealgon** [comment]
> - Golems are no longer affected by TripleDemonDamage (Golems are classified as Demons in the Monster table)
> - The Type for Golems is manually set to show "Golem" instead of "Demon"

Is there consensus on this? I think special-casing the golem like this is a bad idea. If he is classified as a Demon, he should have the Demon behaviors.

**Comment by kphoenix137** [comment]
There are only 3 monster types, and it seems plausible that demon was selected becsuse weapon class bonuses wouldn't apply against it

**Comment by StephenCWills** [comment]
If we are to assume that Golem is not supposed to actually be a demon, then you also need a special case for `ItemSpecialEffectHf::ACAgainstDemons`. Or to introduce another category of monster.

**Comment by julealgon** [comment]
> it seems plausible that demon was selected because weapon class bonuses wouldn't apply against it

That seems quite far-fetched to me actually. Why would you jump to this conclusion?

It is much more likely to me that Demon was selected because it just made the most sense among the existing types.

**Comment by DakkJaniels** [comment]
I agree they probably didn't think out how affixes would apply, but I also think that they could have just defined the golem as something else (I don't think making a 4th define just for Golem would have been a huge issue).

I would probably just leave it as demon and keep whatever interactions come from that, since you could trigger them in vanilla, it was just more difficult because you couldn't select the golem, right?

**Comment by kphoenix137** [comment]
Why would Golem be a Demon? If anything it would be Undead, but then Holy Bolt would damage it

**Comment by DakkJaniels** [comment]
> As for this, I'd be inclined to believe they just didn't bother introducing a fourth type because they didn't have any reason to. Therefore, the technical difficulty of doing so is pretty irrelevant.

> EDIT: I suppose it would be more accurate to say that I'd be inclined to believe the technical difficulty is pretty irrelevant for the aforementioned reason. I don't feel I have enough info to make a definitive call on whether or not they would have introduced another type if they felt they did have a reason to do so.

My thought was more that if they wanted golem to be something other than demon, they could have easily done that (I think). If there was some technical hurdle that I'm not thinking of, then maybe they would have picked demon to avoid having a 4th type defined, but I doubt that's the issue here.


> Why would Golem be a Demon? If anything it would be Undead, but then Holy Bolt would damage it

Why would it be undead? It's made of clay (or stone), demon could make sense if you consider the golem body being possessed by a demon spirit or something. Regardless, they picked demon, not anything else. If they wanted something else, I'm sure they could have done that.

**Comment by julealgon** [comment]
> If anything it would be Undead

Well... it was never alive in the first place, so how can it be undead 😆 At least that's my definition for what undead means: it must've been alive at one point surely.

**Comment by StephenCWills** [comment]
> My thought was more that if they wanted golem to be something other than demon, they could have easily done that (I think). If there was some technical hurdle that I'm not thinking of, then maybe they would have picked demon to avoid having a 4th type defined, but I doubt that's the issue here.

No, there's no technical hurdle. You can just add another value to the enum and apply it to Golem. It wouldn't be referenced anywhere in the codebase, so there wouldn't be any mechanics associated with it. It's just.. _why_ do that? If `MonsterClass` is used for PvM and Blizzard devs assumed players wouldn't be going around attacking Golems in PvM, there's no motive for introducing a separate category just for Golems. That is, unless you value conceptual integrity half as much as julealgon, and I think we can safely say that Blizzard devs did not.

5l3nz8

**Comment by kphoenix137** [comment]
https://github.com/diasurgical/devilutionX/pull/7010

**Pull request closed without merging**
