### PR TITLE
#2735 documentation cleanup 01

### PR DESCRIPTION
**Pull request by bcko**
- part 1 of #2735

### CODE REVIEW

**Review by AJenbo — DISMISSED** [review]

**Comment by bcko** [comment]
Updated the pull request to resolve conflict.

**Comment by bcko** [comment]
Conflict happened again. I must have made some mistakes during conflict resolution process. Closing this pull request for now.

**Comment by AJenbo** [comment]
Oh i thought i had already merged this, sorry for that.

**Comment by AJenbo** [comment]
Let me fix that real quick

**Comment by AJenbo** [comment]
Ok it's all merged now, i see that the error that happened when you merged things as that you some how ended up deleting this line `if (itemSize.height == 1) {` from `AutoPlaceItemInInventory`.

**Pull request closed without merging**
