### PR TITLE
More memcpy memset

### PR DESCRIPTION
**Pull request by mmaret**
Few code simplification that should also improve the performances

### CODE REVIEW

**Comment by mmaret** [comment]
I've been running the COZ profiler on drawAndBlit.
Bottleneck seems to be RenderLine (more particularly https://github.com/diasurgical/devilutionX/pull/391/files#diff-a591ef71e3bf571c077b6d810716933dL119) and, some time world_draw_black_tile().

For the moment, I let world_draw_black_tile() doing back and forward in dst array but I'm not sure it's nice for cache hit.

**Comment by qndel** [comment]
Funny that I'm poking the same functions but for a completely different purpose at the moment :)

**Comment by AJenbo** [comment]
Nice, playing with COZ seams realy fun :)

**Comment by galaxyhaxz** [comment]
That's no surprise, given that the majority of rendering is the game world tiles, and even then solid tiles done with a copy. It's important for `RenderLine` to be both inlined and have simplified for loops as possible for speed.

**Comment by mmaret** [comment]
I think that before trying to get to much into code optimization, we should try compiler to use optimization.
render.cpp is not compiled with -03.
I've not check the perf improvement ( a part the fact that the compilation took much more time:)) but, for example, it could do the inlining by itself instead of code modifications.
LTO could improve perf as well.

**Comment by AJenbo** [comment]
I think the code is in a good enough state that we could start using -O3.

**Comment by galaxyhaxz** [comment]
Nah, I think we shouldn't use optimizations. Just in case we loose the code, hackers 20 years later can reverse it back =P

**Pull request merged**
