### PR TITLE
🌐 Update Italian localization

### PR DESCRIPTION
**Pull request by M0Rf30**
As in title,
Regards.

### CODE REVIEW

**Comment by AJenbo** [comment]
Thanks, I'll let you know when the renaming elements are translatable :)

**Comment by AJenbo** [comment]
@M0Rf30 all planned features affecting the Italian translation should now be done and all translated text should show correctly in game. We plan to release in October so now would be an excellent time to work on the renaming parts of the translation :)

image

**Comment by M0Rf30** [comment]
@AJenbo Amazing work. I'll refine the localization just in time for the next release, but I'm having an annoying issue with libsodium detection that breaks the software building process. I've seen that a related similar issue was previously fixed. At a first glance, reverting this [commit](https://github.com/diasurgical/devilutionX/commit/1f7f5bf3dccee957e23bdf4d976883b155d5e81a) does the magic. I'll keep you up to date

**Comment by AJenbo** [comment]
Ok, You will need to let us know what system you are on for us to help with that :)

Don't forget that you can also just grab a test build from the CI

**Pull request merged**
