### PR TITLE
Refactored parameters of "StartItemPower(...)" and code around calls to it.

### PR DESCRIPTION
**Pull request by matheusgomes28**
The improvements include:

1. Packed the parameters to `StartItemPower(...)` into a struct.
2. Renamed some of the parameters to make logical sense, to the best of my knowledge.
3. Added builder functions to make the required parameters from other item-related structs.

A few discussions were added by @AJenbo to my [local fork's PR here](https://github.com/matheusgomes28/devilutionX/pull/4/), make sure there are no outstanding discussions in that PR before merging (I've so far replied to all of them).

This PR implements issue #2211

### CODE REVIEW

**Comment by AJenbo** [comment]
Nice work. I went ahead and made a couple of changes, I did this instead of the normal review process as the PR is currently blocking another one, hope you don't mind :)

- `SaveItemPowerParams` is renamed `ItemPower` and used for compositing `PLStruct` and `UItemStruct`. This avoids having to convert them in various places and simplifies the others.
- Renamed randMin/Max back to param1/2 as they can represent other values depending on the power type.
- Get item by reference instead of an index in to the global `Items` (cause I actually made a bug in reusing `i` when making the other changes)

Lastly I split the change in to two commits, one that moves the function and then one that applies all the changes, so that it is easier to see what changed in the diff.

**Review by ephphatha — APPROVED** [review]
looks good, I wasn't a fan of the static conversion functions but that's no longer an issue with the introduction of the ItemPower struct :)

**Review by matheusgomes28 — COMMENTED** [review]
@ephphatha I wasn't a fan of that myself, glad it's gone 😄 

@AJenbo Very welcoming changes, looking a lot better now!

**Comment by AJenbo** [comment]
Did a follow up that rosters the order of itemdat.cpp and removes the redundant values from uniques:

https://github.com/diasurgical/devilutionX/pull/2347

**Pull request merged**
