### PR TITLE
Add missing pt_br translations

### PR DESCRIPTION
**Pull request by yuripourre**
@julealgon or @altiereslima if you have some free time, I would really appreciate it.

What to you think about `Stash -> Armazém`?

### CODE REVIEW

**Comment by altiereslima** [comment]
> @julealgon or @altiereslima if you have some free time, I would really appreciate it.
> 
> What to you think about `Stash -> Armazém`?

Eu gostei, estava pensando em baú, mas como não aparece a imagem de baú no jogo então Armazém ficou ótimo.

**Review by AJenbo — APPROVED** [review]

**Comment by julealgon** [comment]
A bit too late I guess, but I have to say that "armazem", while apparently an adequate translation theoretically (if we stretch it), sounds _very_ strange. 

I'd probably go with "Depósito" on this one.

**Comment by AJenbo** [comment]
There's going to be and update to DevilutionX soon so now would be a good time to update the translation if you have time :)

**Comment by yuripourre** [comment]
@AJenbo I will have some time next Monday. Is it ok?

**Comment by AJenbo** [comment]
Perfect :)

**Pull request merged**
