### PR TITLE
New Platform: Clockwork PI GameShell

### PR DESCRIPTION
**Pull request by danie1kr**
Hi all,
I added support for the [Clockwork PI GameShell device](https://www.clockworkpi.com/gameshell), a arm powered handheld.
With the recent keyboard mapping update from @glebm, the limited GameShell keyboard can now run all functions properly.
I also added a GameShell launcher menu script which can compile and update the source.

Best Regards
Daniel

### CODE REVIEW

**Comment by AJenbo** [comment]
Excelent work, nicely documented and easy to digest.

P.s. do you by chance have a video of the game running on the device?

**Comment by danie1kr** [comment]
Thanks for the fast update. I will try to do a video in the next days.

**Comment by qndel** [comment]
can't wait! this stuff looks cool :D

**Comment by danie1kr** [comment]
I just did a short video here: [click](https://drive.google.com/file/d/1TpF1woxVHAD6wxUM7wnPpBPx45mKTbsR/view)
Nothing special but you should get an impression.

**Comment by AJenbo** [comment]
Thanks for doing the video, it helps get a sens of how well it's working and what kind of device we are dealing with :)

Game looks to run nicely.

I did noticed that the town background image doesn't show during initial loading, I have seen this once and heard it reported, but it appears to be device specific. My guess is that it's related to gbBufStart/End not being set correctly at the time, but I haven't had a chance to debug it on a device that exhibit the issue. The values should be set here:
https://github.com/diasurgical/devilutionX/blob/master/Source/init.cpp#L52
But there are other places that will change them during the render process.

This is what the load screen shot look like:
image

Again nice work on getting a port working on this device.

**Comment by danie1kr** [comment]
Thanks, I remember the image... I will look into this.

**Comment by danie1kr** [comment]
I really do have a hard time on this.
I noticed that on a second 'load game', the image is present. But I could not trace it to any fault regarding the palettes, the image file itself or something like this.
The progress bar is present, so I don't think it is a problem with the gpBuffer as it is written to.
Can you think of any other part to check?

**Comment by qndel** [comment]
does it run SDL1 or 2? if 2, can you try with my light branch? I'm curious if it'd change anything

**Comment by AJenbo** [comment]
> I really do have a hard time on this.
> I noticed that on a second 'load game', the image is present. But I could not trace it to any fault regarding the palettes, the image file itself or something like this.
> The progress bar is present, so I don't think it is a problem with the gpBuffer as it is written to.
> Can you think of any other part to check?

Since the progress bar is there I think both gpBuffer and colors are working correct, but especially the fact that the image work the seound time just makes me even more strongly belive it is related to `gbBufStart` or `gbBufEnd`. The limit the area of the screen that will be drawn to by the cel render functions in engine.cpp. If they are set to render to no part of the screen this would explain the observed behavior.

**Comment by danie1kr** [comment]
> Since the progress bar is there I think both gpBuffer and colors are working correct, but especially the fact that the image work the seound time just makes me even more strongly belive it is related to `gbBufStart` or `gbBufEnd`. The limit the area of the screen that will be drawn to by the cel render functions in engine.cpp. If they are set to render to no part of the screen this would explain the observed behavior.
Ok, now I got it. I can confirm that this is the issue.
`memcpy(dst, src, width);` in `CelBlitSafe` is never called for the first load but for later loads it is called.
Btw: I use SDL2 on the GameShell.

**Comment by danie1kr** [comment]
And there it is:
The first time `lock_buf_priv` from dx.cpp:73 is called, gpBufEnd is `0xAECAE008` (from the init.cpp you hinted earlier). Adding `0xAEC36008` overflows to `0x5d...` which cannot be recovered by the following `unlock_buf_priv` safely.
It seems later changes to gpBufEnd correct this and make it lock-safe.
The GameShell is a 32bit machine, 64 bit pointers would not have this problem.

**Comment by AJenbo** [comment]
Thanks that explains a lot, could you try just removing the `gpBufEnd` line from `init_create_window` and see if this solves the issue?

**Comment by danie1kr** [comment]
> does it run SDL1 or 2? if 2, can you try with my light branch? I'm curious if it'd change anything

Hi @qndel 
the GameShell runs SDL2. 
The game looks fine from your branch. However, the performance in the dungeons is really low on the GameShell. Unplayable. It did not run it with the FPS counter though, but I guess it is around 10 FPS. So I hope you will integrate a #define for your improvements or improve the performance 😁

**Comment by qndel** [comment]
@danie1kr there is a define! :) enabled by default atm but you can remove it (#define PIXEL_LIGHT 1)

**Comment by qndel** [comment]
maybe you'd want to join discord for faster chatting :)
http://discord.gg/aQBQdDe

**Pull request merged**
