### PR TITLE
Simplify InitPlrGfx

### PR DESCRIPTION
**Pull request by glebm**
It was tracking each type of graphics individually but they're always allocated together.

### CODE REVIEW

**Comment by AJenbo** [comment]
is there even any significant benefit to pre allocating this instead of doing it when loading individual sprites?

**Comment by glebm** [comment]
I still haven't figured out how all of this works
It *might* be related to a few of these being different between town and dungeon

**Comment by glebm** [comment]
I also don't understand how why it worked previously with multiple players

The `plr_gfx_flag` was shared across all players and never reset!

**Comment by glebm** [comment]
OK, so previously it always allocated the size of the BLOCK buffer to all animations of all the players except the first one!

**Comment by glebm** [comment]
Ah no, nevermind, it used the sizes it got when evaluating the first player

**Comment by glebm** [comment]
So we'll hopefully save some RAM once we begin allocating exact buffer sizes (for which I added a FIXME in this PR)

**Comment by AJenbo** [comment]
i guess this PR made Multiplayer start slightly slower :)

**Comment by glebm** [comment]
@AJenbo This PR doesn't change any behaviour, only the follow-up #1396 does

**Pull request merged**
