### PR TITLE
Better line drawing function

### PR DESCRIPTION
**Pull request by AJenbo**
https://github.com/diasurgical/devilution/pull/1125#issuecomment-489474723

linedrawing

### CODE REVIEW

**Comment by Chance4us** [comment]
Beautiful function. Why it is not merged yet?

**Comment by AJenbo** [comment]
There are some other clean ups to the function from up stream that I would like to merge first to avoid conflicts.

**Comment by Manuel-K** [comment]
I'm not sure how you want to handle such cases, but I think it should be possible to compile devilutionX
 with vanilla oddities like the crooked lines.

**Comment by AJenbo** [comment]
One way could be to simply place an `#ifdef` around it and add a parameter for switching enhancements on/off at compile time. But we might even be able to do most of it at run time.

**Comment by pgielda** [comment]
I really like this feature. It would make most sense to be able to switch in runtime, too much ifdefed code is hard to test.

**Comment by mmaret** [comment]
@AJenbo still something blocking from merging it ?

**Comment by AJenbo** [comment]
@mmaret only that I don't want to change the look of the game before the release of 1.0.0

**Comment by AnthonyIacono** [comment]
What are the drawbacks to this approach? Does any functionality get lost? The code is much cleaner and easier to read.

**Comment by galaxyhaxz** [comment]
Butthurt purists...

**Pull request merged**
