### PR TITLE
Use cast animation in town

### PR DESCRIPTION
**Pull request by obligaron**
Uses cast animation in town and unify casting in town and dungeon.

<details><summary>Original Description (outdated)</summary>
Since #1939 casting in Town is buggy.
We don't use `NewPlrAnim` for casts in town but still check `AnimationInfo.CurrentFrame`.

Possible Solutions

1. Bring back `actionFrame` only for the special case of casting in town.
2. Start explicit Stand Animation for the cast.
3. Use the cast animation in town

This pr uses solution 3, but if the cast animation in town is not desired I would open a new pr with solution 2.

_The original bug was fixed with #2025._
</details>

<details>
<summary>Example Videos</summary>

## DevilutionX 1.21 (no casting Animation)
https://user-images.githubusercontent.com/25415264/118359759-4b16df00-b585-11eb-823a-dd9946be456d.mp4

## Sorc Sword+Shield
https://user-images.githubusercontent.com/25415264/118359873-ae087600-b585-11eb-8659-1f57330e2f25.mp4

## Sorc Staff
https://user-images.githubusercontent.com/25415264/118359787-6255cc80-b585-11eb-8f81-a6ed1be7fe36.mp4

## Sorc Sword
https://user-images.githubusercontent.com/25415264/118360004-148d9400-b586-11eb-9b39-e6e986ecbf7d.mp4

## Warrior Mace+Shield
https://user-images.githubusercontent.com/25415264/118359893-bc569200-b585-11eb-8c5e-907bbe8a2371.mp4

## Warrior Axe
https://user-images.githubusercontent.com/25415264/118359912-c37da000-b585-11eb-8167-28c60a97b075.mp4

## Warrior Mace
https://user-images.githubusercontent.com/25415264/118359930-ced0cb80-b585-11eb-8c6e-12bf47389724.mp4

## Warrior Axe + Heavy Armor
https://user-images.githubusercontent.com/25415264/118359935-d4c6ac80-b585-11eb-9752-41602f759ec7.mp4

## Rouge Bow
https://user-images.githubusercontent.com/25415264/118359967-ef992100-b585-11eb-848e-4bc5a06ae9df.mp4

</details>

Notes:

- If they hero holds the weapon in his hands, the casting animation with weapon is used. If the weapon hangs at the belt the unarmed casting animation is used.
- Generally this looks good. But please watch warrior with heavy armor example, cause in the town walking/stand animation he doesn't wear his helmet.
- Reviewer notes: best reviewed with hide whitespace changes.

### CODE REVIEW

**Comment by AJenbo** [comment]
Two sounds best

**Comment by obligaron** [comment]
> 
> 
> 2 sounds the least intrusive

That's for sure.

Normally I wouldn't open a pr that changes behavior for fixing a new introduced bug.
But in this case it felt like the natural change. :blush:
Now we give the user visual feedback of his actions (casting animation) that was previous missing.
The original logic (no animation) could also be classified as bug.
Casting in town is not a core mechanic of the game. That's also the reason why the original devs didn't put the work into own animations for casting in town.
So I thought to myself this is better then before, not perfect but good enough.

Anyway I knew this would be a little bit controversial. So it's really no problem if we don't want to take this now then I would code again and open a new pr. 🙂

**Comment by galaxyhaxz** [comment]
I think we discussed this before and the issue is what you mentioned about the warrior and heavy armor. The animations don't look right since town has separate animations. If you are ok with this oddity then the PR works.

What they did on the playstation port was separate the spell overlays from the character animations and make the player freeze in limbo while the overlay plays on top but that requires new assets. Either that or make town use the same walk/stand animations as the dungeon.

**Comment by obligaron** [comment]
I found #

> 
> 
> I think we discussed this before and the issue is what you mentioned about the warrior and heavy armor. The animations don't look right since town has separate animations. If you are ok with this oddity then the PR works.

I think you are right. I found #1102. But the difference to this pr is that the weapon problem is resolved (use unarmed animations) and for me that was the main problem. 🙃

> 
> What they did on the playstation port was separate the spell overlays from the character animations and make the player freeze in limbo while the overlay plays on top but that requires new assets. Either that or make town use the same walk/stand animations as the dungeon.

If someone could get us this assets it would be nice. But I think that's outside the scope of this pr.

**Comment by FitzRoyX** [comment]
I don't think it's a big deal that upright casting animations don't exist given the few spells allowed in town. But the sudden stance change for #3 isn't that jarring to me either, and it lets other players know who is casting. Messing with the assets would be splitting hairs and overkill IMO (I feel the same about shadows). There is a degree of art jank I find easy to accept with old games as long as there are bigger problems at hand.

**Comment by galaxyhaxz** [comment]
> There is a degree of art jank I find easy to accept with old games as long as there are bigger problems at hand.

Wish I could say the same, but I'm a perfectionist ;) <3

**Comment by julealgon** [comment]
Using the cast animation in town seems like the more sensible approach to me as well. What are the problems associated with it again?

**Comment by AJenbo** [comment]
> Using the cast animation in town seems like the more sensible approach to me as well. What are the problems associated with it again?

The cast animations have combat stance, all town animations have a non-combat stance. So using them in town will have the player flip between two stances (the warrior in particular will have his helmet pop on and off)

**Comment by Chance4us** [comment]
As it is, I see the advantages and disadvantages of 2 and 3. The question that arises is where the advantages are greater.

3 is more invasive but gives better player feedback and looks great. The side effect of the warrior putting on the helmet should not scare the NPCs or other players. The gameplay remains unchanged.

2 leaves the game unchanged, but does not allow a better feedback.

So let's vote. One vote for 3.

**Comment by obligaron** [comment]
I opened another PR #2025 with solution 2.
Both PRs can be compared (visual & code) so I hope that helps for the discussion.
If we want/need more time to think about what is the correct long term solution, then I would suggest to take PR #2025 with solution 2 now. With that the new introduced bug is fixed.

Note: I'm still a fan of casting animation in town but I don't like to couple bug fixes for new introduced bugs (by me :disappointed:) and design changes (casting in town animation).

**Comment by Chance4us** [comment]
> Note: I'm still a fan of casting animation in town but I don't like to couple bug fixes for new introduced bugs (by me
> disappointed) and design changes (casting in town animation).

The stand animation is good enough for now and everybody agrees with it.
The decoupling of position change is progressing well overall and is necessary despite the side effects.

**Comment by ephphatha** [comment]
This was autoclosed because of the keywords used in #4010 😅

**Comment by ikonomov** [comment]
The animation is slightly darker for a warrior wearing a one handed weapon in plate armor.  Probably looks fine in the dungeons since the lightning there is darker.

https://github.com/diasurgical/devilutionX/assets/5624187/bbb5d831-7f77-4ebf-9cf8-8577fdd8e76c

**Pull request merged**
