### PR TITLE
Fix warning when calling NetSendHiPri() wiht MyPlayerId

### PR DESCRIPTION
**Pull request by AJenbo**
Seeing this one pop up a lot in the GitHub UI as of late, maybe this will fix part of it.

### CODE REVIEW

**Comment by obligaron** [comment]
Could we pass a `Player` reference instead of the playerid to the `NetSendHiPri` and `NetSendLowPri` methods?
This way we only need one or two casts in these functions.

**Comment by AJenbo** [comment]
I noticed that it it would actually make more sens to take it as size_t in most cases so I changed it to that instead, this also got it down to just one cast and fixed a few other cases.

**Comment by obligaron** [comment]
When thinking about it... I'm not sure if we should keep Player and Monster Id as `size_t`.

They are 
- not platform depend
- should be stored in saves always the same
- should be the same across network calls
- not that much that we should have billions of them 😁 

I would stick with a `int` or `int32_t`. But if possible we shouldn't use a Id at all and instead keep the Object-References.

But these are only thought about the Id-topic in general and shouldn't prevent merge a PR that reduces warnings. 🙂

**Comment by AJenbo** [comment]
We already did a lot to minimize the places that use the index and rather use the object reference when possible.

It's size_t because it comes from `sizeof()` for arrays and `.size()` from the player vector.

It's a little hard for me to play along with fixing MSVC as I only really have the GitHub Action result to see if I'm helping or not, so I'll let you decide if this should be closed or approved..

**Comment by obligaron** [comment]
I think we should merge this as it's a improvement. 🙂 

How to handle the other warnings/issues we see when we start addressing them.
A theory discussion is not that helpful. I'm currently thinking about how to handle the other warnings, so I started talking about the current ideas in my head. 😁

**Comment by AJenbo** [comment]
Oh, if you can let me know how many this PR fixed that would be interesting :D

**Comment by obligaron** [comment]
This PR reduces the warnings by 50 (from 355 to 305) 🙂

**Pull request merged**
