### PR TITLE
loadsave.cpp: Fix pfile_write_save_file call

### PR DESCRIPTION
**Pull request by glebm**
Refs #1367

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
Thank you for tracking this down. The idea with m_bufferPtr was that it would crop the buffer to just the amount of data that was written to it instead of whatever was allocated. I guess that didn't work out :(

**Comment by glebm** [comment]
>  I guess that didn't work out :(

Well there is no code that actually does it

**Comment by glebm** [comment]
It's a trivial fix, 1 sec

**Comment by glebm** [comment]
Wait, a variable called `m_bufferPtr` is not actually a pointer

Perhaps this fix doesn't actually fix anything

**Comment by glebm** [comment]
Yeah nevermind

**Pull request closed without merging**
