### PR TITLE
Automate Linux x86_64 release

### PR DESCRIPTION
**Pull request by glebm**
Also adds `discord_game_sdk.so` to the Linux release builds.

### CODE REVIEW

**Comment by glebm** [comment]
@AJenbo We need this for 1.5.0 because this fixes Discord integration for the x86_64 Linux Release

**Comment by glebm** [comment]
Will have to be merged manually because GitHub is stuck waiting for the CircleCI job that was deleted in this PR

**Comment by AJenbo** [comment]
Was hoping to stay compatible with 18.04 for this release and upgrade to 20.04 after. But I guess I missed the deadline.

**Comment by glebm** [comment]
Yeah, Ubuntu 18.04 EOL'd on 30 Apr 2023.

**Comment by AJenbo** [comment]
With, it's not EOL'ed yet, won't be until May 30th :D

**Pull request merged**
