### PR TITLE
Xbox One: Package assets/ directory

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Review by AJenbo — COMMENTED** [review]
Best to also disable loading of devilutionx.mpq so we don't get issues with people upgrading or being extra judicial in adding files.

**Comment by glebm** [comment]
Shall we simply make `assets/` take priority over the MPQs?

**Comment by AJenbo** [comment]
Not sure, will have to think :)

**Comment by glebm** [comment]
Turns out the appx file already has the assets!

**Pull request closed without merging**
