### PR TITLE
Optional Regenerating Life and/or Mana

### PR DESCRIPTION
**Pull request by burningserenity**
Adds gameplay options to toggle regenerating life, regenerating mana, or both. Regeneration rates are based on the rate monsters regenerate their HP.

### CODE REVIEW

**Comment by yuripourre** [comment]
I don't think people will approve it. I don not consider myself a purist but this change is definitely in a mod territory.

**Comment by AJenbo** [comment]
hmm yeah this is defiantly mod territory, each release i wonder bout removing the Adrea mana option :D

**Comment by Iniquitatis** [comment]
I don't mind it myself, however yeah, having such gameplay-changing options in the core game surely does feel somewhat wrong.

**Comment by burningserenity** [comment]
How do I have this added to the mod list?

**Comment by StephenCWills** [comment]
You should be able to do that yourself.

**Comment by malvarenga123** [comment]
> each release i wonder bout removing the Adrea mana option :D

I really hope you don't :pray:

**Comment by AJenbo** [comment]
> How do I have this added to the mod list?

It's a wiki you can simply add it: https://github.com/diasurgical/devilutionX/wiki/Mods-and-related-projects/_edit

**Comment by AJenbo** [comment]
Closing since it doesn't fit the scope of DevilutionX. Let us know if you need help setting your fork up to highlight your mod :)

**Pull request closed without merging**
