### PR TITLE
Fix warp position offset and adjust some spawn positions

### LINKED ISSUE #5185: Stairs hero position offset
If you go down a level like in this example and then come back, then the hero is in the following position.

offset1

If you then use the warp spell, then your hero will be moved to the following position.

offset2

As you can see, the two positions differ and it is desirable to treat the positions for the stairs equally in both cases.

I can't currently tell if it's a vanilla issue or since when it was introduced.

Savegame:
[stairs_test.zip](https://github.com/diasurgical/devilutionX/files/9253177/stairs_test.zip)

EDIT:
Of course, the same applies to the stairs that lead upstairs.

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #5185 (second try 😉)

This PR fixes the warp positions (hopefully) and changes some spawn positions (for examples see bottom).
Please review the changed spawn positions especially. I think the most controversial could be hellgate and hell downstairs. 😉 

<details><summary>Banner Quest</summary>

## Master
BannerQuest_Master

## PR
BannerQuest_PR

## Reference (normal level, not changed)
BannerQuest_Reference

</details>

<details><summary>Chamber of Bone</summary>

## Master
ChamberOfBone_Master

## PR
ChamberOfBone_PR

## Reference (normal level, not changed)
ChamberOfBone_Reference

</details>

<details><summary>Lazarus Portal</summary>

## Master
Lazarus_Master

## PR
Lazarus_PR

## Reference
Lazarus_Reference

</details>

<details><summary>Warlord of Blood</summary>

## Master
WarlordOfBlood_Master

## PR
WarlordOfBlood_PR

</details>

<details><summary>Hell downstairs</summary>

## Master
HellDownstairs_Master

## PR
HellDownstairs_PR

</details>

<details><summary>Hell gate</summary>

## Master
Hellgate_Master

## PR
Hellgate_PR

</details>

@Chance4us It would be great if you could test this pr. 🙂 

I didn't change
>  upstairs: The warp and hero position is the same, but the hero stands displaced in the entrance (unclear if vanilla behavior)

### CODE REVIEW

**Comment by Chance4us** [comment]
Thanks, will test on Sunday.

**Review by AJenbo — APPROVED** [review]

**Comment by Chance4us** [comment]
Although I am only at the beginning of the tests, I would like to describe an important interim result.
As I already suspected, there is a fundamental problem with the hero's position at the "poisoned water" entrance.
While it's not a big deal, the hero's position will be different from vanilla when the hero exits the quest. Below the vanilla screenshot and Devilutionx. You can use the attached vanilla savegame for testing, in which I have the hero standing in front of the entrance. If you now load the savegame in devilutionx, the hero will be promoted directly to the quest when loading.
In Vanilla, however, the hero remains standing in front of the entrance while loading this savegame.
All in all, it's a relatively minor issue.

Vanilla hellfire hero position:
vanilla

Devilutionx hero position:
devilutionx

Vanilla Savegame:
[poisoned.zip](https://github.com/diasurgical/devilutionX/files/9639447/poisoned.zip)

**Comment by Chance4us** [comment]
I have one more finding with good news. In vanilla level 6 the warp and hero positions also differ from each other. So we fix the following issue and can leave it as it is.

https://user-images.githubusercontent.com/45902449/192116651-de94229f-f69e-4adc-86d3-eff0c9914d47.mp4

**Comment by Chance4us** [comment]
Conclusion:
The PR is very satisfactory and can be merged.
If necessary, the position when entering and leaving the poisoned water quest can be corrected, but this is not absolutely necessary. Fixing the vanilla position issues described below can be seen as a positive gain.

**Comment by Chance4us** [comment]
Thanks a lot @obligaron , @AJenbo . So we have a huge improvement.

**Comment by AJenbo** [comment]
could you create an issue for what is left

**Comment by Chance4us** [comment]
The issue report is ready.

**Pull request merged**
