### PR TITLE
minor alignment adjustment

### PR DESCRIPTION
**Pull request by ikonomov**
It is still not perfect, but I think that's how it was intended to be aligned and then probably got misaligned after some change.  The alignment looks slightly different in GitHub and Visual Studio, I made this edit according to how it looks in Visual Studio.

### CODE REVIEW

**Review by StephenCWills — DISMISSED** [review]
The difference in alignment is due to GitHub rendering tabs as 8 spaces whereas Visual Studio renders them as 4 spaces. If you're so inclined, you can change it in your GitHub account settings.

**Comment by qndel** [comment]
This still looks bad ...

**Review by qndel — CHANGES_REQUESTED** [review]
This still isn't aligned properly

**Comment by StephenCWills** [comment]
@qndel What's the issue? It looks okay to me. Maybe the first column header could be shifted left, but it's not really a problem visually.

image

**Comment by qndel** [comment]
image

**Comment by StephenCWills** [comment]
Your alignment is off by 4 spaces because of the way GitHub renders tabs. Are you saying the tabs need to be removed?

**Comment by qndel** [comment]
That too, I don't think we are using tabs anywhere else for alignment?

**Comment by ikonomov** [comment]
However you guys think looks best.  I simply noticed that it was way off currently.

**Comment by AJenbo** [comment]
tab should only be used for indentation, never for alignment

**Review by StephenCWills — APPROVED** [review]

**Pull request merged**
