### PR TITLE
	modified:   Source/automap.cpp

### PR DESCRIPTION
**Pull request by joewis**
Added feature to show all players on automap.

### CODE REVIEW

**Comment by AJenbo** [comment]
At a glance, this looks good. But please apply the project code style to the code. This can be done using `clang-format`.

**Comment by galaxyhaxz** [comment]
A much cleaner way to do this is change `myplr` to `i` and add `int i` to the function call then loop through in the main drawing function.

**Comment by qndel** [comment]
Thought about the same thing :D

**Comment by galaxyhaxz** [comment]
Sub-millisecond reply times as always. I couldn't even read my message again ;P

**Comment by joewis** [comment]
Ya, I was trying to touch as little as possible, still working to understand the code.
Is there any penalty to do it this way?

**Comment by galaxyhaxz** [comment]
Nope, it's how they did it on the PSX (loop inside the function). It just changes more lines of code. Otherwise the same.

**Comment by qndel** [comment]
there's a penalty to style and we are all about style

**Comment by galaxyhaxz** [comment]
Also, the math for getting the X/Y on screen looks a bit heinous as it has not been cleaned up yet. [I fixed that here long ago in my Devilution rewrite](https://github.com/galaxyhaxz/devilution/blob/master/2020_03_31/Source/automap.cpp#L432), which is how they wrote it originally.

**Comment by joewis** [comment]
I have moved the loop into the main drawing function and applied clang-format.

@galaxyhaxz your code looks quite a bit less heinous,  but is it hard coded for 640x480? Maybe we can leave that for a separate pull request.

**Review by AJenbo — APPROVED** [review]

**Comment by galaxyhaxz** [comment]
All you have to do is copy/paste the screen_width defines over the 640/352 from devilx. Devilutions is deprecated to there won't be a PR

**Comment by galaxyhaxz** [comment]
```c
	MapX = Px - ViewX - 2 * AutoMapXOfs;
	MapY = Py - ViewY - 2 * AutoMapYOfs;
	x = SCREEN_WIDTH / 2 + SCREEN_X + MapX * AmLine16 - MapY * AmLine16;
	y = (SCREEN_HEIGHT - PANEL_HEIGHT) / 2 + SCREEN_Y + MapX * AmLine8 + MapY * AmLine8;
	x += plr[myplr]._pxoff * AutoMapScale / 100 >> 1;
	y += plr[myplr]._pyoff * AutoMapScale / 100 >> 1;
	x += ScrollInfo._sxoff * AutoMapScale / 100 >> 1;
	y += ScrollInfo._syoff * AutoMapScale / 100 >> 1;
```

**Comment by AJenbo** [comment]
image

**Comment by qndel** [comment]
pic doesn't load

**Comment by AJenbo** [comment]
Yes, but it's just transparent...

**Comment by galaxyhaxz** [comment]
I think it'd be cool to make friendly players appear green and hostile players red. Oh wait diablo has no green :D

**Comment by qndel** [comment]
don't show hostile players , ez

**Comment by galaxyhaxz** [comment]
d2 shows them only when close by. friendly players are shown on the whole map.

**Comment by joewis** [comment]
> don't show hostile players , ez

I had that thought too, but undecided. It may change gameplay for PvP when you're always broadcasting your position.

**Comment by galaxyhaxz** [comment]
diablo also has no proper pvp system since friendly mode only affects missiles. so as it stands that would need to be reworked.

**Pull request merged**
