### PR TITLE
Fix MissileFileData arrays not getting properly filled

### PR DESCRIPTION
**Pull request by vlolteanu**
Fixes https://github.com/diasurgical/devilutionX/issues/2579

I couldn't find a pretty way of calling explicit constructors in a brace-enclosed initializer list.

### CODE REVIEW

**Comment by AJenbo** [comment]
Thanks, I had just gotten to the same conclusion :)

**Review by AJenbo — APPROVED** [review]

**Comment by StephenCWills** [comment]
FYI, the last entry in the `MissileSpriteData` array gives me a couple run-time errors at startup in Visual Studio.
`Run-Time Check Failure #3 - The variable 'ret' is being used without being initialized.`

The exception occurs at the return statement in the `maybeAutofill()` function. Presumably, the reason this occurs is that it's operating on a list of size 0 and so no value ever gets assigned to the contents of the array. As far as I can tell, it's not actually causing any issues at runtime apart from the debugger stopping on the thrown exception.

**Comment by vlolteanu** [comment]
You could try doing `std::array<T, 16> ret = {};`. It won't change the end-result, but maybe it will pacify Visual Studio.

**Comment by StephenCWills** [comment]
Thanks, that does appear to pacify Visual Studio. I'll submit a PR.

**Pull request merged**
