### PR TITLE
use uint64_t instead of unsigned __int64 in structs.h

### PR DESCRIPTION
**Pull request by mewmew**
Updates #449.

**Note**: this PR is not yet ready for merge. I just want to see where the build fails on Windows using the CI to build.

### CODE REVIEW

**Comment by glebm** [comment]
This should be `std::uint64_t` from `<cstdint>`, as we're using C++.

**Comment by mewmew** [comment]
> Nevermind, I see you're trying to make headers C-compatible. In this case #include <stdint.h> is required.

Currently struct.h doesn't include anything, but expects the source file that includes `structs.h` to also include the environment needed.

Compiling with `clang -x c -o foo.o structs.h` also complains about `BYTE` not being defined, etc. But those are easily fixable. The main point with this PR is that `unsigned __int64` cannot be fixed with e.g. defines or typedefs, as they are two distinct tokens (at least not to my knowledge).

**Comment by AJenbo** [comment]
looks like it compiles let us know when its ready :)

**Comment by mewmew** [comment]
> looks like it compiles let us know when its ready :)

It's ready :)

**Pull request merged**
