### PR TITLE
Fixed outline drawing for item on cursor to match rest of game

### PR DESCRIPTION
**Pull request by thebigMuh**
Also made GetOutlineColor param const, and made gold outline golden again... because the white outline made me sad.

### CODE REVIEW

**Comment by julealgon** [comment]
Would you mind adding some screenshots comparing how it was before to how it is now? Or create an issue with the details and linking this PR with it?

**Review by AJenbo — APPROVED** [review]

**Comment by thebigMuh** [comment]
> Would you mind adding some screenshots comparing how it was before to how it is now? Or create an issue with the details and linking this PR with it?

Sure, pretty straightforward.
Old white gold outline, sad:
image
New golden gold outline, happy:
image

The other issue is far easier to see when you play the game, but I tried to capture it.
Previously, as soon as you picked an item up, it would only know three different outline colors - red if you didn't meet the stats requirements, blue for magical and unique items, and yellow for everything else:

https://user-images.githubusercontent.com/81810641/117059101-b9ef6f00-ad1f-11eb-8d08-9417dd92b0e1.mp4

Now, the outline color for items stuck to your cursor matches the colors when the items are in your inventory or on the floor:

https://user-images.githubusercontent.com/81810641/117059172-cc69a880-ad1f-11eb-912f-970232a40756.mp4

**Comment by julealgon** [comment]
> Now, the outline color for items stuck to your cursor matches the colors when the items are in your inventory or on the floor:

This is a nice change. I appreciate the consistency.

> Old white gold outline, sad:
> New golden gold outline, happy:

I'm confused now: isn't white outline the standard in the game for all "normal" items (i.e. items without magical properties)? Why would we change it for gold specifically? Why do you think it is bad in the first place? If anything, the white outline is a _lot_ more readable to me so I think changing it to the unique item coloring makes it worse. However, even that is not an argument for keeping it: consistency is.

Changing the gold outline color creates inconsistency in design and is a really bad change IMHO. Can we please consider reverting that @AJenbo ?

**Comment by thebigMuh** [comment]
The white isn't really white, it's more a bright grey.
I think it looks really bad around the edges of gold, that's the only reason I have for changing it.

**Comment by AJenbo** [comment]
> Changing the gold outline color creates inconsistency in design and is a really bad change IMHO. Can we please consider reverting that @AJenbo ?

In the original game all item outlines where gold.

**Comment by julealgon** [comment]
> In the original game all item outlines where gold.

For items on the ground it's not. I'm specifically referring to gold on the ground.
image

**Comment by julealgon** [comment]
Looking at the original again, I'm ok with this change only if we make all normal item outlines the same color when on the ground.

The original game seems to use the same color for everything (contrary to what I said earlier).

Making only gold different makes zero sense (to me).

**Pull request merged**
