### PR TITLE
Wake up the whole pack of Gargoyles when disturbed

### LINKED ISSUE #7448: [Issue Report]: Blood Claw Unique Pack Wakeup Issue
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

The Blood Claw Unique and his minions wake up separately instead of all waking up if any one individual is woken up.

### To Reproduce

1. Find the Blood Claw Unique Pack
2. Walk near them at an angle that gets you close to just 1 or a small number of them.
3. Observe those few wake up, but not the whole pack.

### Expected Behavior

When any one of the Blood Claw unique pack wakes up, they all should.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by StephenCWills**
~~Not tested, but~~ this looks like the right place to reintroduce the logic.

This resolves #7448

### CODE REVIEW

**Comment by StephenCWills** [comment]
I'm testing now, and this doesn't work right. Switching to draft.

**Comment by StephenCWills** [comment]
The trick is that `GroupUnity()` only gets called when `monster.mode` transitions from one state to another.

Gargoyles start with `MonsterMode::SpecialMeleeAttack` and `MFLAG_ALLOW_SPECIAL`. This particular combination makes them stay in stone form until they're disturbed by the player. Whent hey are awoken, the `MFLAG_ALLOW_SPECIAL` flag is removed. If they ever go back into stone form, they will be given `MFLAG_ALLOW_SPECIAL` with `MonsterMode::Heal`. That mode will eventually wake them when their hp is full.

Since `GroupUnity()` only gets called when `monster.mode` transitions, the first time it gets called is when the Gargoyle first transitions from `MonsterMode::SpecialMeleeAttack` to `MonsterMode::Stand`. You can see this as a delay, where the first monster that wakes up will wake up the leader at the end of his first animation, then the leader will wake up the pack at the end of his first animation.

On the other hand, `FollowTheLeader()` gets called unconditionally on every frame. We can't move the logic to this function unless we explicitly check whether the leader is dormant or not. Not that the behavior is slightly different from vanilla. If you wake up the leader, all the other Gargoyles will immediately wake up with him. If you wake up a minion, the rest of the pack will wake up simultaneously at the end of its first animation.

**Comment by StephenCWills** [comment]
I should probably mention I consider this ready now, in case it wasn't clear.

**Comment by StephenCWills** [comment]
Tweaked to better match vanilla behavior. It only checks `leader->mode == MonsterMode::SpecialMeleeAttack` without checking `leader->flags & MFLAG_ALLOW_SPECIAL` to ensure that the leader of the pack has fully finished his waking animation before waking the rest of the pack.

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
