### PR TITLE
prevent possible long/infinite loops by not relying on random

### PR DESCRIPTION
**Pull request by pionere**
use better loops to find matching shrine/stat/item.

### CODE REVIEW

**Comment by AJenbo** [comment]
please provide unit test with these cleanups so that we can easily verify the behavior.

**Comment by pionere** [comment]
how exactly do you expect to unit test a code which depends on random()?

**Comment by yuripourre** [comment]
@pionere if you need deterministic tests, you can provide a seed to random

**Comment by qndel** [comment]
be aware that by modifying/changing the sequence of random calls you might affect everything else, I think we managed to keep things the same so far = if you played devilutionx and vanilla side by side I'd expect same things to happen

**Pull request closed without merging**
