### PR TITLE
Wii U support

### PR DESCRIPTION
**Pull request by GaryOderNichts**
This draft tries to continue what #5944 started, by getting the Wii U builds into a workable state.
It currently boots into the game but has very slow loading times and some graphical/performance issues.

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by szablewskidex** [comment]
Can u make wii build so i can test on my wii? I cant do it on myself

**Comment by AJenbo** [comment]
if you go to the check list you can download the test build from there

**Comment by szablewskidex** [comment]
i dont see check list

**Comment by AJenbo** [comment]
Go to the mentioned PR instead of this one. Wii U support is still WIP

**Comment by szablewskidex** [comment]
i cant see it in mentioned PR, i dig through all here and still nothing, can u please send me link?

**Comment by AJenbo** [comment]
link changes everytime there is an update, read the instructions on the main page or try the chat

**Pull request merged**
