### PR TITLE
Remove miniwin

### PR DESCRIPTION
**Pull request by glebm**
Event handling code moved to `engine/events.{hpp,cpp}`.

### CODE REVIEW

**Comment by AJenbo** [comment]
looks like there is a missing import:
`/root/repo/Source/platform/vita/touch.cpp:233:4: error: 'SetMouseButtonEvent' was not declared in this scope; did you mean 'SetMouseMotionEvent'?`

**Comment by AJenbo** [comment]
This project was born from miniwin, but it's eradication is also worth some celebration since it removes the last of the legacy API connections :tada:

**Review by AJenbo — COMMENTED** [review]
looks like there is a missing import:
`/root/repo/Source/platform/vita/touch.cpp:233:4: error: 'SetMouseButtonEvent' was not declared in this scope; did you mean 'SetMouseMotionEvent'?`

**Comment by glebm** [comment]
Done!

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
